- CONTRIBUTING.md
[x ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/<reponame>/blob/master/CONTRIBUTING.md).
Adds information on how to build on a Windows machine.
This will hopefully reduce the barrier of entry for Windows users to contribute.
I followed this process to enable building on a Windows 7 64-bit development machine.
> Updating contributing

- build/helper.py
* This fixes #64 
* Correct way to compare strings
* Travis + system test
> Use == and != instead of is and is not

- src/nidmm/system_tests/test_system_nidmm.py
* Use NI-ModInst to find device for system test
* Makes system test easier to use
> Fix #70 - Use ModInst to select device

- build/defines.mak
- build/helper.py
- build/templates/attributes.rst.mako
- build/templates/session.py.mako
- build/templates/session.rst.mako
- docs/nidmm.rst
- docs/nidmm/attributes.rst
- docs/nidmm/session.rst
- docs/nimodinst.rst
- docs/nimodinst/attributes.rst
- docs/nimodinst/session.rst
- generated/command_history.bat
- generated/command_history.sh
- generated/nidmm/session.py
- generated/nimodinst/session.py
- src/nidmm/metadata/attributes.py
- src/nimodinst/templates/session.py.mako
* Moves full attribute descriptions to separate file
* Order attributes by name rather than attr id
* Remove active channel attribute
* Cleaner documentation
* Travis & ReadTheDocss
> Implement some Tech Writer feedback

- build/templates/session.py.mako
- generated/nidmm/session.py
- src/nidmm/system_tests/test_system_nidmm.py
* Fixes #95 
* Remove support for ViSession attributes
* Remove ViSession attribute test
* Use new, correct enum values
* Fixes issues
> Fix system test

- build/rules.mak
- src/nimodinst/nimodinst.mak
* Fixes #91
* Add driver to prints
* Fixes issue
* Travis
> Add driver to prints

- build/Makefile
- build/templates/setup.py.mako
- generated/nidmm/setup.py
- generated/nimodinst/setup.py
* Fixes #90
* Clean up multuple warnings and extraneous messages
* Fix issue
> Clean up multuple warnings and extraneous messages

- build/defines.mak
- build/rules.mak
* Files built from templates should depend on metadata as well
* Trigger build of generated files when metadata changes
* Improves build process
* Travis
> Files built from templates should depend on metadata as well

- build/templates/attributes.rst.mako
- build/templates/ctypes_library.py.mako
- build/templates/enums.py.mako
- build/templates/enums.rst.mako
- build/templates/errors.py.mako
- build/templates/mock_helper.py.mako
- build/templates/session.py.mako
- build/templates/session.rst.mako
- src/nidmm/metadata/__init__.py
- src/nimodinst/metadata/__init__.py
- src/nimodinst/templates/session.py.mako
* Less to pass around to have all metadata
* Need functions and attribute metadata to fix up links in function documentation.
* Needed for docs/function_help
* Travis
> Put the attribute, enums and functions dictionaries as part of config

- build/rules.mak
* This is not invoking tox, just run a quick pytest on the generated files
* Fixes #124 
* Fixes issue
* Travis
* Building multiple time under different circumstances
> Run the unit tests every time

- src/nidmm/system_tests/test_system_nidmm.py
Adds system tests for invalid attribute value error check and ViInt32 output function
Increases coverage of system tests
Tested on a local machine and passes
> System tests for invalid attribute value error and Int output function.

- build/Makefile
- build/templates/setup.py.mako
* Fixes #172 
* Suppress problematic make output
* Set zip_safe=True to remove warning
* Fixes issue
* Travis
> Clean up build output

- docs/index.rst
[x ] This contribution adheres to [CONTRIBUTING.md]
Fixes #155 
To solve the issue with the bad title
Built and Ran unit tests
> Updating title

- CONTRIBUTING.md
* Updates lots of outdated information.
* Removes several TODOs
* Fixes Markdown syntax problems.
* Fixes #107 
Lots of improvements. Should make it easy for new developers to get up and running.
None
> Update Contributing in order to match the repos state

- tox.ini
* Move all configuration to testenv section
* This allows more sharing
* More concise
* Cleans up tox.in
* Travis
> Consolidate tox.ini sections

- build/templates/library_singleton.py.mako
- build/templates/session.py.mako
- generated/nidmm/library_singleton.py
- generated/nidmm/session.py
- generated/nidmm/tests/test_session.py
- generated/nifake/library_singleton.py
- generated/nifake/session.py
- generated/nifake/tests/test_session.py
- generated/nimodinst/library_singleton.py
- generated/nimodinst/session.py
- generated/nimodinst/tests/test_modinst.py
- src/nidmm/tests/test_session.py
- src/nifake/tests/test_session.py
- src/nimodinst/templates/session.py.mako
- src/nimodinst/tests/test_modinst.py
Fix #214 
Simplify interface for getting the Library singleton.
Nothing works without this fix.
Ran NI-DMM and NI-ModInst example.
> Fix getting Library singleton (#214)

- build/rules.mak
* Fixes #218 
* Needed for #217 
* Fixes incorrect dependency
* Travis
> Move dependency on RST_FILES to copy_generated_files rule

- build/templates/errors.py.mako
- build/templates/session.py.mako
- src/nifake/tests/test_session.py
- src/nimodinst/templates/session.py.mako
Cleans up how we handle errors.
* Decouples Eror classes from session
* Simplifies Session method for getting error descriptions
* Improves handle_error function
* No longer prefixed with _
* Knows how to handle warnings, simplifies generated code.
* Generated code no longer calls private functions in errors.
Improves error handling code.
Unit tests and some local tests were run.
> Clean up error handling

- generated/nidmm/errors.py
- generated/nidmm/session.py
- generated/nifake/errors.py
- generated/nifake/session.py
- generated/nifake/tests/test_session.py
- generated/nimodinst/errors.py
- generated/nimodinst/session.py
- generated/nimodinst/tests/test_modinst.py
- src/nimodinst/tests/test_modinst.py
* Fixes master branch build
* Fixes build
* Travis
> Master branch build broken - fix

- build/metadata_utilities.py
- src/nidmm/metadata/__init__.py
- src/nifake/metadata/__init__.py
- src/nimodinst/metadata/__init__.py
- src/niswitch/metadata/__init__.py
* Fixes #255 
* Create shared implementation of merge_dicts used in all metadata modules
* Use new shared implementation
* Reduces redundancy
* Travis & system tests
> Use shared implementation for merge_dicts

- build/templates/session.py.mako
- generated/nidmm/session.py
- generated/nifake/session.py
- generated/niswitch/session.py
* Fixes #278 
* Changes default value for id_query to False
* Fixes issue
* Cleans up code
* Travis & System tests
> Fix default value in Session.__init__

- build/helper.py
- docs/nidmm/functions.rst
- docs/nifake/functions.rst
- docs/niswitch/functions.rst
* Fixes #279 
* Use the intrinsic type for the return type
* Make the description separate from the type descritpion
* Clean up documentation
* Travis & System tests
* Visual inspection of generated html
> Fix method return value documentation

- tox.ini
* Add JUnit output from pytest when running system tests
* Needed to keep system_tests from failing due to missing files.
* Fix incorrect test failure
* system tests
> Add junit output from system tests

- .coveragerc
- build/Makefile
- build/__init__.py
- build/__main__.py
- build/generate_template.py
- build/helper.py
- build/metadata_utilities.py
- build/utilities.py
- generated/nifake/tests/test_session.py
- tox.ini
* Fixes #294 
* Fixes #283 
* Test the build scripts before using them.
* Adds build script tests to code coverage metrics
* Add flake8 testing to build scripts
* Then fix numerous flake8 violations in build scripts
* More correct
* Travis
> Test build scripts before running codegen

- build/templates/session.py.mako
- generated/nidmm/session.py
- generated/nifake/session.py
- generated/nifake/tests/test_session.py
- generated/niswitch/session.py
- src/nidmm/metadata/config.py
- src/nifake/metadata/config.py
- src/niswitch/metadata/config.py
* Fixes #267 
* Driver metadata no longer has list of directions.
* Only one context manager per driver
* Name explicitly in metadata
* Fixes issue
* Simplifies code
* Travis
* System tests
> Context manager name in metadata

- generated/nifake/tests/test_session.py
- src/nifake/tests/test_session.py
Adds a unit test for getting an attribute of type enum.
Improves unit test coverage.
Unit test passes!
> add test_get_enum_attribute

- build/defines.mak
- build/templates/attributes.py.mako
- build/templates/session.py.mako
- generated/nidmm/attributes.py
- generated/nidmm/session.py
- generated/nifake/attributes.py
- generated/nifake/session.py
- generated/nimodinst/attributes.py
- generated/niswitch/attributes.py
- generated/niswitch/session.py
Attribute classes are now in their own file.
Cleans up our codebase.
Unit tests and nimi-bot system tests.
> Move Attribute classes to its own file.

- generated/nifake/tests/test_session.py
- src/nifake/tests/test_session.py
[X ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/<reponame>/blob/master/CONTRIBUTING.md).
Adds a unit test that checks Initializing with non default parameters
It increases areas being tested
Ran on a local machine and it passes
> Added Unit test for initializing with all non default parameters

- build/templates/examples.rst.mako
[ x] This contribution adheres to [CONTRIBUTING.md]
Fixes #314 
Allows people with windows machine to build the code and get correctly generated rst strings.
Built and ran system tests
> Fixing bug 314 by replacing backward slashes with forward slashes

- generated/nifake/tests/test_session.py
- src/nifake/tests/test_session.py
Cleans unit tests a bit.
Code improvements.
Ran tests.
> Minor test cleanup

- src/niswitch/system_tests/test_system_niswitch.py
[x] This contribution adheres to [CONTRIBUTING.md]
This adds system tests for NI-SWITCH functions that are not related to scanning.
This improves coverage
Built and ran. Ran system tests
> Updating System tests to test all remaining non-scanning functions

- docs/nidmm/functions.rst
- docs/niswitch/functions.rst
- generated/nidmm/library.py
- generated/nidmm/session.py
- generated/nidmm/tests/mock_helper.py
- generated/niswitch/library.py
- generated/niswitch/session.py
- generated/niswitch/tests/mock_helper.py
- src/nidmm/metadata/functions_addon.py
- src/nidmm/system_tests/test_system_nidmm.py
- src/niswitch/metadata/functions_addon.py
- src/niswitch/system_tests/test_system_niswitch.py
[x ] This contribution adheres to [CONTRIBUTING.md]
Fixes #359
Fixes #358 
Fixes #357 
Fixes #356   
Fixes #355  
Fixes #342 
To remove unwanted and unused APIs
Built and ran system / unit tests
> Remove unwanted functions

- CHANGELOG.md
- build/helper/metadata_add_all.py
- docs/nidmm/functions.rst
- generated/nidmm/session.py
- src/nidmm/examples/nidmm_fetch_waveform.py
- src/nidmm/examples/nidmm_measurement.py
- src/nidmm/examples/nidmm_multi_point_measurement.py
- src/nidmm/metadata/functions_addon.py
- src/nidmm/system_tests/test_system_nidmm.py
[ x] This contribution adheres to [CONTRIBUTING.md]
Fixes #298 
To add default metadata for NI-DMM
Ran unit tests and system tests. Ran all examples on sample device.
> Add default values for parameters for NI-DMM

- build/helper/__init__.py
- build/helper/codegen_helper.py
- build/helper/documentation_helper.py
- build/helper/metadata_filters.py
- build/templates/functions.rst.mako
- build/templates/library.py.mako
- build/templates/mock_helper.py.mako
- build/templates/session.py.mako
- build/templates/session.rst.mako
- src/nimodinst/templates/session.py.mako
Improves naming of functions in code generator.
General improvement.
tox
> Rename extract_* functions to filter_*

- tools/build_dev_release.py
- tools/install_local_wheel.py
- tools/run_python_system_tests.py
- tools/updateDevVersions.py
- tox.ini
[x] This contribution adheres to [CONTRIBUTING.md]
Adds driver specific system tests.
This is required for internal test suites to run only the specific driver.
Ran both nidmm and niswitch. Verified released python packages were installed (saw errors due to default parameters change).
> Adding nidmm and niswitch tox system test functions

- .github/PULL_REQUEST_TEMPLATE.md
Updates the PR template to be more useful. Specifically it will make it harder to forget updating CHANGELOG and listing fixes.
Better PRs
None
> Update PR template to more closely match project's needs

- build/templates/examples.rst.mako
- docs/nidmm/examples.rst
- docs/nimodinst/examples.rst
- docs/niswitch/examples.rst
~~[] I've updated [CHANGELOG.md](https://github.com/ni/<reponame>/blob/master/CHANGELOG.md) if applicable.~~
* Improves documentation
* Fix #376 
* Visual inspection of generated documentation
* Travis & system tests
> Fix examples documentation page to show all examples

- tools/install.bat
It’s stale and a maintenance burden. I assume nobody uses it.
N/A
Removes a script that appears to be stale. If nobody uses it, I'd rather not have it.
N/A
N/A
> Remove unused script

- src/nimodinst/nimodinst.mak
* Improves build process
* Add dependency on metadata files for modinst session.py rule
* Fix #292 
* Manual edit & build
> ModInst session.py now rebuilds after change to metadata

- build/helper/metadata_add_all.py
This breaks unit test. See #399
[X ] I've updated [CHANGELOG.md](https://github.com/ni/<reponame>/blob/master/CHANGELOG.md) if applicable.
N/A
Reverts breaking change to unit test.
N/A
Tox not passes.
> Back out PR #386

- build/templates/examples.rst.mako
- docs/nidcpower/examples.rst
- docs/nidmm/examples.rst
- docs/niswitch/examples.rst
* Make examples order in documentation sorted (I.e. deterministic) so that there are not changes in PR that are there only because they got added in a different order
* Fix #403 
* Manual inspection of generated examples.rst
* Travis &  system tests
> Make example order deterministic

- build/helper/__init__.py
- build/helper/codegen_helper.py
- build/helper/documentation_helper.py
- build/templates/library.py.mako
- build/templates/mock_helper.py.mako
- build/templates/session.py.mako
- build/templates/session.rst.mako
- src/nimodinst/templates/session.py.mako
~~[X] I've updated [CHANGELOG.md](https://github.com/ni/<reponame>/blob/master/CHANGELOG.md) if applicable.~~
* Rename ParamListType to ParameterUsageOptions
* Rename ParamListTypeDefaults to _parameterUsageOptions
* Add option to skip_input_parameters
* get_params_snippet() is  split up into filter_parameters() and
get_params_snippet()
This will be used in future PRs.
~~### List issues fixed by this Pull Request below, if any.~~
tox
> Break up get_params_snippet()

- src/nidmm/system_tests/test_system_nidmm.py
Adding more system tests for nidmm
- test_fetch_waveform
- test_fetch_waveform_error
- test_get_measurement_peiod
- test_perform_cable_compensation
- test_read_waveform
- test_send_software_trigger
- test_reset_method
Pytest passed on dev machine
> Adding system tests for uncovered dmm methods

- build/helper/documentation_helper.py
Adding more system tests for documentation helper
- test_get_function_rst
- test_get_function_docstring
- test_get_rst_header_snippet
- test_get_documentation_for_node_docstring
tox and system tests are passing on dev machine
> adding unit tests for documentation helper

- build/helper/documentation_helper.py
Fixed failing **test test_get_function_docstring**
* Fix #425 
tox, systemtests on local machine
> added missing space caused test to fail

- src/nidmm/system_tests/test_system_nidmm.py
Adding nidmm system tests,
- test_error_message
- test_set_boolean_attribute
* Fix #202 
tox, systemtests are passing on dev machine
> Adding system test for nidmm

- build/templates/mock_helper.py.mako
- generated/nidcpower/tests/mock_helper.py
- generated/nidmm/tests/mock_helper.py
- generated/nifake/tests/mock_helper.py
- generated/niswitch/tests/mock_helper.py
* Remove assert that the buffer length was the same as the test value
* This didn't work for functions that expected a fixed size buffer
* Removed altogether
* Fix #429 
* Travis
* System tests
> Remove assert in mock_helper

- .github/PULL_REQUEST_TEMPLATE.md
* Fix the paths in the urls in PULL_REQUEST_TEMPLATE.md to point to this repo
> Fix links in PULL_REQUEST_TEMPLATE

- tox.ini
Updating tox to have pytest-json as dependency to output results as json. (Want this dependency to update results in internal elasticsearch server).
invoked systemtest tox environment in dev system
> updating tox.ini for system tests reporting

- .github/PULL_REQUEST_TEMPLATE.md
* Add a checkbox to the pull request template to remind everyone to add unit tests if applicable
* Travis
* System tests
> Add check box for unit tests

- CHANGELOG.md
* Adds table of contents to CHANGELOG.md
* Move some content around
* Travis
* System tests
> Add table of contents to changelog

- tools/run_python_system_tests.py
[x ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
Allows system test runner to work as expected. 
This is required because at the time when we had the 0.1 and 0.2 release, all characters on the releases website were ascii. With the 0.3 release a character was added to the releases page that was utf-8.
Ran tool
> Updating to use utf-8 for run_python_system_tests.py

- src/nidcpower/system_tests/test_system_nidcpower.py
Adding systemtests for nidcpower.
- test_commit_after_initiate
- test_get_self_cal_last_date_and_time
- test_get_self_cal_last_temp
- test_read_current_temperature
- test_reset_device
- test_reset_with_default
- test_reset
- test_disable
Partial fix #390 
tox, systemtests.
> Adding more dcpower system tests

- README.rst
* Remove scale command from badges in README.rst
* GitHub ignores them anyway
* Some don't return fast enough during the build causing warnings
* Fix #476 
* Unit
* System
> Remove scale command from images

- CHANGELOG.md
- src/nidcpower/examples/nidcpower_measure_record.py
- src/nidcpower/examples/nidcpower_source_delay_measure.py
- src/nidmm/examples/nidmm_fetch_waveform.py
- src/nidmm/examples/nidmm_measurement.py
- src/nidmm/examples/nidmm_multi_point_measurement.py
- src/nifgen/examples/nifgen_placeholder.py
- src/nimodinst/examples/nimodinst_all_devices.py
- src/niswitch/examples/niswitch_connect_channels.py
- src/niswitch/examples/niswitch_get_device_info.py
- src/niswitch/examples/niswitch_relay_control.py
~~[] I've added any unit tests that are applicable for this pull request~~
Simplifies examples:
* No try/except clause, removing extraneous code
* Errors are reported with full stack, which is more "Pythonic"
* No need to import sys anymore.
Also:
* Improves output of src/nidmm/examples/nidmm_fetch_waveform.py
* Fix #509 
Ran examples.
> Remove try/except from examples

- build/helper/metadata_add_all.py
- src/nidcpower/metadata/__init__.py
- src/nidcpower/metadata/functions_addon.py
- src/nidmm/metadata/__init__.py
- src/nidmm/metadata/functions_addon.py
- src/nifake/metadata/__init__.py
- src/nifake/metadata/functions_addon.py
- src/nifgen/metadata/__init__.py
- src/nifgen/metadata/functions_addon.py
- src/nimodinst/metadata/__init__.py
- src/nimodinst/metadata/functions_addon.py
* Instead of each metadata package having to merge any applicable dictionaries, common function adds any variables that in 'metadata.functions_addon' that start with 'functions_'
* Had to rename to ensure naming convention met.
* System
* Unit
> Move metadata dictionary merge to common location

- src/nifgen/system_tests/test_system_nifgen.py
- tox.ini
[ ] I've added any unit tests that are applicable for this pull request
Adding system tests for nifgen.
- test_self_test
- test_get_attribute_string
- test_error_message
- test_get_error
- test_method_get_self_cal_supported
- test_get_self_cal_last_date_and_time
- test_self_cal
Partial * Fix #484 
System tests,tox
> Adding system tests for nifgen

- build/templates/library.py.mako
- build/templates/library_singleton.py.mako
- generated/nidcpower/library.py
- generated/nidcpower/library_singleton.py
- generated/nidmm/library.py
- generated/nidmm/library_singleton.py
- generated/nifake/library.py
- generated/nifake/library_singleton.py
- generated/nifgen/library.py
- generated/nifgen/library_singleton.py
- generated/nimodinst/library.py
- generated/nimodinst/library_singleton.py
- generated/niscope/library.py
- generated/niscope/library_singleton.py
- generated/niswitch/library.py
- generated/niswitch/library_singleton.py
[ ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
Uses dependency injection of the ctypes library into out Library class so that we don't need to use #pragmas in the Library.py 
* Fix #317 
tox and system tests
>  Inject ctypes library into nifoo.Library so we can better unit test it

- src/nifgen/system_tests/test_system_nifgen.py
System tests for nifgen
- test_create_waveform
- test_disable
- test_get_ext_cal_last_date_and_time
- test_get_ext_cal_last_temp
- test_get_ext_cal_recommended_interval
- test_get_hardware_state
- test_get_self_cal_last_temp
- test_query_arb_wfm_capabilities
- test_query_freq_list_capabilities
- test_read_current_temperature
Partial * Fix #484 
tox, system tests
> Adding more system tests for nifgen

- src/nidcpower/metadata/functions_addon.py
- src/nidmm/metadata/functions_addon.py
- src/nifake/metadata/functions_addon.py
- src/nifgen/metadata/functions_addon.py
- src/nimodinst/metadata/functions_addon.py
- src/niscope/metadata/functions_addon.py
- src/niswitch/metadata/functions_addon.py
[X] I've added any unit tests that are applicable for this pull request
Remove duplicate and incomplete documentation in each functions_addon.py, which was moved and updated to the [wiki](https://github.com/ni/nimi-python/wiki/API-Metadata).
* Fix #545 
Ran generator and verified none of the output files get modified.
> DRY comments in functions_addon.py

- .gitignore
- tox.ini
Updating tox to report results as <root>\bin\kibana\ni<driver>_systemtests.json
* Fix #567 
tox, systemtests
> updated systemtest environment to report results inside bin folder

- build/Makefile
- build/helper/__init__.py
- build/helper/metadata_add_all.py
- src/nidcpower/metadata/__init__.py
- src/nidmm/metadata/__init__.py
- src/nifake/metadata/__init__.py
- src/nifgen/metadata/__init__.py
- src/nimodinst/metadata/__init__.py
- src/niscope/metadata/__init__.py
- src/niswitch/metadata/__init__.py
- tox.ini
* Persist metadata after all merging and additions to bin/metadata
* Visual inspection
* Unit
* System
> Persist metadata after all processing (easier debugging)

- generated/nifake/tests/test_session.py
- src/nifake/tests/test_session.py
~~[] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~~
Code cleanup, more pythonic for loops in a few places.
N/A
Ran the tests.
> Use zip in tests to make for loops more "pythonic"

- src/niscope/system_tests/test_system_niscope.py
Adding initial set of system tests for niscope
- test_self_test
- test_reset
- test_reset_device
- test_reset_with_defaults
- test_get_error
Partial * Fix #520
Systemtests, tox
> Adding niscope system tests

- src/nifake/unit_tests/test_session.py
- tox.ini
* Add support for testing 32 bit as well as 64 bit on nimi-bot
* Fix unit test issue on Windows Python 2.7
* Requires corresponding change on nimi-bit to use
* Unit
* System
> Add support for testing 32 bit

- CONTRIBUTING.md
* Improve wording and instructions in CONTRIBUTING.md
* How to configure Windows when not using WSL
* N/A
> Update CONTRIBUTING for recent changes to tox

- src/niscope/system_tests/test_system_niscope.py
Adding more system tests for niscope.
test_configure_ref_levels
test_configure_trigger_digital
test_configure_trigger_edge
test_configure_trigger_hysteresis
test_configure_trigger_software
test_configure_trigger_video
test_configure_trigger_window
test_fetch_read_measuremet
Partial Fix #520 
tox, system tests
> Adding more niscope systemtests

- src/niscope/system_tests/test_system_niscope.py
[ x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
Removes system tests with NI-SCOPE that cause failures.
* Fix #651 
Ran flake8 and system tests
> Removing the two system tests that cause intermittent failures

- README.rst
Makes instructions for building more discoverable.
~~### List issues fixed by this Pull Request below, if any.~~
Clicked link, it works.
> Link to CONTRIBUTING.md from README.rst so people can find the instructions

- CHANGELOG.md
- build/helper/codegen_helper.py
- build/helper/metadata_add_all.py
- build/helper/metadata_filters.py
- generated/nidcpower/session.py
- generated/nidmm/session.py
- generated/nifake/session.py
- generated/nifake/unit_tests/test_session.py
- src/nidcpower/examples/nidcpower_measure_record.py
- src/nidcpower/metadata/functions_addon.py
- src/nidcpower/system_tests/test_system_nidcpower.py
- src/nidmm/examples/nidmm_fetch_waveform.py
- src/nidmm/examples/nidmm_multi_point_measurement.py
- src/nidmm/metadata/functions_addon.py
- src/nidmm/system_tests/test_system_nidmm.py
- src/nifake/metadata/functions_addon.py
- src/nifake/unit_tests/test_session.py
[X] I've ~~added~~updated tests applicable for this pull request
* Add option to code generator to allow skipping some parameters in the Python API.
* Right now, only used for return list
* Fix #635 
* Unit
* System
> There are some return parameters that don't make sense in Python so don't return them

- build/helper/documentation_helper.py
- build/helper/metadata_add_all.py
- build/helper/metadata_filters.py
- build/templates/session.py/numpy_read_method.py.mako
- docs/nidmm/functions.rst
- generated/nidmm/session.py
- generated/nifake/session.py
- generated/nifake/unit_tests/test_session.py
- generated/nifgen/session.py
- generated/niscope/session.py
- numpy TODO.md
- src/nidmm/system_tests/test_system_nidmm.py
- src/nifake/unit_tests/test_session.py
- src/niscope/metadata/functions_addon.py
- src/niscope/system_tests/test_system_niscope.py
- src/niscope/templates/session.py/fetch_waveform.py.mako
[X] I've ~~added~~updated tests applicable for this pull request
* Unit
* System
> Skip size parameters for `_into` functions

- tox.ini
Adding numpy dependency to <nidriver>_systemtests environments
niscope_system_tests
nidmm_system_tests
nifgen_system_tests
* Fix #711 
tox, systemtests
> Adding dependency to system_test environments

- .github/PULL_REQUEST_TEMPLATE.md
* Update PULL_REQUEST_TEMPLATE.md to have real check boxes
* Update wording on CHANGELOG checkbox to indicate check always required.
> [4]Update PULL_REQUEST_TEMPLATE

- generated/nimodinst/session.py
- src/nidcpower/examples/nidcpower_advanced_sequence.py
- src/nidcpower/examples/nidcpower_measure_record.py
- src/nidcpower/examples/nidcpower_source_delay_measure.py
- src/nidmm/examples/nidmm_fetch_waveform.py
- src/nidmm/examples/nidmm_measurement.py
- src/nidmm/examples/nidmm_multi_point_measurement.py
- src/nifgen/examples/nifgen_arb_waveform.py
- src/nifgen/examples/nifgen_standard_function.py
- src/nimodinst/examples/nimodinst_all_devices.py
- src/nimodinst/templates/session.py.mako
- src/niscope/examples/niscope_fetch.py
- src/niscope/examples/niscope_read.py
- src/niswitch/examples/niswitch_connect_channels.py
- src/niswitch/examples/niswitch_get_device_info.py
- src/niswitch/examples/niswitch_relay_control.py
- tox.ini
* Tests examples (using simulation) as part of system tests
* Ensure no syntax errors
* Ensure they are updated with any breaking changes
* Fix multiple issues in examples new testing uncovered
* Fix logic bug in nimodinst session iteration
* Fix #563 
* Unit
* System
> [4]Test examples

- docs/_static/nidcpower_usage.inc
* Make the sample in the nidcpower usage documentation snippet complete
* add with nidcpower.Session ...
* Fix #757 
* Unit
* System
> Fix sample in usage snippet

- build/templates/errors.py.mako
- generated/nidcpower/errors.py
- generated/nidmm/errors.py
- generated/nifake/errors.py
- generated/nifgen/errors.py
- generated/nimodinst/errors.py
- generated/niscope/errors.py
- generated/niscope/library_singleton.py
- generated/niswitch/errors.py
- src/niscope/metadata/config.py
* Adds bitness mismatch as possible reason for not being about to load runtime
* Fix Scope name
* Unit
* System
> Update error text when driver not loadable

- src/nidmm/examples/nidmm_fetch_waveform.py
* Remove unused digit parameter in nidmm waveform example
* Digit is not applicable to waveform mode
* Fix #771 
* System
> Remove unused digit parameter

- CHANGELOG.md
- build/templates/errors.py.mako
- build/templates/session.py.mako
- generated/nidcpower/errors.py
- generated/nidcpower/session.py
- generated/nidmm/errors.py
- generated/nidmm/session.py
- generated/nifake/errors.py
- generated/nifake/session.py
- generated/nifgen/errors.py
- generated/nifgen/session.py
- generated/nimodinst/errors.py
- generated/niscope/errors.py
- generated/niscope/session.py
- generated/niswitch/errors.py
- generated/niswitch/session.py
* All exceptions that can be raised by the Python bindings now inherit from `<driver>.Error`
* `<driver>._ErrorBase` removed
* Any error returned by the underlying driver will now be raised as `<driver>.DriverError`
* Fix #784 
* Unit
* System
> Clean up errors

- docs/nidcpower/functions.rst
- docs/nidmm/functions.rst
- docs/nifgen/functions.rst
- docs/niscope/functions.rst
- docs/niswitch/functions.rst
- generated/nidcpower/session.py
- generated/nidmm/session.py
- generated/nifgen/session.py
- generated/niscope/session.py
- generated/niswitch/session.py
- src/nidcpower/metadata/functions_addon.py
- src/nidmm/metadata/functions_addon.py
- src/nifgen/metadata/functions_addon.py
- src/niscope/metadata/functions_addon.py
- src/niswitch/metadata/functions_addon.py
* Old exception name in `self_test()` documentation - fixed
* Fix #798 
* Unit
* System
> Fix exception name in self_test documentation

- CHANGELOG.md
- docs/nidcpower/functions.rst
- generated/nidcpower/session.py
- src/nidcpower/metadata/functions_addon.py
* Remove default value for values parameter on `nidcpower.Session.set_sequence()`
* Fix #797 
* Unit
* System
* Visual inspection of generated code
> Remove default value for values parameter on set_sequence()

- build/templates/installation.inc.mako
- docs/nidcpower/installation.inc
- docs/nidmm/installation.inc
- docs/nifgen/installation.inc
- docs/nimodinst/installation.inc
- docs/niscope/installation.inc
- docs/niswitch/installation.inc
* Add compatibility version for installation instructions per [PEP 440](https://www.python.org/dev/peps/pep-0440/#compatible-release)
* Fix #734 
> Update install instruction to add compatibility version

- build/Makefile
* Delete generated folder when running `make clean`
* Fix #821 
* Visual inspection
> Clean generated

- docs/nidcpower/attributes.rst
- docs/nidcpower/functions.rst
- generated/nidcpower/session.py
- src/nidcpower/metadata/functions_addon.py
* Set `'public_method_name'` for `initiate` so that documentation doesn't point to a private method
* Fix #826 
* Visual inspection of generated documentation
> Update documentation to reference public initiate()

- build/helper/documentation_helper.py
- build/helper/metadata_add_all.py
- src/nidcpower/metadata/functions_addon.py
- src/nidmm/metadata/functions_addon.py
- src/nifgen/metadata/functions_addon.py
- src/niscope/metadata/functions_addon.py
- src/niswitch/metadata/functions_addon.py
* Rename 'public_method_name' to 'method_name_for_documentation'
* Fix #829 
* Visual inspection of generated files for no changes
> Rename 'public_method_name' to 'method_name_for_documentation'

- CHANGELOG.md
- docs/nifgen/class.rst
- generated/nifgen/enums.py
- generated/nifgen/session.py
- src/nifgen/metadata/attributes.py
- src/nifgen/metadata/enums.py
- src/nifgen/system_tests/test_system_nifgen.py
* Fix in extraction tool to remove additional quote around some strings
* Incorporate NI-FGEN change to rename `num_channels` attribute to `channel_count`
* Fix #876 
* Unit
* System
> Update extracted metadata

- CHANGELOG.md
- docs/nidmm/class.rst
- docs/nidmm/enums.rst
- generated/nidmm/_library.py
- generated/nidmm/enums.py
- generated/nidmm/session.py
- generated/nidmm/unit_tests/_mock_helper.py
- src/nidmm/metadata/attributes_addon.py
- src/nidmm/metadata/functions_addon.py
- src/nidmm/system_tests/test_system_nidmm.py
* Remove attributes and functions that only apply to EOL HW
* Fix #875 
* Unit
* System
> Remove attributes and functions that only apply to EOL HW

- CHANGELOG.md
- generated/nimodinst/session.py
- src/nimodinst/templates/session.py.mako
* Fix issues found during nimodinst review
* Make `get_next()` helper function private
* Allow double close to return driver error - same as other drivers
* Fix #882 
* `device` --> `devices` already done
* Unit
* System
> Changes from nimodinst review

- CHANGELOG.md
- docs/niswitch/class.rst
- generated/niswitch/_library.py
- generated/niswitch/session.py
- generated/niswitch/unit_tests/_mock_helper.py
- src/niswitch/metadata/attributes_addon.py
- src/niswitch/metadata/functions_addon.py
- src/niswitch/system_tests/test_system_niswitch.py
* Changes from niswitch review
* Remove attributes that only apply to EOL HW
* `cabled_module_scan_advanced_bus`
* `cabled_module_trigger_bus`
* `master_slave_scan_advanced_bus`
* `master_slave_trigger_bus`
* `parsed_scan_list`
* `trigger_mode`
* `scan_advanced_polarity`
* `trigger_input_polarity`
* Remove methods that have attributes to set
* `configure_scan_list()`
* `configure_scan_trigger()`
* `route_trigger_input()`
* `set_continuous_scan()`
* Fix #881 
* Unit
* System
> Changes from niswitch review

- build/helper/__init__.py
- build/helper/documentation_helper.py
- build/helper/documentation_snippets.py
- build/helper/metadata_add_all.py
- build/templates/class.rst.mako
- build/templates/session.py.mako
- docs/nidcpower/class.rst
- docs/nifgen/class.rst
- docs/niscope/class.rst
- docs/niswitch/class.rst
- generated/nidcpower/session.py
- generated/nidmm/session.py
- generated/nifake/session.py
- generated/nifgen/session.py
- generated/niscope/session.py
- generated/niswitch/session.py
- src/nifgen/metadata/attributes_addon.py
* Add repeated capability container information to nifgen (only driver that currently has non 'channels' containers)
* Add default repeated capability container information of 'channels' where appropriate
* Use repeated capability container information in tips
* Fix #854
* Visual inspection of generated html and session files
> Clean up repeated capabilities tip

- build/templates/_converters.py.mako
- generated/nidcpower/_converters.py
- generated/nidmm/_converters.py
- generated/nifake/_converters.py
- generated/nifgen/_converters.py
- generated/nimodinst/_converters.py
- generated/niscope/_converters.py
- generated/niswitch/_converters.py
* Add tests that test other string types for the option string parsing
* Unit
* System
> Add unicode tests

- CHANGELOG.md
- build/__init__.py
- build/templates/__init__.py.mako
- generated/nidcpower/__init__.py
- generated/nidmm/__init__.py
- generated/nifake/__init__.py
- generated/nifake/unit_tests/test_session.py
- generated/nifgen/__init__.py
- generated/nimodinst/__init__.py
- generated/niscope/__init__.py
- generated/niswitch/__init__.py
- src/nifake/unit_tests/test_session.py
* Add `__version__` to each driver
* Fix #928 
* System
* Unit
> Add __version__ to all drivers

- CHANGELOG.md
- generated/niscope/waveform_info.py
- src/niscope/custom_types/waveform_info.py
* Fix formatting when printing a `niscope.WaveformInfo`
* Fix `__repr__` for `niscope.WaveformInfo`
* Fix #920
* Unit
* System
> niscope.WaveformInfo __repr__ and __str__ improvements

- docs/_static/nidcpower_usage.inc
* Makes the nidcpower usage snippet run on more devices
* Add an explicit channel '0'
* Fix #930 
* Unit
* System
> Some devices require a channel

- tox.ini
* Add required `numpy` dependency for nidmm and nifgen system tests in tox.ini
* Ensure pip is up to date before running any test
* Fix #937
* Fix #938 
* Unit
* System
> Add required numpy dependency and update pip

- generated/niscope/session.py
- generated/niscope/waveform_info.py
- src/niscope/custom_types/waveform_info.py
- src/niscope/system_tests/test_system_niscope.py
- src/niscope/templates/session.py/fancy_fetch.py.mako
- src/niscope/templates/session.py/fetch_waveform.py.mako
* Be more explicit with the fields we use in `niscope.WaveformInfo`
* Fix #934 
* System
* Unit
* Hand
> Cleanup waveform info - add explicit fields used

- build/templates/session.py.mako
- docs/nise/class.rst
- generated/nise/session.py
- src/nidcpower/metadata/config.py
- src/nidmm/metadata/config.py
- src/nifake/metadata/config.py
- src/nifgen/metadata/config.py
- src/nimodinst/metadata/config.py
- src/nimodinst/templates/session.py.mako
- src/niscope/metadata/config.py
- src/nise/metadata/config.py
- src/nise/metadata/functions_addon.py
- src/nise/templates/session.py.mako
- src/niswitch/metadata/config.py
* Make close function to call configurable
* Defaults to `close()`
* Update documentation name for nise `CloseSession`
* Fix #898 
* Unit
* System
> Make driver close function to call configurable

- CONTRIBUTING.md
Helps clarify system requirements for building nimi-python
> Help clarify that Windows itself is not a system requirement.

- build/helper/codegen_helper.py
- build/helper/metadata_filters.py
- src/nidcpower/system_tests/test_system_nidcpower.py
- src/nifgen/system_tests/test_system_nifgen.py
- tox.ini
* Requires numpy be less than 1.16
* Due to numpy issue numpy/numpy#12736
* Unit
> Require numpy be less than 1.16

- src/nifgen/examples/nifgen_script.py
- src/niscope/examples/niscope_fetch_forever.py
- [x ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
- [x ] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.
TODO: Check the above box with an 'x' if considered if there were any and then documented client facing changes in [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md). Strike through if this is not a relevant client facing change.
- [x ] I've added tests applicable for this pull request
TODO: Check the above box with an 'x' indicating you have considered and added any applicable system or …
> Fix typo in niscope_fetch_forever example

- generated/nifake/__init__.py
- generated/nifake/_library.py
- generated/nifake/custom_struct.py
- generated/nifake/session.py
- generated/nifake/unit_tests/_mock_helper.py
- generated/nifake/unit_tests/test_session.py
- src/nifake/custom_types/custom_struct.py
- src/nifake/metadata/attributes.py
- src/nifake/metadata/config.py
- src/nifake/metadata/enums.py
- src/nifake/metadata/functions.py
- src/nifake/unit_tests/test_session.py
* Update nifake metadata with the latest build
* Renames custom struct to be consistent with niscope
* Unit
> Update nifake metadata

- src/nidigital/metadata/__init__.py
- src/nidigital/metadata/attributes.py
- src/nidigital/metadata/attributes_addon.py
- src/nidigital/metadata/config.py
- src/nidigital/metadata/config_addon.py
- src/nidigital/metadata/enums.py
- src/nidigital/metadata/enums_addon.py
- src/nidigital/metadata/functions.py
- src/nidigital/metadata/functions_addon.py
* Add nidigital metadata
* But don't do anything with it yet
None yet
> Add nidigital metadata

- README.rst
- docs/nise/status.inc
- src/nise/metadata/attributes.py
- src/nise/metadata/config.py
- src/nise/metadata/enums.py
- src/nise/metadata/functions.py
* Updated nise metadata - nothing major
* Unit
* System
> Update nise metadata

- .codecov.yml
- tools/build_release.py
- tox.ini
* Add .codecov.yml to control the limits for what is allowed to be considered passing
* Unit
* System
> [#1019] Add codecov file to control limits for passing

- CHANGELOG.md
- docs/nise/installation.inc
- generated/nise/__init__.py
- generated/nise/setup.py
- src/nise/metadata/config_addon.py
* Updates nise to 1.9
* Unit
* System
> Update nise to 1.0

- CHANGELOG.md
- build/templates/installation.inc.mako
- docs/nidcpower/installation.inc
- docs/nidigital/installation.inc
- docs/nidmm/installation.inc
- docs/nifgen/installation.inc
- docs/nimodinst/installation.inc
- docs/niscope/installation.inc
- docs/nise/installation.inc
- docs/niswitch/installation.inc
- docs/nitclk/installation.inc
- tox.ini
* Improves installation instructions by not putting a version to pin to. This is confusing in master (what read the docs shows by default) since that version doesn't exist yet.
* This will actually fix the underlying issue in #967 
* Visual inspection of generated installation.inc
> Fix install instructions

- docs/_static/niscope_usage.inc
N/A
N/A
Fix a small typo in `niscope` documentation.
> Fix typo in comment

- README.rst
- docs/_static/about.inc
Removes the image of an NI PXIe DMM with a Python logo overlay, as it "competes for attention with NI".
N/A
None.
> Remove image of DMM with Python logo overlay

- .github/ISSUE_TEMPLATE.md
Update the GitHub issue template - Added a header and formatting changes.
None
Verified the rendering of template in GitHub.
> Update GitHub issue template.

- CHANGELOG.md
- build/templates/_visatype.py
- generated/nidcpower/_visatype.py
- generated/nidigital/_visatype.py
- generated/nidmm/_visatype.py
- generated/nifake/_visatype.py
- generated/nifgen/_visatype.py
- generated/nimodinst/_visatype.py
- generated/niscope/_visatype.py
- generated/nise/_visatype.py
- generated/niswitch/_visatype.py
- generated/nitclk/_visatype.py
* Adds ViUInt8 as a valid type
* Fix #1095 
* Can no longer reproduce
> Add ViUInt8 as a valid VISA type

- docs/nidigital/class.rst
- generated/nidigital/session.py
- src/nidigital/metadata/attributes.py
Remove private properties from nidigital API
* Fix #1063
> Remove private attributes from nidigital metadata

- src/nidigital/system_tests/test_system_nidigital.py
Refactor Get/Set Property tests to be more representative of how users will use multi-instrument sessions.
None
Ran the tests
> Refactor Get/Set Property tests in nidigital

- src/nidigital/system_tests/test_system_nidigital.py
Add TDR system tests for nidigital
None
None
> Add TDR system tests

- build/templates/errors.rst.mako
- docs/nidcpower/errors.rst
- docs/nidigital/errors.rst
- docs/nidmm/errors.rst
- docs/nifgen/errors.rst
- docs/nimodinst/errors.rst
- docs/niscope/errors.rst
- docs/nise/errors.rst
- docs/niswitch/errors.rst
- docs/nitclk/errors.rst
* Add documentation for base exception class `Error`
* Update module to put the exceptions into <driver>.errors
* Fix #1060 
> Update exceptions documentation

- README.rst
Updates/Improvements to README:
- Add nidigital and nitclk to list of supported drivers
- Alphabetize list of supported drivers
- Fix Hyperlink
None
Visual Inspection
> Updates/Improvements to README

- CHANGELOG.md
Updated changelog for 1.1.4 release to include:
- Added support for Python 3.8
- NI Switch Executive version updated to 1.1.4 to match other drivers
None
None
> Updated changelog for 1.1.4 release

- README.rst
- docs/_static/about.inc
- docs/_static/installation.inc
- docs/_static/support.inc
Updates/Improvements to README:
- Add nidigital and nitclk to list of supported drivers
- Alphabetize list of supported drivers
- Fix Hyperlink
None
> Improvements/Fixes to README

- CHANGELOG.md
- README.rst
- generated/nidcpower/_library_singleton.py
- generated/nidigital/_library_singleton.py
- generated/nidmm/_library_singleton.py
- generated/nifake/_library_singleton.py
- generated/nifgen/_library_singleton.py
- generated/nimodinst/_library_singleton.py
- generated/niscope/_library_singleton.py
- generated/nise/_library_singleton.py
- generated/niswitch/_library_singleton.py
- generated/nitclk/_library_singleton.py
- src/nidcpower/metadata/config.py
- src/nidigital/metadata/config.py
- src/nidmm/metadata/config.py
- src/nifake/metadata/config.py
- src/nifgen/metadata/config.py
- src/nimodinst/metadata/config.py
- src/niscope/metadata/config.py
- src/nise/metadata/config.py
- src/niswitch/metadata/config.py
- src/nitclk/metadata/config.py
(unknown)
Does not pass libraries with lib/.so trimmings to ctypes find_library.
* Fix #1140 
Tested that modifying the generated file on a linux machine fixes the crash outlined in the issue.
> Fix Linux support

- tools/build_release.py
A change done during 1.1.4 release resulted in the command that uploads packages to PyPI to include nifake package. This PR fixes it.
Fix #1148
Ran `build_release` `--update` and `--upload` commands in preview mode
> Remove nifake from list of drivers to upload

- README.rst
- docs/_static/about.inc
* Add a note saying we will begin following the Python org life cycle policy
> Update README for new life cycle policy

- .gitattributes
* Be explicit that we want text files to use LF (unix style) line endings both locally and in the repo
* This will not fix things immediately, but going forward, as files are updated, I think it will help
> Fix LF in repo and locally

- CHANGELOG.md
- docs/nidigital/class.rst
- generated/nidigital/nidigital/_library.py
- generated/nidigital/nidigital/session.py
- generated/nidigital/nidigital/unit_tests/_mock_helper.py
- src/nidigital/metadata/functions_addon.py
Remove programmatic pin map creation API from nidigital.
* Fix #1124 
Visual inspection of generated files
> Remove programmatic pin map creation API from nidigital

- .travis.yml
* We have chosen to use codecov for reporting code coverage into GitHub
* Removes reporting coverage to coveralls.io
* Fix #1172 
* Inspection of reported coverage
> Do not report coverage to coveralls.io

- src/nidigital/system_tests/test_system_nidigital.py
Verify pins repeated capability is working correctly in nidigital
None
Ran nidigital system tests
> Verify pins repeated capability is working correctly in nidigital

- .gitignore
- .travis.yml
- build/templates/tox-system_tests.ini.mako
- generated/nidcpower/tox-system_tests.ini
- generated/nidigital/tox-system_tests.ini
- generated/nidmm/tox-system_tests.ini
- generated/nifake/tox-system_tests.ini
- generated/nifgen/tox-system_tests.ini
- generated/nimodinst/tox-system_tests.ini
- generated/niscope/tox-system_tests.ini
- generated/nise/tox-system_tests.ini
- generated/niswitch/tox-system_tests.ini
- generated/nitclk/tox-system_tests.ini
- tox-travis.ini
- tox.ini
* Uses more granular flags for reporting to codecov
* Makes it easier to see which results have been reported and processed
> Unique codecov flags for better tracking of processing

- generated/nifake/nifake/_library.py
- generated/nifake/nifake/enums.py
- generated/nifake/nifake/session.py
- generated/nifake/nifake/unit_tests/_mock_helper.py
- src/nifake/metadata/attributes.py
- src/nifake/metadata/config.py
- src/nifake/metadata/enums.py
- src/nifake/metadata/functions.py
Update nifake metadata from internal metadata export.
None
Visual inspection of generated files
> Update nifake metadata from internal metadata export

- build/helper/codegen_helper.py
- generated/nifake/nifake/session.py
- generated/nifake/nifake/unit_tests/test_session.py
- src/nifake/unit_tests/test_session.py
Fix the code generator for string-valued enums
* Fix #1199 
Added a unit test in nifake
> Fix the code generator for string-valued enums

- src/niscope/system_tests/test_system_niscope.py
N/A
N/A
Adds more detail and fixes inaccuracy to a comment in a system test for `niscope`
N/A
N/A
> Make comment more accurate

- build/templates/tox-system_tests.ini.mako
- generated/nidcpower/tox-system_tests.ini
- generated/nidigital/tox-system_tests.ini
- generated/nidmm/tox-system_tests.ini
- generated/nifake/tox-system_tests.ini
- generated/nifgen/tox-system_tests.ini
- generated/nimodinst/tox-system_tests.ini
- generated/niscope/tox-system_tests.ini
- generated/nise/tox-system_tests.ini
- generated/niswitch/tox-system_tests.ini
- generated/nitclk/tox-system_tests.ini
- tox.ini
N/A
Adds `--durations` switch to `pytest` invocation to print the slowest 5 tests.
None, but hopefully it's helpful when attacking #1264 
Inspected logs produced by nimi-bot.
> Log system test durations

- build/templates/tox-system_tests.ini.mako
- generated/nitclk/tox-system_tests.ini
* Fixes a merge error where the wrong condition was being used to add dependencies between environments in the system_tests tox ini file
* System
> Fix merge error

- .travis.yml
* Removes pypy3 from .travis.yml since we no longer explicitly test it.
* Unit
> Remove pypy3 from .travis.yml

- src/niscope/system_tests/test_system_niscope.py
This is a follow up to improvements suggested by @sbethur in #1265.
> Minor wording improvements in comments  for niscope system test

- src/nifgen/system_tests/test_system_nifgen.py
* Add test to verify #960 fixed
* System
> Add test for handle based waveform operations

- build/helper/documentation_helper.py
- generated/nifake/nifake/session.py
* Fix documented type for string enums to be the enum and not 'str'
* Fix #1200 
> Fix string enum docs

- build/helper/codegen_helper.py
- generated/nidcpower/nidcpower/session.py
- generated/nidigital/nidigital/session.py
- generated/nidmm/nidmm/session.py
- generated/nifake/nifake/session.py
- generated/nifgen/nifgen/session.py
- generated/niscope/niscope/session.py
- generated/nise/nise/session.py
- generated/niswitch/niswitch/session.py
* Error string for enum parameter type check was wrong (for any parameter not named 'mode')
* Fixed the code generator to properly insert the parameter name
* Visual inspection of generated `session.py` files
> Fix enum check error string

- docs/nise/class.rst
- generated/nise/nise/session.py
- src/nise/metadata/attributes.py
- src/nise/metadata/config.py
- src/nise/metadata/enums.py
- src/nise/metadata/functions.py
Fix documentation for millisecond time-based parameters
None
> nise metadata update

- docs/nidmm/class.rst
- generated/nidmm/nidmm/session.py
- src/nidmm/metadata/attributes.py
- src/nidmm/metadata/config.py
- src/nidmm/metadata/enums.py
- src/nidmm/metadata/functions.py
Fix documentation for millisecond time-based parameters
None
> nidmm metadata update

- src/nifgen/metadata/attributes.py
- src/nifgen/metadata/config.py
- src/nifgen/metadata/enums.py
- src/nifgen/metadata/functions.py
Fix documentation for millisecond time-based parameters
None
> nifgen metadata update

- docs/niswitch/class.rst
- generated/niswitch/niswitch/session.py
- src/niswitch/metadata/attributes.py
- src/niswitch/metadata/config.py
- src/niswitch/metadata/enums.py
- src/niswitch/metadata/functions.py
- Fix documentation for millisecond time-based parameters
- Remove metadata for unused methods and properties
None
> niswitch metadata update

- build/helper/__init__.py
- build/helper/documentation_helper.py
- build/helper/documentation_snippets.py
- docs/nidcpower/class.rst
- docs/nidigital/class.rst
- docs/nifgen/class.rst
- docs/niscope/class.rst
- docs/niswitch/class.rst
- generated/nidcpower/nidcpower/session.py
- generated/nidigital/nidigital/session.py
- generated/nidmm/nidmm/session.py
- generated/nifake/nifake/session.py
- generated/nifgen/nifgen/session.py
- generated/niscope/niscope/session.py
- generated/niswitch/niswitch/session.py
- generated/nitclk/nitclk/session.py
* Remove code from repeated capabilities tip since there is no way to make the code snippet work for all cases
* If we have more metadata (I.e. what repeated capability it applies to) we might be able to add this back in a more correct way
* Fix #1125 
> Remove misleading rep cap tip

- docs/nidigital/class.rst
- generated/nidigital/nidigital/session.py
- src/nidigital/metadata/functions.py
Update docstring of send_software_edge_trigger() in nidigital. Updated docstring provides guidance on what values to pass to trigger and trigger_identifier parameters.
* Fix #1193 
Visual inspection of docstring and generated html documentation
> Update docstring of send_software_edge_trigger() in nidigital

- src/nidigital/system_tests/test_system_nidigital.py
Add system tests for nidigital utility methods. Tests added:
- test_reset
- test_reset_device
- test_self_test
- test_get_error
- test_clear_error
- test_self_calibrate
None
Added and executed new system tests
> Add system tests for nidigital utility methods

- CHANGELOG.md
- docs/nidigital/class.rst
- generated/nidigital/nidigital/_library.py
- generated/nidigital/nidigital/session.py
- generated/nidigital/nidigital/unit_tests/_mock_helper.py
- src/nidigital/metadata/functions.py
Remove `clear_error()` from nidigital API
* Fix #1366 
Ran existing unit and system tests
> Remove clear_error() from nidigital API

- src/nifgen/system_tests/test_system_nifgen.py
Add TODOs for 5421 in nifgen tests
None
Unit and system tests will be run as part of gated checkin.
> Add TODOs for 5421 in nifgen tests

- build/templates/rep_caps.rst.mako
- docs/nidcpower/rep_caps.rst
- docs/nidigital/rep_caps.rst
- docs/nifgen/rep_caps.rst
- docs/niscope/rep_caps.rst
- docs/niswitch/rep_caps.rst
Fix a typo in repeated capabilities documentation
None
nimibot will run the CI
> Fix a typo in repeated capabilities documentation

- generated/nidigital/nidigital/session.py
- generated/nifgen/nifgen/session.py
- src/nidigital/templates/session.py/fancy_write_source_waveform_site_unique.py.mako
- src/nifgen/templates/session.py/create_waveform.py.mako
- src/nifgen/templates/session.py/write_waveform.py.mako
Fix typo - "unecessarilly" in code comments
None
CI will run tests
> Fix typo - "unecessarilly" in code comments

- CHANGELOG.md
- docs/nidigital/class.rst
- generated/nidigital/nidigital/_library.py
- generated/nidigital/nidigital/session.py
- generated/nidigital/nidigital/unit_tests/_mock_helper.py
- src/nidigital/metadata/functions.py
- src/nidigital/system_tests/test_system_nidigital.py
Rename parameter `time_set` to `time_set_name` in applicable time set methods
* Fix #1396 
Updated system tests if required; they will be run by nimibot
> Rename parameter `time_set` to `time_set_name` in applicable time set methods

- README.rst
- build/templates/rep_caps.rst.mako
- docs/_static/installation.inc
- docs/index.rst
- docs/nidcpower/rep_caps.rst
- docs/nidigital.rst
- docs/nidigital/rep_caps.rst
- docs/nifgen/rep_caps.rst
- docs/niscope/rep_caps.rst
- docs/niswitch/rep_caps.rst
- docs/nitclk/class.rst
- src/nitclk/templates/class.rst.mako
* Links to nidigital documentation, what there is of it
* Fixes two sphinx warnings
* One fixes formatting of code block
* Inspect documentation in web browser
> Link nidigital docs and other documentation cleanup

- src/nidigital/system_tests/test_system_nidigital.py
* Improves nidigital system test documentation of what methods are tested.
Ran the system tests on a system with nidigital 19.0.1 installed.
> Add docstrings to nidigital system tests that cover multiple methods

- build/helper/metadata_add_all.py
- build/templates/setup.py.mako
- generated/nidigital/setup.py
- src/nidigital/metadata/config.py
Add hightime as a dependency to nidigital installer. `hightime` library will be used to fix #1368.
Change contributes toward fixing #1368 
pip installed `nidigital` and verified `hightime` was installed as a dependency.
> Add hightime as a dependency to nidigital installer

- src/nidigital/system_tests/test_system_nidigital.py
- Add test for channels repeated capability
- Add test for sites repeated capability
- Add test for sites/pins chained repeated capability
None
Added new tests. CI will run the tests.
> Add nidigital system tests for channels and sites repeated capabilities

- src/nidigital/system_tests/test_system_nidigital.py
Add pattern_opcode_events and conditional_jump_triggers rep caps tests.
None
New tests added. CI will run all tests.
> Add pattern_opcode_events and conditional_jump_triggers rep caps tests

- build/helper/codegen_helper.py
- build/helper/documentation_helper.py
- generated/niscope/niscope/session.py
- src/niscope/templates/session.py/fetch_waveform.py.mako
- tools/updateReleaseInfo.py
flake8 on TravisCI got updated recently from 3.7.9 to 3.8.1. On the new version, checks for `'...'.format(...)` have become stricter.
None
CI will run tests.
> Fix flake8 violations

- CHANGELOG.md
- docs/nidcpower/class.rst
- docs/nidcpower/enums.rst
- generated/nidcpower/nidcpower/enums.py
- generated/nidcpower/nidcpower/session.py
- src/nidcpower/metadata/attributes.py
- src/nidcpower/metadata/config.py
- src/nidcpower/metadata/enums.py
- src/nidcpower/metadata/functions.py
Adds attributes released with the 20.0 NI-DCPower API
- built the component
- CI
> Updated metadata with the 20.0 release of NI-DCPower API

- CHANGELOG.md
Use module names (along with Driver Runtime names) in CHANGELOG.md
None
Visual inspection of CHANGELOG
> Use module names in CHANGELOG.md

- generated/nidigital/nidigital/session.py
- generated/niscope/niscope/session.py
- src/nidigital/templates/session.py/fancy_fetch_capture_waveform.py.mako
- src/nidigital/templates/session.py/fancy_load_specifications_levels_and_timing.py.mako
- src/niscope/templates/session.py/fancy_fetch_array_measurement.py.mako
Reorder helper methods in mako templates of fancy methods to fix session.lock issue
* Fix #1512 
Ran system tests locally
> Reorder helper methods in mako templates to fix session.lock issue

- generated/nifake/nifake/unit_tests/test_session.py
- src/nifake/unit_tests/test_session.py
- src/nimodinst/system_tests/test_system_nimodinst.py
- [x ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
~~- [ ] I've added tests applicable for this pull request.~~
Removing the remaining dependency on six in system_test
* Fix #1164 
* Unit
* System
> Removing six dependency in nifake unit_test and nimodinst system_test

- CHANGELOG.md
- README.rst
- docs/conf.py
- docs/nidcpower/class.rst
- docs/nidcpower/enums.rst
- docs/nidcpower/status.inc
- generated/nidcpower/README.rst
- generated/nidcpower/nidcpower/enums.py
- generated/nidcpower/nidcpower/session.py
- src/nidcpower/metadata/attributes.py
- src/nidcpower/metadata/config.py
- src/nidcpower/metadata/config_addon.py
- src/nidcpower/metadata/enums.py
- src/nidcpower/metadata/functions.py
* API parity with NI-DCPower 20.6.0 by adding Merged Channels and Shutdown Triggers support
* Update documentation with the latest 'Driver Version Tested Against'
n/a
System tests will be run by nimi-bot
> Python metadata changes for NI-DCPower 20.6 release

- CHANGELOG.md
- docs/nidigital/class.rst
- docs/nidigital/enums.rst
- generated/nidigital/README.rst
- generated/nidigital/nidigital/enums.py
- generated/nidigital/nidigital/session.py
- src/nidigital/metadata/attributes.py
- src/nidigital/metadata/enums.py
- src/nidigital/metadata/functions.py
- src/nidigital/metadata/functions_addon.py
Adds API reference documentation for NI-Digital.
* Fix #1527 
Built using 'tox' and manually inspected generated HTML documentation.
> Add API reference documentation for NI-Digital

- docs/nidigital/class.rst
- generated/nidigital/nidigital/session.py
- src/nidigital/metadata/functions.py
- src/nidigital/system_tests/test_system_nidigital.py
- src/nidigital/templates/session.py/fancy_fetch_history_ram_cycle_information.py.mako
Makes get_pattern_name and get_time_set_name private, and fixes up references to those functions.
* Fix #1557 
Just build.
> Make get_pattern_name and get_time_set_name private

- docs/nidigital/enums.rst
- generated/nidigital/nidigital/enums.py
- src/nidigital/metadata/enums.py
Add docs for the values of the WriteStaticPinState enumeration.
Just build.
> Add docs for WriteStaticPinState enum values

- docs/nidigital/class.rst
- generated/nidigital/nidigital/session.py
- src/nidigital/metadata/functions.py
The docs for ApplyLevelsAndTiming referred to private functions (LoadLevels and LoadTiming), so this PR replaces those references with the corresponding public function (LoadSpecificationsLevelsAndTiming).
> Replace private functions with public Fancy functions

- docs/nifgen/examples.rst
- docs/nitclk/examples.rst
Fix minor differences between recently added (#1540 and #1541) example source and code-generated example.rst files. I think code generation was not rerun after some late changes to the source.
None
CI
> Fix code-generated examples.rst files

- generated/nidcpower/nidcpower/_converters.py
- generated/nidigital/nidigital/_converters.py
- generated/nidmm/nidmm/_converters.py
- generated/nifake/nifake/_converters.py
- generated/nifake/nifake/unit_tests/test_converters.py
- generated/nifgen/nifgen/_converters.py
- generated/nimodinst/nimodinst/_converters.py
- generated/niscope/niscope/_converters.py
- generated/nise/nise/_converters.py
- generated/niswitch/niswitch/_converters.py
- generated/nitclk/nitclk/_converters.py
I failed to regenerate files after making some changes to the converters in #1576 . This PR includes those regenerated files.
> Regenerated files after changes to converter template

- build/templates/session.py.mako
- generated/nidcpower/nidcpower/session.py
System test for repeated capabilities will be added in a subsequent pull request. #1614 
Makes initiate work on channel-based sessions.
Ran dcpower system tests.
> Generate initiate in _SessionBase class instead of Session class to handle repeated capabilities

- docs/nidcpower/class.rst
- docs/nidigital/class.rst
- docs/nifgen/class.rst
- docs/niscope/class.rst
- generated/nidcpower/nidcpower/session.py
- generated/nidigital/nidigital/session.py
- generated/nidmm/nidmm/session.py
- generated/nifake/nifake/session.py
- generated/nifgen/nifgen/session.py
- generated/niscope/niscope/session.py
- generated/niswitch/niswitch/session.py
- generated/nitclk/nitclk/session.py
Change #1610 was merged in without regenerating the doc tips after the [1460a46](https://github.com/ni/nimi-python/pull/1610/commits/1460a46385dc54feb94a1b60c66c3c4e506d16da) commit.
Performed internal builds and inspected generated code, while verifying that all automated tests pass.
> Update generated doc tips after wording change

- docs/nidcpower/class.rst
- generated/nidcpower/nidcpower/session.py
- src/nidcpower/metadata/functions_addon.py
- src/nidcpower/system_tests/test_system_nidcpower.py
- ~~[ ] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~~
Adds support for repeated capabilities to create_advanced_sequence method. A previous attempt to add this support was incomplete.
Verified calls to create_advanced_sequence using repeated capabilities succeed without error. New system tests will be added to test each method that now supports repeated capabilities in a different PR #1624.
> Correct implementation of create_advanced_sequence to support repeated capabilities

- src/nidcpower/system_tests/test_system_nidcpower.py
Fix flake8 error introduced in #1624
> Fix style error

- docs/_static/nidcpower_usage.inc
- generated/nidcpower/README.rst
Updates the nidcpower sample code used in the readme to match the nidcpower_measure_record.py example updated [here](https://github.com/ni/nimi-python/pull/1600).
> Update nidcpower sample code from modified example

- CHANGELOG.md
- docs/nidcpower/class.rst
- generated/nidcpower/nidcpower/_library.py
- generated/nidcpower/nidcpower/session.py
- generated/nidcpower/nidcpower/unit_tests/_mock_helper.py
- src/nidcpower/metadata/functions.py
- src/nidcpower/system_tests/test_system_nidcpower.py
Add support for commit step feature by implementing create_advanced_sequence_commit_step
- Fix #1636
Modified system tests pass.
> Add create_advanced_sequence_commit_step to NI-DCPower

- docs/nidigital/class.rst
- generated/nidigital/nidigital/session.py
- src/nidigital/metadata/functions.py
Fixes stale documentation of nidigital.get_channel_names()
* Fix #1587
Generated new documentation from updated metadata
> Fix nidigital.get_channel_names documentation

- CHANGELOG.md
Update the CHANGELOG entry for nidcpower Independent Channels feature to improve readability and its usefulness to client devs. I used the text from NI-DCPower 20.6 [README](https://www.ni.com/pdf/manuals/375374ab.html#New).
None
PR build
> Update the CHANGELOG entry for nidcpower Independent Channels feature

- CONTRIBUTING.md
The examples are zipped as part of codegen. This requires the `zip` tool to be installed.
- Fix #1657
None
> Update Contributing guide to install `zip`

- CHANGELOG.md
Independent Channel functionality was added to `nidcpower` Python module in 1.4.0, which has certain requirements relating to driver runtime compatibility and session constructor. The CHANGELOG is updated to better clarify these requirements.
None
PR build
> Update CHANGELOG for nidcpower 1.4.0

- CONTRIBUTING.md
Update the Contributing guide to make it clear that the latest version of Python supported by nimi-python is what contributors should be using for building nimi-python locally.
N/a
None
> Update Python setup in Contributing guide

- CHANGELOG.md
- docs/nidcpower/class.rst
- generated/nidcpower/nidcpower/session.py
- src/nidcpower/metadata/attributes_addon.py
- Enable `lcr_automatic_level_control` and `lcr_dc_bias_automatic_level_control`
- Update CHANGELOG
Built locally successfully.
> NI-DCPower: Enable automatic level control attrs

- docs/nidcpower/class.rst
- generated/nidcpower/nidcpower/session.py
- src/nidcpower/metadata/attributes.py
- src/nidcpower/metadata/attributes_addon.py
- src/nidcpower/metadata/config.py
- src/nidcpower/metadata/enums.py
- src/nidcpower/metadata/functions.py
- Update docs for attributes
- Disable new attributes
N/A
> NI-DCPower: Update metadata (docs) to 22.5.0d65

- .github/workflows/github_actions_aws_rhel_python64.yml
- .github/workflows/github_actions_aws_windows_python32.yml
- .github/workflows/github_actions_aws_windows_python64.yml
~!- [ ] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~
Changing the string reported in GitHub Workflow UI from `nimibot_win_64 / system_tests_win64 (niscope) (pull_request)` to `nimibot_win_64 / system_test (niscope) (pull_request)`
* Partially fixing #1768 
PR build
> Remove redundant text in the GitHub Workflow report UI

- CONTRIBUTING.md
Update CONTRIBUTING.md is to clarify where Python needs to be installed on Windows platform - in Windows Subsystem for Linux.
* Fix #1775
None
> Update CONTRIBUTING.md is to clarify where Python needs to be installed

- .gitignore
#1702 added unit tests for `nidcpower`, whose execution generates nidcpowerunittest.xml, which contains the code coverage data. This PR adds the aforementioned XML file to `.gitignore`.
None
PR build
> Add nidcpowerunittest.xml to .gitignore list

- generated/nidmm/nidmm/session.py
- src/nidmm/metadata/attributes.py
- src/nidmm/metadata/config.py
- src/nidmm/metadata/enums.py
- src/nidmm/metadata/functions.py
- Update nidmm metadata to align with NI-DMM Runtime 2022 Q3
- The metadata update resulted in a minor change to the docstring of a public-facing API
None
PR build
> Update nidmm metadata to align with NI-DMM Runtime 2022 Q3

- src/nifgen/metadata/attributes.py
- src/nifgen/metadata/config.py
- src/nifgen/metadata/enums.py
- src/nifgen/metadata/functions.py
- src/nimodinst/metadata/attributes.py
- src/nimodinst/metadata/config.py
- src/nimodinst/metadata/enums.py
- src/nimodinst/metadata/functions.py
- src/niscope/metadata/attributes.py
- src/niscope/metadata/config.py
- src/niscope/metadata/enums.py
- src/niscope/metadata/functions.py
- src/nise/metadata/attributes.py
- src/nise/metadata/config.py
- src/nise/metadata/enums.py
- src/nise/metadata/functions.py
- src/niswitch/metadata/attributes.py
- src/niswitch/metadata/config.py
- src/niswitch/metadata/enums.py
- src/niswitch/metadata/functions.py
- src/nitclk/metadata/attributes.py
- src/nitclk/metadata/config.py
- src/nitclk/metadata/enums.py
- src/nitclk/metadata/functions.py
- Update metadata to match the latest driver Runtimes
- All the metadata changes had already been done in nimi-python earlier. This PR is use the metadata from official internal exports
- Zero changes in generated files
- Fix #1789
PR build
> Update metadata to match the latest driver Runtimes

- .github/CODEOWNERS
Replace myself with @ni-jfitzger as a code owner for nimi-python
None
None
> Replace myself with Jay as a code owner

- src/niscope/system_tests/test_system_niscope.py
Moves the NI-SCOPE system tests into a class, in preparation for #1845 
None
None
> Put NI-SCOPE system tests into a class

- NILICENSE
- README.rst
- docs/_static/license.inc
- generated/nidcpower/README.rst
- generated/nidigital/README.rst
- generated/nidmm/README.rst
- generated/nifgen/README.rst
- generated/nimodinst/README.rst
- generated/niscope/README.rst
- generated/nise/README.rst
- generated/niswitch/README.rst
- generated/nitclk/README.rst
-~~ [ ] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~~
-~~ [ ] I've added tests applicable for this pull request~~
Adding legal notices for the gRPC features per request from NI Legal.
> Adding license info for gRPC

- CHANGELOG.md
- docs/nidigital/examples.rst
- src/nidigital/examples/burst_with_start_trigger/nidigital_burst_with_start_trigger_grpc.py
N/A
Add gRPC Examples for NI-Digital. These drivers have their protos and system tests added and so we are adding an example for each to show the use of the gRPC sessions. These examples are based off of existing examples so that users can see side-by-side the difference in setting up session (e.g. how easy it is).
Ran local server and after installing build artifacts successfully ran the gRPC examples.
> Add gRPC Example for NI-Digital

- build/templates/tox-system_tests.ini.mako
- generated/nidcpower/tox-system_tests.ini
- generated/nidigital/tox-system_tests.ini
- generated/nidmm/tox-system_tests.ini
- generated/nifake/tox-system_tests.ini
- generated/nifgen/tox-system_tests.ini
- generated/nimodinst/tox-system_tests.ini
- generated/niscope/tox-system_tests.ini
- generated/nise/tox-system_tests.ini
- generated/niswitch/tox-system_tests.ini
- generated/nitclk/tox-system_tests.ini
- tox-travis.ini
- tox.ini
Eliminate use of "py" test, build_test dependency.
- [py.test has been replaced with pytest](https://pypi.org/project/py/)
- [py has a known security vulnerability](https://github.com/advisories/GHSA-w596-4wvx-j9j6)
None
None
> Eliminate "py" dependency

- src/nise/metadata/attributes.py
- src/nise/metadata/config.py
- src/nise/metadata/enums.py
- src/nise/metadata/functions.py
- nise metadata is updated from the latest final export or later
None
None
> Update nise metadata for nimi-python 1.4.4 release

- src/nifake/metadata/attributes.py
- src/nifake/metadata/config.py
- src/nifake/metadata/enums.py
- src/nifake/metadata/functions.py
- src/nifake/metadata/functions_addon.py
nifake metadata is updated to remove an override in src/nifake/metadata/functions_addon.py
None
None
> Update nifake metadata to remove override

- src/nidigital/metadata/attributes.py
- src/nidigital/metadata/config.py
- src/nidigital/metadata/enums.py
- src/nidigital/metadata/functions.py
- src/nidigital/metadata/nidigitalpattern.proto
- nidigital metadata is updated from the latest final export or later
- nidigitalpattern.proto is updated to the latest available in https://github.com/ni/grpc-device
None
None
> Update nidigital metadata for nimi-python 1.4.4 release

- src/nimodinst/metadata/attributes.py
- src/nimodinst/metadata/config.py
- src/nimodinst/metadata/enums.py
- src/nimodinst/metadata/functions.py
- nimodinst metadata is updated from the latest final export or later
None
None
> Update nimodinst metadata for nimi-python 1.4.4 release

- src/niswitch/metadata/attributes.py
- src/niswitch/metadata/config.py
- src/niswitch/metadata/enums.py
- src/niswitch/metadata/functions.py
- src/niswitch/metadata/niswitch.proto
- niswitch metadata is updated from the latest final export or later
- niswitch.proto is updated to the latest available in https://github.com/ni/grpc-device
None
None
> Update niswitch metadata for nimi-python 1.4.4 release

- src/nidmm/metadata/attributes.py
- src/nidmm/metadata/config.py
- src/nidmm/metadata/enums.py
- src/nidmm/metadata/functions.py
- src/nidmm/metadata/nidmm.proto
- nidmm metadata is updated from the latest final export or later
- nidmm.proto is updated to the latest available in https://github.com/ni/grpc-device
None
None
> Update nidmm metadata for nimi-python 1.4.4 release

- src/nitclk/metadata/attributes.py
- src/nitclk/metadata/config.py
- src/nitclk/metadata/enums.py
- src/nitclk/metadata/functions.py
- nitclk metadata is updated from the latest final export or later
None
None
> Update nitclk metadata for nimi-python 1.4.4 release

- docs/nifgen/enums.rst
- generated/nifgen/nifgen/enums.py
- src/nifgen/metadata/attributes.py
- src/nifgen/metadata/config.py
- src/nifgen/metadata/enums.py
- src/nifgen/metadata/functions.py
- src/nifgen/metadata/nifgen.proto
- nifgen metadata is updated from the latest final export or later
- nifgen.proto is updated to the latest available in https://github.com/ni/grpc-device
None
None
> Update nifgen metadata for nimi-python 1.4.4 release

- build/templates/tox-system_tests.ini.mako
- generated/nidigital/tox-system_tests.ini
- generated/nifake/tox-system_tests.ini
- generated/nifgen/tox-system_tests.ini
- generated/niscope/tox-system_tests.ini
- generated/nitclk/tox-system_tests.ini
Remove an unnecessary dependency from tox-system_tests.ini.
None
PR Checks succeed, so we're still building the wheel_dep successfully for our system tests.
> Remove packaging dep from tox-system_tests.ini

- build/generate_template.py
- build/helper/documentation_helper.py
- tools/simple_mako.py
I noticed some more code that was an artifact of when we supported both Python 2 and Python 3. This deletes it.
None
PR Checks
> Delete more code used for supporting Python 2

- src/shared/system_test_utilities.py
https://github.com/ni/grpc-device/pull/989 altered the output of grpc_device_server.exe and caused our internal nimi-python test suites to fail all gRPC tests. I discussed this with ni/grpc-device owners / contributors and it was determined there is no contract for the output to follow a certain format.
A copy of https://github.com/ni/nidaqmx-python/pull/450, this change updates GrpcServerProcess to keep reading the server output until the server port is parsed.
Note: this won't fix our internal ats failures until we release.
Alternatives:
I tried reading the port from the server json config instead, but it caused the …
> Read grpc_device_server port from any line of server output when running system_tests

- .github/workflows/github_actions_aws_rhel_python64.yml
- .github/workflows/github_actions_aws_windows_python32.yml
- .github/workflows/github_actions_aws_windows_python64.yml
Update the workflow action ymls to run nimodinst system tests on Linux. We've had Linux support for NI-ModInst for at least a year or two, now.
While I'm in there, update workflow yml arrays to be consistent in their style.
* Fix #2016
PR Checks
> Run nimodinst system tests on Linux

- tools/coverage_system_tests.rc
- tools/coverage_unit_tests.rc
* We're currently measuring test coverage for files we don't care about, throwing off our code coverage metrics.
* The reasons for files being omitted from our coverage metrics are not stated
* System test coverage is not reported for our hand-coded fancy functions in session.py
This change addresses all 3 issues.
* Fix #2015
* Ran the unit tests locally and observed the reported coverage.
* PR Checks
Currently reported code coverage for master branch: 64%
Reported Code Coverage for this PR: 90.87%
https://app.codecov.io/github/ni/nimi-python/tree/update-coverage-rcs/generated
> Update coverage rc files
