ni/nimi-python

src/nidmm/system_tests/test_system_nidmm.py
[x ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/<reponame>/blob/master/CONTRIBUTING.md).
Fixes DMMSystemTests to work with simulated devices.
This enables system tests on all device types.
Ran and saw passing and skipped tests.
=> Fixing DMM System Tests for Simulated Devices

build/helper.py, build/templates/ctypes_library.py.mako, generated/nidmm/ctypes_library.py, generated/nimodinst/ctypes_library.py
* Fixes #92 
* Create and acquire lock before referencing or updating cfunc information
* List functions sorted by name
* This will prevent spurious changes because Python iterated over objects in a different order
* Fix issue
=> Create and acquire lock before referencing or updating cfunc information

docs/_static/theme_overrides.css, docs/conf.py
* Wide tables don't word wrap correctly
* Add static file with fixed css
* Solution from [rackerlags](http://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html)
* readthedocs documentation looks better
* Verify on rtd
=> Workaround ReadTheDocs table width bug

src/nidmm/system_tests/test_system_nidmm.py
Adds a test case for the test test_readonly_attribute, which tests that appropriate exception is thrown when trying to write into a read-only attribute.
To increase coverage of tests
Tested locally on a machine with DMM and test passes
=> Added test for writeonly attribute

build/helper.py, docs/nidmm/functions.rst, docs/nimodinst/functions.rst
* Fix parameter type formatting on read the docs
* Need a space after rst instruction
* Fix documentation
Travis
=> Fix formatting in function parameters on readthedocs

src/nidmm/system_tests/test_system_nidmm.py
(https://github.com/ni/<reponame>/blob/master/CONTRIBUTING.md).
Added system test to check option string behavior while initializing the device.
1.  test_init_with_Valid_optionstring
2.  test_init_with_invalid_optionstring
Modified test test_method_with_enum_output_type_method to have enum return type
System test coverage for optionstring check
Passed on local machine
=> Added more nidmm system tests and fixed test related to enum return type

build/rules.mak, generated/command_history.bat, generated/command_history.sh
Use file $(LOG_DIR)/test_results.log to signal rest of build process
that tests executed successfully. This file is touched after unit tests
run.
Fixes issue #136 
Improves command line output during build
Fixes an issue, improves incremental builds.
Locally verified that if unit tests fail, then you make again, they run.
Locally verified that on incremental builds unit tests don't run unless needed.
=> Fix: Unit tests run every time you make, even if nothing changed #136

build/templates/attributes.rst.mako, build/templates/enums.rst.mako, build/templates/functions.rst.mako, build/templates/session.rst.mako, docs/nidmm.rst, docs/nidmm/attributes.rst, docs/nidmm/enums.rst, docs/nidmm/functions.rst, docs/nidmm/session.rst, docs/nifake/attributes.rst, docs/nifake/enums.rst, docs/nifake/functions.rst, docs/nifake/session.rst, docs/nimodinst.rst, docs/nimodinst/attributes.rst, docs/nimodinst/functions.rst, docs/nimodinst/session.rst
* Fixes #158 
* Change Page headers (which become section names on the index) to be more Pythonic. I.e.:
* NI-DMM Functions --> nidmm.Session methods
* NI-DMM Attributes --> nidmm.Session properties
* NI-DMM Enums --> nidmm enums
* NI-DMM Session --> nidmm.Session
* Documentation improvement
* Travis
=> Page headers and section name more pythonic

.gitignore, build/defines.mak, build/rules.mak, generated/nidmm/setup.py, generated/nimodinst/setup.py
* Fixes #167 
* Create file in LOG_DIR to track when a build step has completed successfully
* Create variables in defines.mak for all the tracking files
* All targets except test & html now use this mechanism
* sphinx already does a good job of not rebuilding when not required
* `make test` should always run tests
* Developer effenciency
* Travis
=> Do a better job of minimizing building

build/rules.mak
* Fixes #176 
* Only add .py files to be copied when gathering files for system tests and examples
* Improve build
* Travis
=> Only look for .py files when getting system tests and examples

.travis.yml, build/Makefile, build/defines.mak, build/rules.mak, build/tools.mak, generated/nidmm/setup.py, generated/nifake/setup.py, generated/nimodinst/setup.py, src/nimodinst/nimodinst.mak, tox.ini
* Uses tox for pytest, flake8 & sphinx
* Now these dependencies are no longer required to be installed on the build machine
* All three are ran as part of the test target
* Runs after all drivers are complete
* Only unit test nifake
* Run flake8 on all drivers at the same time
* Fix rerunning tests when not required
* Use tracking file similar to other things
* Item builds that can change testing results trigger the tests to be ran by deleting the tracking file if it exists
* Moves common functions into tools.mak
* Allows use in multiple places without multiple defines
* There was already a discrepancy between two versions of one of them
* Improve overall build times
* Travis
=> Change how tox is used

.gitignore, tox.ini
* Fixes #221 
* Run ModInst unit tests
* ModInst uses own session class, so some of NI-FAKE unit testing doesn't apply
* Add to code coverage report
* Percentage is going down because of this
* Need to unit test ModInst separately
* Travis
=> Unit test ModInst again

.gitignore, tox.ini
Moves the HTML that the coverage tool generates into bin/htmlcov, rather than the default htmlcov/
* make clean now get rids of this potentially stale directory
* removes need for developer to remember that htmlcov/ is special (we already learned bin/ is special)
* Simplifies .gitignore
Locally ran tox and HTML was created in desired location.
make clean still works.
=> Move generation of html for coverage tool into bin/ folder.

build/helper.py, build/metadata_utilities.py, build/templates/library.py.mako, build/templates/mock_helper.py.mako, build/templates/session.py.mako, build/templates/session.rst.mako, docs/nidmm/functions.rst, docs/niswitch/functions.rst, src/nidmm/metadata/__init__.py, src/nidmm/metadata/config.py, src/nifake/metadata/__init__.py, src/nifake/metadata/config.py, src/nimodinst/metadata/__init__.py, src/nimodinst/metadata/config.py, src/nimodinst/templates/session.py.mako, src/niswitch/metadata/__init__.py, src/niswitch/metadata/config.py, tox.ini
* Take the different flavors of get parameter list snippet and consolidate into single function
* Pick which flavor using enum
``` python
class ParamListType(Enum):
'''Type of parameter list to return'''
API_METHOD = 1
'''Used for methods param list for the public API'''
IMPL_METHOD = 2
'''Used for methods param list for implementation'''
DISPLAY_METHOD = 3
'''Used for methods param list for display (rst)'''
LIBRARY_METHOD = 4
'''Used for methods param list when calling library'''
LIBRARY_CALL = 5
'''Used for methods param list when calling into the DLL'''
LIBRARY_CALL_TYPES = 6
'''Used for methods param list types when calling into the DLL'''
```
* Add extra types to metadata
* Add session name to config metadata
* Each flavor has …
=> Consolidate different functions into single get_params()

build/templates/errors.py.mako, generated/nidmm/errors.py, generated/nifake/errors.py, generated/nifake/tests/test_session.py, generated/nimodinst/errors.py, generated/niswitch/errors.py, src/nifake/tests/test_session.py
[ x] This contribution adheres to [CONTRIBUTING.md]
Fixes #312 
Removes redundant warnings for error handling functions.
Adds additional tests to cover if we get errors in both _get_error and _get_error_message
Built and tested system tests
=> Don't log a warning when the driver cannot get error description

CHANGELOG.md, build/templates/attributes.py.mako, build/templates/session.py.mako, generated/nidmm/attributes.py, generated/nidmm/session.py, generated/nifake/attributes.py, generated/nifake/enums.py, generated/nifake/session.py, generated/nifake/tests/test_session.py, generated/nimodinst/attributes.py, generated/niswitch/attributes.py, generated/niswitch/session.py, src/nifake/metadata/attributes.py, src/nifake/metadata/enums.py, src/nifake/tests/test_session.py
* Fixes #330 
* Changes to `AttributeEnum()`
* Now inherits from `object` instead of `AttributeViInt32`
* Class of appropriate underlying type is passed in to the constructor
``` python
resolution_digits = attributes.AttributeEnum(attributes.AttributeViReal64, enums.DigitsResolution, 1250003)
```
* Instantiates the underlying type and uses that for actual get/set
* Enum type is still used to return the correct type and to do type checking on the incoming type
* Tests added to get/set float based enum
* Fixes issue
* Travis
* System tests
=> Support enums that aren't ViInt32

build/templates/examples.rst.mako
* We shouldn't add as an example in documentation a file that doesn't end in '.py'. Some OSes may add files in there for different reasons (macOS for instance created .DSStore files)
* Better documentation
* Manually added non .py file and example.rst didn't change
=> Only add examples if they end in .py

docs/niswitch/examples.rst, generated/nifake/tests/test_session.py, src/nifake/tests/test_session.py
* Groups all related tests
* Improves logical ordering of tests
* Makes it more obvious what tests are missing
* Adds lots of annotations about tests yet to be written (not comprehensive)
* Improves consistency of names
Before:
```
* test_init_with_options
* test_close
* test_session_context_manager
* test_get_error_description_get_error
* test_simple_function
* test_method_with_error
* test_method_with_warning
* test_ivi_dance_with_error
* test_get_string_attribute_private
* test_get_string_attribute
* test_get_a_number
* test_invalid_attribute_value
* test_error_on_init
* test_invalid_method_call_not_enough_parameters
* test_invalid_method_call_wrong_type
* test_library_singleton
* test_one_input_function
* test_two_input_function
* …
```
=> Reordered and renamed tests in test_session.py

build/templates/session.py.mako, generated/nidmm/session.py, generated/nifake/session.py, generated/nifake/tests/test_session.py, generated/niswitch/session.py, src/nifake/tests/test_session.py, src/niswitch/examples/niswitch_get_device_info.py
Removes context manager from _RepeatedCapability class. This was judged to be an abuse of Python context managers.
Puts our API closer to where we want it to be.
tox
=> Fix #343: _RepeatedCapability should not be a context manager

build/helper/codegen_helper.py, build/helper/metadata_add_all.py, build/templates/session.py.mako, generated/nidmm/session.py, generated/nifake/session.py, generated/nifake/tests/test_session.py, generated/nimodinst/session.py, generated/nimodinst/tests/test_modinst.py, generated/niswitch/session.py, src/nifake/tests/test_session.py, src/nimodinst/templates/session.py.mako, src/nimodinst/tests/test_modinst.py
* Fix #256 
* Adds underscore prefix to private members for consistency with PEP8 coding conventions
* Shrinks the "surface area" of API by signaling clients not to use those.
* Renames 'session_name' to 'session_handle_parameter_name' in ParamListType, consistent with config.py metadata.
* Renames 'name_to_use': 'library_call_name' in ParamListType to 'library_call_snippet', as it contains code not just a name.
* Fix a handful of locations where "vi" was still hardcoded, rather than use ${config['session_handle_parameter_name']}
* Bug fixes
* Naming improvements
tox
=> Add underscore prefix to all private members

generated/nifake/library.py, generated/nifake/session.py, generated/nifake/tests/mock_helper.py, generated/nifake/tests/test_session.py, src/nifake/metadata/functions.py, src/nifake/metadata/functions_addon.py, src/nifake/tests/test_session.py
[x ] This contribution adheres to [CONTRIBUTING.md]
Add unit test and niFAKE function that has enums that are default
Increases build coverage. Handling default values of type enum was added recently to the codegenerator but not tested in NI-FAKE.
Built and ran unit tests and flake8
=> Add unit test and NI-FAKE function that has enum parameter with default value

build/helper/documentation_helper.py
When our code generator processes documentation strings from metadata,
it finds/replaces links to functions. If those links have typos
(typically but not always incorrect capitalization) it would normally
die with a KeyError. Now it prints a warning. This allows us to get a full list of these errors so we can fix in origin.
Makes it easier to first onboard drivers with issues in its source metadata. In my case I ran into a lot of problems with NI-DCPower.
I've been using this change successfully.
=> Skip typos / bogus function names when converting to doc links

CHANGELOG.md, build/templates/ctypes_types.py, build/templates/python_types.py, generated/nidmm/ctypes_types.py, generated/nidmm/python_types.py, generated/nifake/ctypes_types.py, generated/nifake/library.py, generated/nifake/python_types.py, generated/nifake/session.py, generated/nifake/tests/mock_helper.py, generated/nifake/tests/test_session.py, generated/nimodinst/ctypes_types.py, generated/nimodinst/python_types.py, generated/niswitch/ctypes_types.py, generated/niswitch/python_types.py, src/nifake/metadata/functions.py, src/nifake/tests/test_session.py
Adds support for ViInt64 type. This is needed by APIs that will be added (example NI-DCPower).
Added a test function and a unit test to NI-FAKE.
=> Add ViInt64 to code-generator

build/templates/session.py.mako, src/nidmm/metadata/config.py, src/nifake/metadata/config.py, src/niswitch/metadata/config.py
* Use C name to lookup context manager actions method names to use
* Rename keys to add '_function' to be clear that it is the function name
* Fix #350 
* Travis & System tests
=> Use the actual function name and then lookup python name

build/helper/metadata_add_all.py
* Add helper functions for dictionary and list comparison
* Determining what was different in two large dictionaries is tedious
* This breaks the comparison down to smaller pieces so the reporting can be more helpful
N/A
* Travis
* System tests
=> Add helper functions for dicts/lists comparison

generated/nifake/tests/test_session.py, src/nifake/tests/test_session.py
Split pull request #369 to run tests which passes on both python versions.(python27 and python36)
tox passed on both python-27 and python-36
=> Creating new PR for tests passing on python-27 and python-36 from PR 369

build/defines.mak, build/helper/codegen_helper.py, build/helper/metadata_add_all.py, build/templates/library.py.mako, build/templates/mock_helper.py.mako, build/templates/session.py.mako, build/templates/visatype.py, generated/nidcpower/library.py, generated/nidcpower/session.py, generated/nidcpower/tests/mock_helper.py, generated/nidcpower/visatype.py, generated/nidmm/library.py, generated/nidmm/session.py, generated/nidmm/tests/mock_helper.py, generated/nidmm/visatype.py, generated/nifake/library.py, generated/nifake/session.py, generated/nifake/tests/mock_helper.py, generated/nifake/visatype.py, generated/nimodinst/library.py, generated/nimodinst/session.py, generated/nimodinst/tests/mock_helper.py, generated/nimodinst/tests/test_modinst.py, generated/nimodinst/visatype.py, generated/niswitch/library.py, generated/niswitch/session.py, generated/niswitch/tests/mock_helper.py, generated/niswitch/visatype.py, src/nimodinst/templates/session.py.mako, src/nimodinst/tests/test_modinst.py
Renames ctypes_types.py -> visatype.py
The logic behind this is that visatype.py contains types with names identical to those in visatype.h that ships with VISA and is used by Modular Instruments drivers. They are ctypes types and are binary compatible too.
This should make the code simpler to follow, is the intention.
N/A
tox
=>  Rename ctypes_types.py to visatype.py

src/niswitch/system_tests/test_system_niswitch.py
[x ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/<reponame>/blob/master/CONTRIBUTING.md).
Adds system test to cover error_message which was previously not generated
Ran system tests
=> Adding additional system test to cover error_message

build/helper/codegen_helper.py, build/templates/library.py.mako, build/templates/visatype.py, generated/nidcpower/library.py, generated/nidcpower/visatype.py, generated/nidmm/library.py, generated/nidmm/session.py, generated/nidmm/visatype.py, generated/nifake/library.py, generated/nifake/session.py, generated/nifake/visatype.py, generated/nimodinst/library.py, generated/nimodinst/visatype.py, generated/niswitch/library.py, generated/niswitch/visatype.py
* Make visatypes "typedefs" rather than subclasses
* This is done as setting them equal to the ctype instead of a class that inherits from ctypes
N/A
* Travis
* System tests
=> Make visatypes "typedefs" rather than subclasses

build/helper/metadata_add_all.py
* Code generator assumed that a variable type that had [] in it was always ViChar
* Don't make that assumption any more and break the check into two parts
* Be more pythonic when determining if metadata exists
* Fix #434 
* Travis
* System tests
=> Fix library call

CHANGELOG.md, build/templates/enums.rst.mako, docs/nidcpower/enums.rst, docs/nidmm/enums.rst, docs/niswitch/enums.rst
* Make the enum value name in documentation fully qualified
* This allows easy copy/paste 
* Fix #395 
* Travis
* System tests
* Visual inspection of generated documentation
=> Make enum value names fully qualified

build/helper/documentation_helper.py
* Makes string comparison in unit test pass when the strings differ only by trailing whitespace (RST doesn't care)
* Makes sting comparison in unit test pass when there are different blank strings (RST doesn't care)
* Improves errors in the assertions.
* Fix #442 
tox
Made a test fail, looked at output.
=> Improve RST unit tests

build/helper/__init__.py, build/helper/codegen_helper.py, build/helper/metadata_filters.py, build/templates/session.py.mako, generated/nifake/session.py, generated/nifake/tests/test_session.py, src/nifake/metadata/functions_addon.py, src/nifake/tests/test_session.py
* Add 'len' mechanism for buffer length code generation
* metadata looks like
```
'ArrayInputFunction': { 'parameters': { 2: { 'size': {'mechanism':'len', 'value':'numberOfElements'}, }, }, },
```
* This mechanism will set the size parameter to the length of the buffer parameter
* Created new filter function
* Moved common filter code into shared function
* Changed 'skip_ivi_dance_size_parameter' to 'skip_size_parameter' in `ParameterUsageOptions`
* More generic
* Fix #440 
* Travis
* System tests
=> Add 'len' mechanism for buffers 

generated/nidcpower/session.py, src/nidcpower/metadata/functions_addon.py
Makes nidcpower.Session.fetch_multiple() work with count > 1. Without this memory gets corrupted.
N/A
Tested with examples on my end. Examples will be posted in a separate PR.
=> Add buffer_info for niDCPower_FetchMultiple() parameters

src/nidcpower/system_tests/test_system_nidcpower.py
More syste tests for nidcpower.
- test_config_aperture_time
- test_fetch_multiple
- test_measure_multiple
- test_measure
- test_query_max_current_limit
- test_query_max_voltage_level
- test_query_min_current_limit
- test_query_output_state
Adding all of them as commented tests. since it requires channels . Will enable them once after PR#436 merged and #444 fixed
=> Adding system tests for nidcpower

generated/nifake/tests/test_session.py, src/nifake/tests/test_session.py
[ x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
This organizes unit tests better
- Puts all tests of certain type in category (attribute tests in attributes section, etc)
- Moves attributes tests to follow get / set pattern
- Errors for each section go at bottom of each section
- Groups todos and commented code in correct locations within categories
- Updated names for consistency
NA
Ran unit tests and flake 8
Before - 
bin/nifake/nifake/tests/test_session.py::TestSession::test_init_with_options_and_close PASSED
bin/nifake/nifake/tests/test_session.py::TestSession::test_init_with_options_nondefault_and_close PASSED
bin/nifake/nifake/tests/test_session.py::TestSession::test_error_on_init PASSED …
=> Moving todos and functions to relevant category in unit test file.

build/templates/session.py.mako, generated/nidcpower/session.py, generated/nidmm/session.py, generated/nifake/session.py, generated/nifake/tests/test_session.py, generated/niswitch/session.py, src/nifake/tests/test_session.py
* Move the error handling methods to _SessionBase
* This way the repeated capabilities object can properly handle errors
* Fix #456 
* Travis
* System test
* Hand testing
=> Move error handling methods to _SessionBase

build/helper/__init__.py, build/helper/codegen_helper.py, build/helper/documentation_helper.py, build/helper/metadata_filters.py, build/helper/parameter_usage_options.py, build/templates/mock_helper.py.mako, build/templates/session.py.mako, src/nimodinst/templates/session.py.mako
* Consolidate filter functions to use filter_parameters with new options
* Break _parameterUsageOptions into two parts
1. filtering
1. snippets
* Maintain wrapper functions for finding len parameter and ivi-damce parameter
* Returns None if not found
* Ensure no more than one found
* Returns parameter dictionary and not list of parameter dictionaries
* Travis
* System test
=> Consolidate filter functions

build/helper/metadata_add_all.py, docs/nidcpower/functions.rst, docs/nidmm/functions.rst, docs/niswitch/functions.rst, generated/nidcpower/session.py, generated/nidmm/session.py, generated/niswitch/session.py
~~[] I've added any unit tests that are applicable for this pull request~~
There is a step in code generation after we read API metadata in which we add a lot of calculated metadata that makes later code generation simpler. We've been adding this metadata to all functions. This change makes it so that we only calculate additional metadata for functions that we actually include in the Python APIs.
This exposes small internal bugs. For example, when generating documentation, we would generate broken links to functions that don't actually exist in the Python API. After …
=> Restrict add all function metadata

CHANGELOG.md, docs/nidmm/enums.rst, generated/nidmm/enums.py, src/nidmm/metadata/enums.py
* Remove incorrect leading underscore from enum values
* Cause was leading space in source
* Process changes all spaces into underscore in names
* Extractor now strips whitespace from names before replacing spaces
* Fix #324 
* System
* Unit
=> Remove incorrect leading underscore from enum values

src/nifake/tests/test_session.py
Changing the test to assert called with Int64 instead of Int32
[X ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
(https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
[X ] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.
(https://github.com/ni/nimi-python/blob/master/CHANGELOG.md).
[X ] I've added any unit tests that are applicable for this pull request
Fixes Issue #532 of test_get_attribute_int64 failing
Fix #532 
Unit test passed
=> Fixes Issue #532 of test_get_attribute_int64 failing

generated/nifake/tests/test_session.py, src/nifake/tests/test_session.py, src/nimodinst/system_tests/test_system_nimodinst.py, tox.ini
[x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
~~[] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~~
[x] I've added any unit tests that are applicable for this pull request
Use six module to check text type in our tests.
* Fix #565 
Ran all tests
=> Fix tests so they check for the right text type regardless of Python version

src/niscope/system_tests/test_system_niscope.py
[X] I've added any unit tests that are applicable for this pull request
Simulate a 5164 digitizer device. This is not only faster, but also works around an NI-SCOPE bug with DAQmx-based digitizers.
* Fix #576 
Ran `tox -e system_tests` locally and it works.
=> Workaround NI-SCOPE simulation bug

src/nifgen/system_tests/test_system_nifgen.py
Adding 8 more system tests for nifgen
- test_allocate_waveform
- test_clear_waveform_memory
- test_query_arb_seq_capabilities
- test_arb_seq
- test_arb_script
- test_reset
- test_reset_device
- test_reset_with_default
* Partial work towards #484 
systemtests, tox
=> Adding more nifgen systemtests

README.rst, tox.ini
* Add pkg testing to default environments
* Print python version and bitness at the beginning of each environment
* Be more specific about which version of python to use for each environment
* As soon as you specify the basepython for one environment, all need to be specified
* This will allow us to not need to support python 2.7 in the code generator
* Allow specifying python version for system_tests
* This along with a change to the commands on nimi-bot will fix #564 
* Unit
* System
=> tox.ini improvements

generated/nifgen/library.py, generated/nifgen/session.py, generated/nifgen/unit_tests/mock_helper.py, src/nifgen/metadata/functions_addon.py
Removing GetAttributeViInt64, SetAttributeViInt64 from nifgen since there is no ViInt64 attributes.
Submission of this PR will be based on the decision for issue #608 
systemtests, tox
=> Removing function not used for nifgen

generated/niscope/library.py, generated/niscope/session.py, generated/niscope/unit_tests/mock_helper.py, src/niscope/metadata/functions_addon.py, src/niscope/system_tests/test_system_niscope.py
**- Adding more systemtests for niscope**
1. test_fetch_read_measuremet
2. test_configure_chan_characteristics
3. test_filter_coefficients
4. test_send_software_trigger_edge
5. test_disable
**Removing SetAttributeViInt64 and GetAttributeViInt64 method since there is no attribute of ViInt64**
Partial towards #520 
Systemtests, tox
=> Removing unused attribute methods and adding more systemtests for niscope

build/helper/metadata_add_all.py, build/templates/session.py.mako, generated/niscope/session.py, src/niscope/metadata/functions_addon.py, src/niscope/system_tests/test_system_niscope.py
*Allows customization of where a method is generated (class _SessionBase or Session).
* This used to be deduced from function metadata values for 'has_repeated_capability' and 'is_error_handling'
* Done through a new metadata value 'render_in_session_base'
* By default it's deduced from  'has_repeated_capability' and 'is_error_handling'
* But can be overridden in metadata
* Fix niscope functions_addon.py to pass parameter to _actual_meas_wfm_size()
* Move _actual_meas_wfm_size() to _SessionBase
* It needs to be …
=> Fix niscope.Session.active_channel.fetch_array_measurement()

build/helper/metadata_add_all.py, build/templates/session.py.mako, src/nimodinst/templates/session.py.mako
Allows to specify via metadata multiple, rather than just one, templates to apply to a single function.
This way we can generate twice for one function. This is necessary for numpy support: for example, we want both nidmm.Session.fetch_waveform() and nidmm.Session.fetch_waveform_into().
* Work towards #511 
Verified that by default generated code is the same. Feature will be leveraged in future PRs.
=> Allow specifying multiple templates for a single function

build/helper/codegen_helper.py, build/templates/session_default_method.py.mako, generated/nidcpower/session.py, generated/nidmm/session.py, generated/nifake/session.py, generated/nifgen/session.py, generated/nimodinst/session.py, generated/niscope/session.py, generated/niswitch/session.py
This takes care of an old TODO:
Most of the logic for generating the snippets in which we declare ctypes variables that are to be passed to the library live in get_ctype_variable_declaration_snippet().
The exception was declaring the variables for the second step of the IVI-dance. This is addressed in this PR.
N/A
Exisiting tests.
=> Consolidate codegen of ctypes variable declaration

generated/nifake/library.py, generated/nifake/session.py, src/nifake/metadata/functions.py
Fixes a small metadata inconsistency in NI-FAKE. A string was not marked as a buffer. The generator didn't catch it due to how the logic is laid out.
I caught it in an attempt to refactor parts of the code generator. This will come in a future PR.
N/A
Generated Python doesn't change so all is the same. The documentation got fixed though.
=> Small metadata fix to NI-FAKE

src/nifgen/system_tests/test_system_nifgen.py, src/niscope/system_tests/test_system_niscope.py, tools/run_python_system_tests.py
Added 2 optional parameter for running systemtests on internal testsuite.
'-pv', '--python_version',  accepts py27 and py36.
'-pb', '--python_bitness', accepts ' ' and '--32'
Adding new system test for nifgen
- test_write_waveform_from_file_f64
* Fix #644 
* Fix #484 
systemtests, tox
=> updating helper file for system_tests on internal testsuite

CHANGELOG.md, build/helper/codegen_helper.py, build/helper/metadata_add_all.py, build/helper/metadata_filters.py, build/helper/parameter_usage_options.py, build/templates/session.py.mako, docs/conf.py, generated/nidmm/session.py, generated/nifake/session.py, generated/nifake/unit_tests/test_session.py, generated/niscope/session.py, src/nidmm/metadata/functions_addon.py, src/nidmm/system_tests/test_system_nidmm.py, src/nifake/metadata/functions_addon.py, src/nifake/unit_tests/test_session.py, src/niscope/metadata/functions_addon.py, src/niscope/system_tests/test_system_niscope.py, tox.ini
[X] I've ~~added~~updated tests applicable for this pull request
* `id_query` does not do anything on NI devices
* Remove from any session constructor parameter lists that had it
* nidmm
* niscope
* nifake (for unit testing)
* When removed, pass on the default value to the underlying init function, usually `InitWithOptions()`
* Fix #670 
* Unit
* System
=> Remove id_query parameter from Session() where appropriate

generated/nimodinst/session.py, generated/nimodinst/unit_tests/test_modinst.py, src/nimodinst/templates/session.py.mako, src/nimodinst/unit_tests/test_modinst.py, tox.ini
[X] I've ~~added~~removed tests applicable for this pull request
* Create a iterator of list of Devices when iterating on session
* This allows multiple simultaneous iterators.
* Fix #669 
* Unit
* System
=> Create object and return iter instead of implementing iter on nimodinst session

build/helper/metadata_add_all.py, build/helper/metadata_merge_dicts.py
* Make regular expression an option when merging dictionaries
* Only use regular expressions when merging function metadata
* Fix #624 
* Unit
* System
=> [4]Only use regular expressions for functions

build/templates/session.py.mako, generated/nidcpower/session.py, generated/nidmm/session.py, generated/nifake/session.py, generated/nifake/unit_tests/test_session.py, generated/nifgen/session.py, generated/niscope/session.py, generated/niswitch/session.py, src/nifake/unit_tests/test_session.py
* Calling `session.initiate()` outside of a context manager did not work as expected
* Move actual call to driver `_initiate()` into constructor so it is always called, regardless of whether it is used within a context manager or not.
* If called outside of a context manager, user is responsible for calling session.abort()
* Added test that demonstrated issue prior to fix and not afterwards
* Fix #745 
* Unit
* System
=> Fix initiate usage without context manager

build/helper/metadata_add_all.py, docs/nidcpower/functions.rst, docs/nidmm/functions.rst, docs/niscope/functions.rst, docs/niswitch/functions.rst, generated/nidcpower/session.py, generated/nifgen/session.py, generated/niscope/session.py
* Remove quotes around default values in documentation
`timeout='datetime.timedelta(seconds=1.0)'` --> `timeout=datetime.timedelta(seconds=1.0)`
=> Remove quotes around default values in documentation

build/helper/documentation_helper.py, docs/nidcpower/attributes.rst, docs/nidmm/attributes.rst, docs/nifgen/attributes.rst, docs/niswitch/attributes.rst, generated/nidcpower/session.py, generated/nidmm/session.py, generated/nifake/session.py, generated/nifgen/session.py, generated/niscope/session.py, generated/niswitch/session.py
* Look for 'an attribute' and replace with 'a property', plus variations of capitalization
* Fix #808 
=> Fix poor English created when substituting property for attribute

CHANGELOG.md, build/templates/errors.py.mako, generated/nidcpower/errors.py, generated/nidmm/errors.py, generated/nifake/errors.py, generated/nifgen/errors.py, generated/nimodinst/errors.py, generated/niscope/errors.py, generated/niswitch/errors.py
* `SelfTestError` now inherits from `<driver>.Error`
* Fix #830 
* Unit
* System
=> SelfTestError needs to inherit from Error, not Exception

CHANGELOG.md, build/templates/__init__.py.mako, build/templates/errors.py.mako, generated/nidcpower/__init__.py, generated/nidcpower/errors.py, generated/nidmm/__init__.py, generated/nidmm/errors.py, generated/nifake/__init__.py, generated/nifake/errors.py, generated/nifake/unit_tests/test_session.py, generated/nifgen/__init__.py, generated/nifgen/errors.py, generated/nimodinst/__init__.py, generated/nimodinst/errors.py, generated/nimodinst/unit_tests/test_modinst.py, generated/niscope/__init__.py, generated/niscope/errors.py, generated/niswitch/__init__.py, generated/niswitch/errors.py, src/nifake/unit_tests/test_session.py, src/nimodinst/unit_tests/test_modinst.py
* Renamed warning class name to `<driver>.DriverWarning` for all drivers
* Fix #658 
* Unit
* System
=> Change Warning class name to be PEP8 compliant

tools/run_python_system_tests.py
- [x ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
The system tests were failing on machines that had upgraded pip. This was because pip removed the .main function in pip 10.0. Using another method to install tox. This also upgrades pip as well.
* Fix #844 
Ran Flake8
Ran system test before changes and verify it fails. 
Ran system test after changes and verify it worked.
=> Fixing system test running tools

CHANGELOG.md, docs/nifgen/class.rst, generated/nifgen/_library.py, generated/nifgen/session.py, generated/nifgen/unit_tests/_mock_helper.py, src/nifgen/metadata/functions_addon.py, src/nifgen/system_tests/test_system_nifgen.py, src/nifgen/templates/session.py/delete_waveform.py.mako, src/nifgen/templates/session.py/set_next_write_position.py.mako
* Combines methods that use `waveform_handle` or `waveform_name` into a single method
* Internally calls the correct method
* `set_waveform_next_write_position()` and `set_named_waveform_next_write_position()` becomes `set_next_write_position()`
* `clear_arb_waveform()` and `delete_named_waveform()` becomes `delete_waveform()`
* Fix #862 
* Unit
* System
=> nifgen combine named and non-named waveform methods

CHANGELOG.md, docs/nidmm/class.rst, generated/nidmm/session.py, src/nidmm/metadata/attributes_addon.py
* Fix attribute name that is incorrect in extracted metadata
* `freq_voltage_autorange` --> `freq_voltage_auto_range`
* Fix #874 
* Unit
* System
=> Fix attribute name that is incorrect in extracted metadata

generated/nidcpower/session.py, generated/nidmm/session.py, generated/nifake/session.py, generated/nifgen/session.py, generated/niscope/_library.py, generated/niscope/session.py, generated/niscope/unit_tests/_mock_helper.py, generated/niswitch/session.py, src/nidcpower/metadata/functions_addon.py, src/nidcpower/system_tests/test_system_nidcpower.py, src/nidmm/metadata/functions_addon.py, src/nidmm/system_tests/test_system_nidmm.py, src/nifake/metadata/functions_addon.py, src/nifgen/metadata/functions_addon.py, src/nifgen/system_tests/test_system_nifgen.py, src/niscope/metadata/functions_addon.py, src/niscope/system_tests/test_system_niscope.py, src/niswitch/metadata/functions_addon.py, src/niswitch/system_tests/test_system_niswitch.py
* Add `error_message` to `niscope` - needed for complete error handling
* Don't acquire session lock around error handling methods
* Update error_message tests to catch more issues
* Unit
* System
=> error message clean up

CHANGELOG.md, build/templates/session.py.mako, generated/nidcpower/session.py, generated/nidmm/session.py, generated/nifake/session.py, generated/nifake/unit_tests/test_session.py, generated/nifgen/session.py, generated/niscope/session.py, generated/niswitch/session.py, src/nifake/unit_tests/test_session.py
* Disallow repeated capability on session
* Explicitly disallow using a repeated capability on Session. `session[0].vertical_range = 1.0` will no longer work. Instead use `session.channels[0].vertical_range = 1.0`
* Fix #853 
* Unit
* System
=> Disallow repeated capability on session

CHANGELOG.md, docs/nifgen/class.rst, docs/nifgen/enums.rst, generated/nifgen/_library.py, generated/nifgen/enums.py, generated/nifgen/session.py, generated/nifgen/unit_tests/_mock_helper.py, src/nifgen/metadata/functions_addon.py, src/nifgen/system_tests/test_system_nifgen.py
* Make nifgen send_software_edge_trigger() private
* This is the first step for #850 
* Next step will be to create fancy wrapper(s) that will send the correct trigger depending on if it is sent from `session` or from the `script_trigger` repeated capabilities container.
* Unit
* System
=> Make nifgen send_software_edge_trigger() private

CONTRIBUTING.md, generated/niscope/_library_singleton.py, src/niscope/metadata/config.py
I don't consider this a client facing change since no one is using NI-SCOPE on Linux yet. When Linux is officially supported, then CHANGELOG should be updated to reflect the addition of Linux support.
update NI-SCOPE library name for Linux
I ran the NI-SCOPE examples (in ./src/niscope/examples) on a pre-release build of the NI-SCOPE Linux driver.
=> update NI-SCOPE library name for Linux

src/niswitch/examples/niswitch_get_device_info.py
Fixes some typos, alleviates confusion if none of -d, -c, and -r are specified.
Ran.
=> Fixing help strings for niswitch_get_device_info example.

.travis.yml, CHANGELOG.md, build/templates/_converters.py.mako, build/templates/setup.py.mako, generated/nidcpower/_converters.py, generated/nidmm/_converters.py, generated/nifake/_converters.py, generated/nifgen/_converters.py, generated/nimodinst/_converters.py, generated/niscope/_converters.py, generated/niswitch/_converters.py, tox.ini
* Fix issues with Python 3.7
* Add official support for Python 3.7
* Fix #895 
* Unit
* System
=> Support Python 3.7

CHANGELOG.md, generated/nifake/setup.py, generated/niscope/setup.py, generated/niscope/waveform_info.py, src/niscope/custom_types/waveform_info.py
- [x ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
- [x ] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.
Previously when we would call `print(waveform[0])` it would show information that needed additional spacing. 
Old
```
channel             : 0record              : 0Absolute X0         : 0
Relative X0         : -9.99999e-06
dt                  : 2e-08
offset              : 0
gain                : 1wfm length          : 1,000
```
New
```
channel             : 0
record              : 0
Absolute X0         : 0
Relative X0         : -9.99999e-06
dt                  : 2e-08
offset              : 0
gain                : 1
wfm length          : 1,000
```
Ran tox.
Ran …
=> Fixing spacing in waveform_info.py

build/helper/metadata_merge_dicts.py, src/nidcpower/metadata/functions_addon.py, src/nidmm/metadata/attributes_addon.py, src/nifake/metadata/functions_addon.py, src/nifgen/metadata/attributes_addon.py, src/nimodinst/metadata/functions_addon.py, src/niscope/metadata/attributes_addon.py, src/niscope/metadata/functions_addon.py, src/niswitch/metadata/attributes_addon.py
* Added check for top level metadata that exists in addon but not in the sourced metadata
* `*_additional_*` is the only dictionary that is allowed to add top level items
* There were enough items that were uncovered by this check I decided to make this a separate PR instead of including it with the additional test called for by issue #900 
* In general, I deleted if the only reference was to disable code generation, and commented out if there was other information trying to be set
* First part of fixing #900
* Unit
=> Add check for top level metadata that exists in addon but not in the sourced metadata

build/templates/session.py.mako, generated/nidcpower/session.py, generated/nidmm/session.py, generated/nifake/session.py, generated/nifake/unit_tests/test_session.py, generated/nifgen/session.py, generated/niscope/session.py, generated/niswitch/session.py, src/nifake/unit_tests/test_session.py
* Use [wraps](https://docs.python.org/3/library/functools.html#functools.wraps) for `@ivi_synchronized`. This ensures `session.<method>.__name__` returns the method name instead of the helper method in `@ivi_synchronized`
* Add test for both ivi_synchronized methods and non-ivi_synchronized methods
* Fix #952 
* Unit
* System
=> Add @wraps to @ivi_synchronized

build/templates/session.py.mako, generated/nidcpower/session.py, generated/nidmm/session.py, generated/nifake/session.py, generated/nifgen/session.py, generated/niscope/session.py, generated/nise/session.py, generated/niswitch/session.py
* Remove `__getitem__()` from `Session`
* Was originally implemented to help clarify that indexing for repeated capabilities belongs on the repeated capabilities containers
* That was only during the prerelease stage and is now properly documented
* Fix #955 
* Unit
* System
=> Remove  __getitem__ from Session

CHANGELOG.md, src/nifgen/metadata/enums_addon.py
* Fix the values in the `HardwareState` enum to match the values in niFgen.h
* System
* Unit
=> Fix enum.HardwareState values to match niFgen.h

.travis.yml, tox.ini
* Cleans up build on Travis CI
* pypy3 now passes
* Don't pin `flake8` dependency
* `hacking` is top level package and will pull in `flake8`
* `hacking` does not work with latest flake and if we explicitly add `flake8`, we have to manually pin it to a version `hacking` works with
* By not listing `flake8` at all, we let pip pull in a compatible version
* Don't list `basepython` in tox.ini
* Either never needed or not needed any more
* Breaks pypy/pypy3 build by listing
* numpy does not currently work with pypy/pypy3-7.1.1 numpy/numpy#13807
* Only limit numpy dependency for pypy/pypy3 builds to <1.16, allow other builds to use latest
* Python 3.8 still broken - see numpy/numpy#13790 and linked Python issues for discussion possible solutions
* There doesn't look like we will need to do …
=> Cleans up build on Travis CI and fix pypy/pypy3 builds

build/templates/_attributes.py.mako, generated/nidcpower/_attributes.py, generated/nidigital/_attributes.py, generated/nidmm/_attributes.py, generated/nifake/_attributes.py, generated/nifgen/_attributes.py, generated/niscope/_attributes.py, generated/niswitch/_attributes.py, generated/nitclk/_attributes.py, src/nitclk/metadata/attributes.py
* nitclk session type attributes are actually type `ViSession` and not `ViInt32`
* Also, functions are `GetAttributeViSession()`/`SetAttributeViSession()` and not `GetAttributeViInt32()`/`SetAttributeViInt32()`
* Visual inspection
=> Fix ViSession attribute type for nitclk

build/templates/_library_singleton.py.mako, generated/nidcpower/_library_singleton.py, generated/nidigital/_library_singleton.py, generated/nidmm/_library_singleton.py, generated/nifake/_library_singleton.py, generated/nifgen/_library_singleton.py, generated/nimodinst/_library_singleton.py, generated/niscope/_library_singleton.py, generated/nise/_library_singleton.py, generated/niswitch/_library_singleton.py, generated/nitclk/_library_singleton.py
ctypes on python 3.8 requires full relative paths
- [ X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nimi-python/blob/master/CONTRIBUTING.md).
- ~~[ ] I've added tests applicable for this pull request~~
System tests in place should suffice.
on python 3.8 the API will always return driver not installed error because we are not using a full ablsolute path to the driver .dlls
python 3.8 can't load NI-SCOPE runtime
* Fix #1091 
- ran system tests provided. 
- the error in the issue #1091 doesn't happen anymore.
=> Changing _library_singleton.py to pass a relative path to ctypes.CDLL()

generated/nidigital/_library.py, generated/nidigital/session.py, generated/nidigital/unit_tests/_mock_helper.py, src/nidigital/metadata/functions.py
Remove _get/set_attribute_vi_session methods from nidigital, as they are not needed.
None
=> Remove _get/set_attribute_vi_session methods from nidigital

src/nifgen/system_tests/test_system_nifgen.py
Use path.join() instead of slashes for dir path in fgen system tests
None
None
=> Use path.join() instead of slashes for dir path in fgen system tests

build/helper/codegen_helper.py
* Validates that `'in'` array parameters do not have a mechanism of `'passed-in'`
* Add extra information for assert messages
* Fix #1116
=> Additional metadata validation

CHANGELOG.md, docs/nidigital/class.rst, generated/nidigital/session.py, src/nidigital/metadata/config.py
* `pins` is now a repeated capability
``` python
session.pins[['VCC','CLK']].ppmu_voltage_level = 4
session.pins['VCC,CLK'].ppmu_voltage_level = 4
```
* Fix #1093 
=> Add pins rep cap

docs/nidcpower/class.rst, generated/nidcpower/session.py, src/nidcpower/metadata/functions.py
* Fix nidcpower get_channel_name() documentation by removing repeated capability required
* Need to explicitly say `channelName` parameter isn't a repeated capability because it is one of the "magic" names
* Fix #1101 
=> Fix nidcpower get_channel_name() documentation

CHANGELOG.md, docs/nidigital/class.rst, generated/nidigital/session.py, src/nidigital/metadata/functions.py, src/nidigital/system_tests/test_system_nidigital.py
* Renames `write_source_waveform_broadcast_u32()` to write_source_waveform_broadcast()`
* Fix #1105 
* Visual inspection to generated files
=> Remove u32 from write_source_waveform_broadcast_u32

build/Makefile, build/rules.mak, build/tools.mak
* Cleans up dependencies for global files
* They now properly build only when an actual dependency changes
* Build is triggered when any driver file rebuilds
These no longer apply, but I think they were already fixed. Either way, they are fixed now so I am marking them as fixed by this PR.
* Fix #647 
* Fix #689 
* Builds. Lots and lots of builds.
=> Make rules cleanup for global files

src/nidcpower/system_tests/test_system_nidcpower.py
* No longer used devices whose driver internally uses the DAQmx framework.
* This was being done as a workaround for a driver bug that has been since fixed: `self_test()` and `device_reset()` didn't work on simulated 416x. 416x does not use the DAQmx framework.
* Opening sessions to devices that internally use DAQmx framework is very slow.
* Opening sessions in parallel to devices that internally use DAQmx framework intermittently fails. We want to overhaul our system testing to parallelize so need to work around this internal NI driver runtime bug.
* System
=> nidcpower system_tests - stop using DAQmx-framework devices

src/nidigital/system_tests/test_files/pin_map.pinmap, src/nidigital/system_tests/test_system_nidigital.py
Add tests for `get_pin_results_pin_information`. This method was made "fancy" in Python:
- Instead of returning pin indices, we call `get_pin_name` and return pin names
- Instead of returning channel numbers (int), we return fully-qualified channel names
- Instead of returning 3 different arrays (as in C API), we return a list of `collections.namedtuple('PinInformation', ['pin_name', 'site_number', 'channel_name'])`
None
Ran tests
=> Add tests for get_pin_results_pin_information

src/nifgen/system_tests/test_system_nifgen.py
* Switch to using 5433 to avoid random error from parallel execution
* System
=> Use 5433 for system test

build/templates/tox-system_tests.ini.mako, generated/nidcpower/tox-system_tests.ini, generated/nidigital/tox-system_tests.ini, generated/nidmm/tox-system_tests.ini, generated/nifake/tox-system_tests.ini, generated/nifgen/tox-system_tests.ini, generated/nimodinst/tox-system_tests.ini, generated/niscope/tox-system_tests.ini, generated/nise/tox-system_tests.ini, generated/niswitch/tox-system_tests.ini, generated/nitclk/tox-system_tests.ini, src/nifgen/system_tests/test_system_nifgen.py, src/niscope/system_tests/test_system_niscope.py
* Check for existing DAQmx simulated device
* Use this if it exists, otherwise, mark the test as skipped
* System tests
=> Use persistent DAQmx simulated device for nifgen system tests

src/niscope/system_tests/test_system_niscope.py
It was not obvious to me, it will be much less obvious to someone who hasn't been involved in the project from day one.
=> Explain why niscope test code uses persistent simulation

tools/system_test_jobs.groovy
* Sets allow concurrent builds flag on all jobs
* Since the builds are different PRs there is no reason not to allow them
* This has already been added to nimi-bot, this is just to update the script in git
* System
=> Allow concurrent builds on nimi-bot

tools/system_test_jobs.groovy
* We want to allow concurrent builds, but we need to limit it to one per node
* This prevents issues with two jobs trying to modify the venv at the same time
* System
=> Limit one concurrent job per node

src/nidigital/examples/nidigital_do_nothing.py, src/nidigital/system_tests/test_system_nidigital.py, src/nifgen/examples/nifgen_script.py, src/nifgen/system_tests/test_system_nifgen.py, src/niscope/system_tests/test_system_niscope.py, src/nitclk/examples/nitclk_configure.py, src/nitclk/system_tests/tests_system_nitclk.py, tox-travis.ini, tox.ini
* When we quit copying examples and system_tests to generated, we no longer had flake8 coverage of these folders
* Run flake8 on system_tests and examples for each driver
* flake8
=> Run flake8 on examples and system_tests

CHANGELOG.md, docs/nidigital/class.rst, generated/nidigital/nidigital/session.py, src/nidigital/metadata/functions.py, src/nidigital/metadata/functions_addon.py, src/nidigital/system_tests/test_system_nidigital.py, src/nidigital/templates/session.py/fancy_fetch_history_ram_cycle_information.py.mako
Following methods are updated such that pins repeated capability can be used on them:
```
configure_time_set_compare_edges_strobe
configure_time_set_compare_edges_strobe2x
configure_time_set_drive_edges
configure_time_set_drive_edges2x
configure_time_set_drive_format
configure_time_set_edge
configure_time_set_edge_multiplier
create_capture_waveform_parallel
create_capture_waveform_serial
create_source_waveform_parallel
create_source_waveform_serial
fetch_history_ram_cycle_information
get_time_set_drive_format
get_time_set_edge
get_time_set_edge_multiplier
```
* Fix #1294 
A new system test is added to verify pins can be used as repeated capability.
=> Update nidigital API methods to use pins repeated capability

generated/nifake/nifake/_library.py, generated/nifake/nifake/session.py, generated/nifake/nifake/unit_tests/_mock_helper.py, generated/nifake/nifake/unit_tests/test_session.py, src/nifake/metadata/attributes.py, src/nifake/metadata/config.py, src/nifake/metadata/enums.py, src/nifake/metadata/functions.py, src/nifake/unit_tests/test_session.py
Update method names in nifake to be language-agnostic:
- `accept_list_of_time_values` changed to `accept_list_of_durations_in_seconds`
- `return_list_of_timedeltas` changed to `return_list_of_durations_in_seconds`
Note: These changes are sourced from internal metadata.
None
Ran unit tests
=> Update method names in nifake to be language-agnostic

build/rules.mak, build/templates/examples.rst.mako, docs/nidcpower/examples.rst, docs/nidigital/examples.rst, docs/nidmm/examples.rst, docs/nifgen/examples.rst, docs/nimodinst/examples.rst, docs/niscope/examples.rst, docs/nise/examples.rst, docs/niswitch/examples.rst, docs/nitclk/examples.rst, tools/build_release.py
- In the master version of documentation, update the text to provide links to two versions of examples:
1. master version
2. latest release version
- Fix the dependency of examples.rst in `rules.mak` so that the examples URL gets updated when making a release
- Update the build script to instruct developer to update `LASTEST_RELEASE` file before `--build` step
* Fix #1322
* Fix #1326
Visual inspection of generated `examples.html`
=> Update Examples URL in documentation of master version

CHANGELOG.md, docs/nidigital/class.rst, docs/nidigital/enums.rst, generated/nidigital/nidigital/enums.py, generated/nidigital/nidigital/session.py, src/nidigital/metadata/attributes.py, src/nidigital/metadata/enums.py, src/nidigital/metadata/enums_addon.py, src/nidigital/metadata/functions.py, src/nidigital/system_tests/test_system_nidigital.py
- Change the type of method parameters and properties in nidigital to enums, where possible.
- Do not use the abbreviation for History RAM - HRAM in public API.
* Fix #1066 
* Fix #1244 
Visual inspection of generated files and running existing system tests
=> Change the type of method parameters and properties in nidigital to enums

docs/nidigital/class.rst, generated/nidigital/nidigital/session.py, src/nidigital/metadata/attributes.py, src/nidigital/metadata/functions.py, src/nidigital/system_tests/test_system_nidigital.py
Change type of applicable time-based method parameters and properties to datetime.timedelta. Users would be able to pass either floats (to represent time in seconds) or datetime.timedelta objects. This will make nidigital consistent with other APIs in nimi-python.
* Fix #1216
Ran system tests
=> Change type of applicable time-based method parameters and properties to datetime.timedelta

CHANGELOG.md, docs/nidigital/class.rst, generated/nidigital/nidigital/session.py, src/nidigital/metadata/functions.py, src/nidigital/metadata/functions_addon.py, src/nidigital/system_tests/test_system_nidigital.py, src/nidigital/templates/session.py/fancy_burst_pattern.py.mako
Update burst_pattern method to return pass/fail results if wait_until_done is True. With this change, users can use `burst_pattern` is two ways:
1. Does not wait for pattern burst to complete.
2. Waits for pattern burst to complete and expect pass-fail results to be returned. (Majority use-case)
* Fix #1296 
Added and ran new system tests.
=> Update burst_pattern method to return pass/fail results if wait_until_done is True

docs/nidigital/class.rst, generated/nidigital/nidigital/session.py, src/nidigital/metadata/functions_addon.py
Add rep cap tip to `get_site_pass_fail` docstring, by adding `site_list` parameter to metadata. This is workaround for #1343. Proper fix is tracked by #1342.
* Fix #1343
Visual inspection of generated files. Running of existing system tests.
=> Modify metadata to add rep cap tip to get_site_pass_fail docstring

generated/nidigital/nidigital/session.py, src/nidigital/system_tests/test_system_nidigital.py, src/nidigital/templates/session.py/fancy_fetch_history_ram_cycle_information.py.mako
Fix two bugs in `fetch_history_ram_cycle_information`:
- Fix typo in the call to `convert_site_to_string` method
- If History RAM is empty and user asks for 0 samples (position = 0, samples_to_read = 0) or all samples (position = 0, samples_to_read = -1), `fetch_history_ram_cycle_information` used to throw. Updated logic to return an empty list instead.
* Fix #1346 
* Fix #1347 
Added a new system test and ran all system tests and unit tests.
=> Fixes in fetch_history_ram_cycle_information - handle empty HRAM case and fix converter name

CHANGELOG.md, docs/nidigital/class.rst, docs/nidigital/enums.rst, generated/nidigital/nidigital/enums.py, generated/nidigital/nidigital/session.py, src/nidigital/metadata/attributes.py, src/nidigital/metadata/enums.py, src/nidigital/metadata/functions.py, src/nidigital/metadata/functions_addon.py, src/nidigital/system_tests/test_system_nidigital.py, src/nidigital/templates/session.py/fancy_fetch_capture_waveform.py.mako, src/nidigital/templates/session.py/fancy_get_site_pass_fail.py.mako
Update enum types in nidigital to match the API in other ADEs:
- Update the names of many enum types.
- Added `WriteStaticPinState` enum type and changed the parameter type of `write_static` method to the newly added enum.
- Added `SoftwareTrigger` enum type and changed the parameter type of `send_software_edge_trigger` method to the newly added enum.
- Removed `SessionState` enum type from metadata.
Note: Internal metadata is being updated in an internal changelist.
* Fix #1330 
Updated API methods in system tests to use the updated enum types and ran system tests successfully.
=> Update enum types in nidigital to match the API in other ADEs

CHANGELOG.md, docs/nidigital/class.rst, docs/nidigital/enums.rst, generated/nidigital/nidigital/enums.py, generated/nidigital/nidigital/session.py, src/nidigital/metadata/functions.py, src/nidigital/templates/session.py/fancy_fetch_capture_waveform.py.mako, src/nidigital/templates/session.py/fancy_get_site_pass_fail.py.mako
Remove get_site_results_site_numbers() and SiteResultType enum from public API. Users do not need to use this method since site numbers are included in the data returned by get_site_pass_fail() and fetch_capture_waveform().
* Fix #1298 
Ran system tests that indirectly call removed method and enum.
=> Remove get_site_results_site_numbers() and SiteResultType enum from public API

CHANGELOG.md, build/templates/_converters.py.mako, docs/nidigital/class.rst, generated/nidcpower/nidcpower/_converters.py, generated/nidigital/nidigital/_converters.py, generated/nidigital/nidigital/session.py, generated/nidigital/nidigital/unit_tests/test_nidigital.py, generated/nidmm/nidmm/_converters.py, generated/nifake/nifake/_converters.py, generated/nifgen/nifgen/_converters.py, generated/nimodinst/nimodinst/_converters.py, generated/niscope/niscope/_converters.py, generated/nise/nise/_converters.py, generated/niswitch/niswitch/_converters.py, generated/nitclk/nitclk/_converters.py, src/nidigital/metadata/functions.py, src/nidigital/metadata/functions_addon.py, src/nidigital/system_tests/test_system_nidigital.py, src/nidigital/templates/session.py/fancy_fetch_history_ram_cycle_information.py.mako, src/nidigital/unit_tests/test_nidigital.py
Update these methods in nidigital to use sites repeated capability:
- fetch_history_ram_cycle_information
- get_history_ram_sample_count
- is_site_enabled
* Fix #1337 
Added new unit tests and system tests
=> Update applicable methods in nidigital to use sites repeated capability

CHANGELOG.md, docs/nidigital/class.rst, generated/nidigital/nidigital/_library.py, generated/nidigital/nidigital/session.py, generated/nidigital/nidigital/unit_tests/_mock_helper.py, src/nidigital/metadata/functions.py
Remove `reset_attribute()` from nidigital API.
* Fix #1364 
Ran existing unit and system tests
=> Remove reset_attribute() from nidigital API

src/nifgen/system_tests/test_system_nifgen.py
Use this device which is a lot faster to simulate and doesn't require synchronization.
Uses 54x3 instead of 5421 in `test_get_hardware_state`. Support was added in NI-FGEN 17.8.
Using 54x3 is preferrable because simulated sessions open much faster, and because we don't need to synchronize opening/closing those sessions in order to workaround driver bugs.
None
Let nimi-bot run the system test.
=> Use 54x3 in get_hardware_state test

src/nidcpower/system_tests/test_system_nidcpower.py
~- [] I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~
Fix a bug in `test_reset_with_default()` in nidcpower.
None
Ran the fixed test
=> Fix a bug in test_reset_with_default() in nidcpower

generated/nidigital/nidigital/history_ram_cycle_information.py, src/nidigital/custom_types/history_ram_cycle_information.py, src/nidigital/system_tests/test_system_nidigital.py
Remove "PinState" from string representation of HistoryRAMCycleInformation
* Fix #1379
Added and executed new system test. Executed existing unit and system tests.
=> Remove "PinState" from string representation of HistoryRAMCycleInformation

CHANGELOG.md, docs/nidigital/class.rst, generated/nidigital/nidigital/_library.py, generated/nidigital/nidigital/session.py, generated/nidigital/nidigital/unit_tests/_mock_helper.py, src/nidigital/metadata/functions.py
Remove clock_generator_initiate() from nidigital API
* Fix #1370 
Ran existing unit and system tests
=> Remove clock_generator_initiate() from nidigital API

docs/nidigital/class.rst, generated/nidigital/nidigital/session.py, src/nidigital/metadata/functions.py, src/nidigital/metadata/functions_addon.py
- Note added to `get_history_ram_sample_count` and `fetch_history_ram_cycle_information`
- The note mentions that History RAM configuration must be done before bursting a pattern
* Fix #1390
Tests will be run by CI
=> Add a note to docstring of History RAM methods

CHANGELOG.md, docs/nidigital/class.rst, generated/nidigital/nidigital/session.py, src/nidigital/metadata/functions.py, src/nidigital/metadata/functions_addon.py, src/nidigital/system_tests/test_files/specifications_levels_and_timing_multiple/levels1.digilevels, src/nidigital/system_tests/test_files/specifications_levels_and_timing_multiple/levels2.digilevels, src/nidigital/system_tests/test_files/specifications_levels_and_timing_multiple/pin_map.pinmap, src/nidigital/system_tests/test_files/specifications_levels_and_timing_multiple/specs1.specs, src/nidigital/system_tests/test_files/specifications_levels_and_timing_multiple/specs2.specs, src/nidigital/system_tests/test_files/specifications_levels_and_timing_multiple/test.digiproj, src/nidigital/system_tests/test_files/specifications_levels_and_timing_multiple/timing1.digitiming, src/nidigital/system_tests/test_files/specifications_levels_and_timing_multiple/timing2.digitiming, src/nidigital/system_tests/test_files/specifications_levels_and_timing_single/levels.digilevels, src/nidigital/system_tests/test_files/specifications_levels_and_timing_single/pin_map.pinmap, src/nidigital/system_tests/test_files/specifications_levels_and_timing_single/specs.specs, src/nidigital/system_tests/test_files/specifications_levels_and_timing_single/test.digiproj, src/nidigital/system_tests/test_files/specifications_levels_and_timing_single/timing.digitiming, src/nidigital/system_tests/test_system_nidigital.py, src/nidigital/templates/session.py/fancy_load_specifications_levels_and_timing.py.mako, src/nidigital/templates/session.py/fancy_unload_specifications.py.mako
Improve usability of loading specifications, levels, and timing files and unloading specifications:
- Added `load_specifications_levels_and_timing` that allows loading of multiple specs, levels, and/or timing files in a single call
- Removed  `load_specifications`, `load_levels`, and `load_timing`
- Modified `unload_specifications` to allow unloading of one or more specs files in a single call
* Fix #1392
Added and executed new system tests
=> Improve usability of loading specifications, levels, and timing files and unloading specifications

CHANGELOG.md, docs/nidigital/class.rst, generated/nidigital/nidigital/_library.py, generated/nidigital/nidigital/session.py, generated/nidigital/nidigital/unit_tests/_mock_helper.py, src/nidigital/metadata/functions.py, src/nidigital/system_tests/test_system_nidigital.py
In nidigital, remove unnecessary prefix for file_path parameter in methods that load and unload files:
- _load_levels()
- load_pin_map()
- _load_specifications()
- _load_timing()
- _unload_specifications()
* Fix #1393
Updated impacted system tests and ran all nidigital system tests. Also ran unit tests. CI will run system tests for all modules.
=> In nidigital, remove unnecessary prefix for file_path parameter in methods that load and unload files

CHANGELOG.md, docs/nidigital/class.rst, generated/nidigital/nidigital/_library.py, generated/nidigital/nidigital/session.py, generated/nidigital/nidigital/unit_tests/_mock_helper.py, src/nidigital/metadata/functions.py, src/nidigital/system_tests/test_system_nidigital.py, src/nidigital/templates/session.py/fancy_get_pin_results_pin_information.py.mako
- Add get_channel_names()
- Remove get_channel_name() and get_channel_name_from_string()
* Fix #1386
Added new system test and ran all unit tests. System tests will be run by CI.
=> Improve usability of getting channel names from channel indices in nidigital

src/nidigital/system_tests/test_system_nidigital.py
* Adds nidigital system test `test_configure_voltage_levels`
* Adds nidigital system test `test_configure_active_load_levels`
Ran the new system tests on a system with nidigital 19.0.1 installed.
=> Adding tests for configuring levels

docs/nidigital/class.rst, generated/nidigital/nidigital/session.py, src/nidigital/metadata/functions.py, src/nidigital/metadata/functions_addon.py
Improve documentation related to types in applicable nidigital methods:
- Change "list" to "basic sequence types"
- Fix info related to types and "represented objects" in some parameter docstrings. The format used in nimi-python is `param_name (type): Info about the object that this parameter represents`. In certain places, the type and represented object was flipped.
None
Visual inspection of the generated filed. CI will run tests.
=> Improve documentation related to types in applicable nidigital methods

src/nidigital/system_tests/test_system_nidigital.py
* Adds nidigital system test `test_clock_generator_abort`
* Adds nidigital system test `test_clock_generator_generate_clock`
* Adds nidigital system test `test_frequency_counter_measure_frequency`
Ran the new system tests on a system with nidigital 19.0.1 installed.
=> Add nidigital clock generator and frequency counter system tests

generated/nidigital/nidigital/unit_tests/test_nidigital.py, src/nidigital/system_tests/test_system_nidigital.py, src/nidigital/unit_tests/test_nidigital.py
* Updates all nidigital tests except for one to use nidigital.<enum_name> to access enums.
- Update of the other test was blocked by #1426.  A TODO was created to update it, when possible.
* Ran unit tests.
* Ran the system tests on a system with nidigital 19.0.1 installed.
=> Make enum usage more consistent in nidigital tests

src/nidigital/system_tests/test_system_nidigital.py
* Documents coverage of `initiate` in `test_configure_pattern_burst_sites` and corrects api usage
* Adds test `test_commit`
* Adds test `test_initiate_context_manager_and_wait_until_done`
- Covers context manager for `initiate`
- Covers `wait_until_done`
- Covers `is_done`
* Adds test `test_abort`
* Adds test `test_abort_keep_alive`
Ran the system tests on a system with ni-digital 19.0.1 installed.
=> Add nidigital system tests for low level actions

build/helper/metadata_add_all.py, build/templates/class.rst.mako, build/templates/session.py.mako, build/templates/setup.py.mako, build/templates/tox-system_tests.ini.mako, src/nidcpower/metadata/config.py, src/nidigital/metadata/config.py, src/nifake/metadata/config.py, src/nifgen/metadata/config.py, src/niscope/metadata/config.py
Change metadata key `supports_nitclk` to `uses_nitclk`.
A new metadata key called `uses_hightime` will be added for #1368. This change will make the key names consistent.
None
No new tests added. CI will run the tests.
=> Change metadata key `supports_nitclk` to `uses_nitclk`

CHANGELOG.md, generated/nidigital/nidigital/history_ram_cycle_information.py, src/nidigital/custom_types/history_ram_cycle_information.py, src/nidigital/system_tests/test_system_nidigital.py
Update HistoryRAMCycleInformation.__repr__ to use `__module__` and `__qualname__`.
Best practice for implementing `__repr__` for custom types is to use
`__module__` and `__qualname__`.
By including `__module__` in `__repr__`, `eval(repr(HistoryRAMCycleInformation()))`
can be called by importing nidigital as `import nidigital`; which is
consistent with recommended import style of nimi-python.
If this change is accepted, `__repr__` for private and internal types
(including nifake) will be changed in a separate PR. `__repr__` for public
types in other modules will be done in 2.0 Source Breakers milestone.
* Fix #1426
Updated existing `__repr__` test. CI will run all tests.
=> Update HistoryRAMCycleInformation.__repr__ to use `__module__` and `__qualname__`

build/templates/_converters.py.mako, generated/nidcpower/nidcpower/_converters.py, generated/nidigital/nidigital/_converters.py, generated/nidmm/nidmm/_converters.py, generated/nifake/nifake/_converters.py, generated/nifake/nifake/_library.py, generated/nifake/nifake/session.py, generated/nifake/nifake/unit_tests/_mock_helper.py, generated/nifake/nifake/unit_tests/test_session.py, generated/nifgen/nifgen/_converters.py, generated/nimodinst/nimodinst/_converters.py, generated/niscope/niscope/_converters.py, generated/nise/nise/_converters.py, generated/niswitch/niswitch/_converters.py, generated/nitclk/nitclk/_converters.py, src/nifake/metadata/functions.py, src/nifake/unit_tests/test_session.py
Add a converter for converting seconds in float to timedelta.
Required for fixing #1397 
Added new unit tests. Tests will be run by CI.
=> Add a converter for converting seconds in float to timedelta

CHANGELOG.md, docs/nidigital/class.rst, generated/nidigital/nidigital/session.py, src/nidigital/metadata/functions.py, src/nidigital/system_tests/test_system_nidigital.py
Change return type of `get_time_set_period` and `get_time_set_edge` to `datetime.timedelta`.
Partial fix for Issue 1397
Tests have been updated as required. CI will run the tests.
=> Change return type of `get_time_set_period` and `get_time_set_edge` to `datetime.timedelta`

src/nidigital/system_tests/test_system_nidigital.py
* Adds nidigital system test `test_close`
* Adds nidigital system test `test_get_fail_count`
* Adds nidigital system test `test_send_software_edge_trigger`
Ran nidigital system tests on a system with nidigital 19.0.1 installed.
=> Add remaining nidigital system tests (excluding repeated capabilities)

build/helper/metadata_add_all.py, build/templates/setup.py.mako, generated/nidigital/setup.py, src/nidigital/metadata/config.py
- `datetime` will be replaced by `hightime` across all nimi-python modules in a separate PR.
- Undo changes of #1438 
None
CI will run tests.
=> Undo changes for adding hightime to nidigital installer

tox-travis.ini, tox.ini
Fix tox env ordering issue:
- flake8 and docs depend on codegen
- test depends on installers (for `install_local_wheel.py --driver nitclk`), not codegen
- pkg depends on installers
None
Ran `tox` in serial and parallel modes and verified the ordering is correct.
=> Fix tox env ordering issue

src/nidcpower/system_tests/test_system_nidcpower.py
Update test_query_max_current_limit in nidcpower to work with 20.0 driver runtime.
The change is required because nimi-bot was updated to NI-DCPower Runtime 20.0 recently. Due to change in driver runtime behavior, now simulated devices will create a high cooling chassis instance. The default value for max current limit on high cooling chassis should be 0.1A.
* Fix #1154 
Ran the test locally and verified it passes. CI will run all tests.
=> Update test_query_max_current_limit in nidcpower to work with 20.0 driver runtime

src/niscope/system_tests/test_system_niscope.py
Remove workaround for bug #959625 in niscope test. The internal bug was fixed in NI-Scope 20.0, which was installed on nimi-bot recently.
None
CI will run the tests.
=> Remove workaround for bug #959625 in niscope test

build/templates/setup.py.mako, generated/nidcpower/setup.py, generated/nidigital/setup.py, generated/nidmm/setup.py, generated/nifake/setup.py, generated/nifgen/setup.py, generated/nimodinst/setup.py, generated/niscope/setup.py, generated/nise/setup.py, generated/niswitch/setup.py, generated/nitclk/setup.py
Specify minimum version for `hightime` dependency in `setup.py`. `hightime` was heavily refactored in 0.2.0 and nimi-python modules rely on `hightime` version being 0.2.0 or later.
* Fix #1474 
Performed a manual test to ensure `hightime` version is bumped up to 0.2.0 when nimi-python module is pip installed.
=> Specify minimum version for `hightime` dependency in `setup.py`

CHANGELOG.md, build/helper/codegen_helper.py, generated/nidcpower/nidcpower/session.py, generated/nidigital/nidigital/session.py, generated/nidmm/nidmm/session.py, generated/nifake/nifake/session.py, generated/nifgen/nifgen/session.py, generated/niscope/niscope/session.py, generated/nitclk/nitclk/session.py
Fix intermittent failure in import_attribute_configuration_buffer() by updating code generator to pass non-temporary object to `get_ctypes_pointer_for_buffer()`.
* Fix #1491 
Created a test that calls `import_attribute_configuration_buffer()` by passing in `list` of `int`, in a loop. The test failed pretty consistently on my setup without the fix. With the fix, it ran for 1 million iterations without failure.
=> Fix intermittent failure in import_attribute_configuration_buffer()

tools/prepare_python_system_tests.py, tools/run_python_system_tests.py
Fix scripts used by ATS to run system tests. The scripts were broken because the `prepare` script referenced `src` folder which won't be present until `prepare` script is run once successfully.
Refactored the scripts so that `prepare` and `run` are decoupled from each other. The way to run system tests is:
```
mkdir %temp%\nimi-python
chdir %temp%\nimi-python
curl -o prepare_python_system_tests.py https://raw.githubusercontent.com/ni/nimi-python/master/tools/prepare_python_system_tests.py
curl -o run_python_system_tests.py https://raw.githubusercontent.com/ni/nimi-python/master/tools/run_python_system_tests.py
python …
```
=> Fix scripts used by ATS to run system tests

generated/niscope/niscope/session.py, src/niscope/templates/session.py/fancy_fetch.py.mako, src/niscope/templates/session.py/fancy_fetch_array_measurement.py.mako, src/niscope/templates/session.py/fancy_fetch_measurement_stats.py.mako
Eliminate code duplication in niscope fancy fetch methods by creating a helper method that's called from fancy methods
* Fix #1496 
Ran system tests locally
=> Eliminate code duplication in niscope fancy fetch methods

src/niscope/system_tests/test_system_niscope.py
- Update niscope system tests to use multi-instrument session, wherever possible 
- Setup the test code such that when a new test is added, by default multi-instrument session gets used. Tests can opt to use `single_instrument_session`, if required.
* Fix #1503 
Ran the system tests locally
=> Update niscope system tests to use multi-instrument session

build/templates/_attributes.py.mako, generated/nidcpower/nidcpower/_attributes.py, generated/nidigital/nidigital/_attributes.py, generated/nidmm/nidmm/_attributes.py, generated/nifake/nifake/_attributes.py, generated/nifake/nifake/session.py, generated/nifake/nifake/unit_tests/test_session.py, generated/nifgen/nifgen/_attributes.py, generated/niscope/niscope/_attributes.py, generated/niswitch/niswitch/_attributes.py, generated/nitclk/nitclk/_attributes.py, src/nifake/metadata/attributes.py, src/nifake/unit_tests/test_session.py
- Add support for properties of type `str` that represents a repeated capability
- It will be used to fix #1497 
Contribute towards fixing #1497 
Added and ran new unit tests in nifake
=> Add support for properties of type `str` that represents a repeated capability

docs/niscope/class.rst, generated/niscope/niscope/session.py, src/niscope/metadata/attributes.py
Make meas_other_channel in niscope work with channel repeated capability types. Users can now pass in `str` or `int` or any other type supported by channel repeated capability.
Metadata changes come from internal metadata source.
* Fix #1497 
None. The generated code is tested by nifake unit tests.
=> Make meas_other_channel in niscope work with channel repeated capability types

.gitignore, CHANGELOG.md, generated/niscope/niscope/session.py, generated/niscope/niscope/unit_tests/test_niscope.py, generated/niscope/niscope/waveform_info.py, src/niscope/custom_types/waveform_info.py, src/niscope/system_tests/test_system_niscope.py, src/niscope/templates/session.py/fancy_fetch.py.mako, src/niscope/templates/session.py/fetch_waveform.py.mako, src/niscope/unit_tests/test_niscope.py, tools/coverage_unit_tests.rc, tox-travis.ini, tox.ini
- Fix two bugs in niscope fetch methods
-- `channel` and `record` fields are swapped in `waveform_info` struct returned from niscope fetch methods
-- `record` value in `waveform_info` struct returned from niscope fetch methods is wrong if `record_number` is non-zero
- Added unit tests for helper functions in `waveform_info.py`
- Update system test for fetch to verify the `channel` and `record` attributes in returned `WaveformInfo` instances
* Fix #1509 
* Fix #1510 
Added new unit and system tests and ran them successfully, locally.
=> Fix bugs in niscope fetch methods

docs/niscope/class.rst, generated/niscope/niscope/_library.py, generated/niscope/niscope/session.py, generated/niscope/niscope/unit_tests/_mock_helper.py, src/niscope/metadata/functions.py, src/niscope/metadata/functions_addon.py, src/niscope/system_tests/test_system_niscope.py, src/niscope/templates/session.py/fancy_fetch_array_measurement.py.mako
Add `measWfmSize` param to `fetch_array_measurement` method in niscope, to be consistent with the corresponding VI in LabVIEW ADE.
Partial fix for #1501 
Updated system test
=> Add `measWfmSize` param to fetch_array_measurement method in niscope

docs/niscope/class.rst, generated/niscope/niscope/session.py, src/niscope/metadata/functions_addon.py, src/niscope/system_tests/test_system_niscope.py, src/niscope/templates/session.py/fancy_fetch_array_measurement.py.mako, src/niscope/templates/session.py/fancy_fetch_measurement_stats.py.mako
Add additional fetch related parameters to `fetch_array_measurement` and `fetch_measurement_stats` methods. This makes these methods be consistent with `fetch`:
https://github.com/ni/nimi-python/blob/028c8a1ed8e977d9d3558ff185d7bf4047929286/generated/niscope/niscope/session.py#L1909
* Fix #1501
Performed some dev testing on real h/w. Added/modified system tests to run on simulated h/w
=> Add additional fetch related parameters to `fetch_array_measurement` and `fetch_measurement_stats` methods

CHANGELOG.md, docs/nidcpower/class.rst, docs/nidcpower/enums.rst, generated/nidcpower/nidcpower/enums.py, generated/nidcpower/nidcpower/session.py, src/nidcpower/metadata/attributes.py, src/nidcpower/metadata/config.py, src/nidcpower/metadata/enums.py, src/nidcpower/metadata/functions.py
- API parity with NI-DCPower 20.5.0 by adding measurement autoranging threshold range support.
- Fix the documentation of `instrument_manufacturer`, `instrument_model`, and `serial_number` properties to correctly mention that they use `instruments` repeated capability.
N/a
System tests will be run by nimi-bot
=> nidcpower API update for NI-DCPower 20.5.0 Runtime changes

CONTRIBUTING.md
When referring to the generated .whl files, change path to be under 'generated' folder.
When referring to the system_tests, change path to be under 'src' folder.
Corrects paths in CONTRIBUTING.md that were incorrect.
Used the updated paths when installing the .whl files and running the system_tests.
=> Update out of date information in contributing guidelines

docs/conf.py, docs/nidigital/class.rst, generated/nidigital/nidigital/session.py, src/nidigital/metadata/functions.py
Adds Note to the documentation for is_site_enabled, clarifying that it is an error to specify more than one site.
* Fix #1421
=> Add Note to clarify that is_site_enabled can only be called for one site

docs/_static/nidigital_usage.inc, generated/nidigital/README.rst
Update nidigital_usage.inc to include code snippet of a basic PPMU example that does not use configuration files generated by digital pattern editor.
* Fix #1145 
Copy and paste this code snippet into an actual Python file, add option string for simulation, and run the example to produce this output:
```
PS Microsoft.PowerShell.Core\FileSystem::\\wsl$\Ubuntu\home\jxie\nimi-python> & C:/Users/Admin/AppData/Local/Programs/Python/Python38/python.exe //wsl$/Ubuntu/home/jxie/nimi-python/src/nidigital/examples/nidigital_example.py      
Channel Name,,,,,,,, Current,,, Voltage,,,
PXI1Slot2/0          0.000000   0.000000 …
```
=> Update nidigital_usage.inc with a basic PPMU example

src/nidigital/examples/ppmu_source_and_measure/nidigital_ppmu_source_and_measure.py
~- [ ] I've added tests applicable for this pull request.~
Fix current_level_range versus current_limit_range confusion in PPMU example
* Fix #1558 
All nidigital example tests passing with simulated devices.
=> Fix current_level_range versus current_limit_range confusion in PPMU example

CHANGELOG.md, docs/nidigital/class.rst, docs/nidigital/enums.rst, generated/nidigital/nidigital/enums.py, generated/nidigital/nidigital/session.py, src/nidigital/metadata/attributes.py, src/nidigital/metadata/attributes_addon.py, src/nidigital/metadata/enums.py
API parity with NI-Digital Pattern Driver 20.6.0 by adding support for configuration of frequency counter measurement mode. The following properties are added:
- `frequency_counter_measurement_mode`
- `frequency_counter_hysteresis_enabled`
None
None
=> API parity with NI-Digital 20.6.0 - Add support for frequency counter measurement mode

build/templates/examples.rst.mako
- Before this PR, the release version of docs link to master version of examples files. e.g. The link [here](https://nimi-python.readthedocs.io/en/1.3.2/nidcpower/examples.html#id4) points to [https://github.com/ni/nimi-python/blob/master/src/nidcpower/examples/nidcpower_advanced_sequence.py](https://github.com/ni/nimi-python/blob/master/src/nidcpower/examples/nidcpower_advanced_sequence.py). With this change, it will point to [https://github.com/ni/nimi-python/blob/1.3.2/src/nidcpower/examples/nidcpower_advanced_sequence.py](https://github.com/ni/nimi-python/blob/1.3.2/src/nidcpower/examples/nidcpower_advanced_sequence.py) …
=> Release version of docs link to release version of example files

build/templates/examples.rst.mako
Documentation files generated on a Windows operating system contained URL paths with backslashes instead of forward slashes because these URLs were obtained from Windows file paths. This change ensures those backslashes in those file paths are converted to forward slashes to create normalized URLs.
Built documentation and verified no changes between local files and repo.
=> Ensure URLs in generated documentation files do not contain backslashes when building on Windows

build/templates/_converters.py.mako, generated/nidcpower/nidcpower/_converters.py, generated/nidigital/nidigital/_converters.py, generated/nidmm/nidmm/_converters.py, generated/nifake/nifake/_converters.py, generated/nifake/nifake/unit_tests/test_converters.py, generated/nifgen/nifgen/_converters.py, generated/nimodinst/nimodinst/_converters.py, generated/niscope/niscope/_converters.py, generated/nise/nise/_converters.py, generated/niswitch/niswitch/_converters.py, generated/nitclk/nitclk/_converters.py, src/nifake/unit_tests/test_converters.py
In preparation for implementing independent channels constructor that takes a resource name parameter, we needed a converter that supports lists and tuples of resource names. With this modification to the existing repeated capabilities converter we can use it also for resource names.
Added unit tests to validate resource name conversions.
=> Modified repeated capabilities converter to support resource names

CHANGELOG.md, docs/nidcpower/class.rst, docs/nidcpower/enums.rst, generated/nidcpower/nidcpower/_library.py, generated/nidcpower/nidcpower/enums.py, generated/nidcpower/nidcpower/session.py, generated/nidcpower/nidcpower/unit_tests/_mock_helper.py, src/nidcpower/metadata/attributes.py, src/nidcpower/metadata/config.py, src/nidcpower/metadata/enums.py, src/nidcpower/metadata/functions.py
- API parity with NI-DCPower 20.7.0 by adding Output Cutoff functionality.
- Remove channels repeated capability from two properties in nidcpower that was previously added erroneously - `auxiliary_power_source_available` and `power_source_in_use`.
- Remove references to enum values (numerical values used by underlying C driver) from public method documentation.
None
PR build
=> API parity with NI-DCPower 20.7.0

build/templates/_library.py.mako, build/templates/errors.py.mako, generated/nidcpower/nidcpower/_library.py, generated/nidcpower/nidcpower/errors.py, generated/nidigital/nidigital/_library.py, generated/nidigital/nidigital/errors.py, generated/nidmm/nidmm/_library.py, generated/nidmm/nidmm/errors.py, generated/nifake/nifake/_library.py, generated/nifake/nifake/errors.py, generated/nifake/nifake/unit_tests/test_session.py, generated/nifgen/nifgen/_library.py, generated/nifgen/nifgen/errors.py, generated/nimodinst/nimodinst/_library.py, generated/nimodinst/nimodinst/errors.py, generated/niscope/niscope/_library.py, generated/niscope/niscope/errors.py, generated/nise/nise/_library.py, generated/nise/nise/errors.py, generated/niswitch/niswitch/_library.py, generated/niswitch/niswitch/errors.py, generated/nitclk/nitclk/_library.py, generated/nitclk/nitclk/errors.py, src/nifake/unit_tests/test_session.py
When a required function (e.g. CommitWithChannels) is missing from the driver runtime, nimi-python adds an error description that is more descriptive than "function not found" to instruct the user to upgrade to a newer version of the driver.
- Fix #1585 
Called abort and commit methods on a system with NI-DCPower 20.5 instrument driver and confirmed that the error message is displayed in the exception information at runtime.
=> Improve error message when function not found in driver runtime

build/helper/metadata_add_all.py, docs/nidcpower/class.rst, generated/nidcpower/nidcpower/session.py, src/nidcpower/metadata/functions.py
Uses an explicit metadata attribute (`is_repeated_capability`) to avoid adding repeated capability in a parameter for which its `name` would otherwise require it, but for which its `python_name` might not (e.g. get_channel_names)
This is a (lower priority) continuation of #1578 
Ensured unit test passes. Performed code generation locally to verify that the repeated capability is correctly removed from the `get_channel_names` function.
=> Use explicit metadata attribute to avoid adding repeated capability

build/templates/conf.py.mako, docs/conf.py
Replace the Sphinx library call `add_stylesheet` with `add_css_file`, since the former has been deprecated in new version of Sphinx. This fixes the Travis CI [failures](https://travis-ci.org/github/ni/nimi-python/jobs/770505265) we've started seeing.
None
PR build
=> Replace the Sphinx library call `add_stylesheet` with `add_css_file`

tools/system_test_jobs.groovy
GitHub said:
"""
We noticed your personal access token, nimi-bot system tests,
has an outdated format and was used to access the GitHub API on
May 19th, 2021 at 17:14 (UTC) with a user-agent header of
Java/1.8.0_144.
We recently updated the format of our API authentication tokens,
providing additional security benefits to all our customers.
In order to benefit from this new format, please regenerate your
personal access token, nimi-bot system tests, using the button below.
"""
Updates PAT used by nimi-bot. GitHub asked us to use a new one.
See if nimi-bot runs PR checks.
=> New PAT with with updated format

src/niswitch/system_tests/test_system_niswitch.py
Disable niswitch system tests that use session-simulated DAQmx devices since they fail intermittently on nimi-bot. Created #1622 to fix the failures.
None
Will verify the test is skipped on nimi-bot
=> Disable niswitch system tests that use session-simulated DAQmx devices

build/templates/tox-system_tests.ini.mako, generated/nidcpower/tox-system_tests.ini, generated/nidigital/tox-system_tests.ini, generated/nidmm/tox-system_tests.ini, generated/nifake/tox-system_tests.ini, generated/nifgen/tox-system_tests.ini, generated/nimodinst/tox-system_tests.ini, generated/niscope/tox-system_tests.ini, generated/nise/tox-system_tests.ini, generated/niswitch/tox-system_tests.ini, generated/nitclk/tox-system_tests.ini, src/nidcpower/system_tests/conftest.py, src/nidcpower/system_tests/test_system_nidcpower.py, tox.ini
Refactors the nidcpower system test to accomplish the following goals:
1. Reduce the number of fixtures, thus making it easier to decide which fixtures future devs should use.
2. Enable a developer to mark at test to run on a legacy session, independent channels session, or both
This PR also adds additional tests focused on channel based repeated capabilities for both session types.
- Resolves #1614 
Tests are passing on local machine.
=> Refactor nidcpower system tests

CHANGELOG.md, docs/nidcpower/class.rst, generated/nidcpower/nidcpower/session.py, src/nidcpower/metadata/attributes.py, src/nidcpower/metadata/config.py, src/nidcpower/metadata/enums.py, src/nidcpower/metadata/functions.py
Update nidcpower to be on par with API changes made in NI-DCPower 21.0.0 driver runtime.
-  Properties added:
- `output_cutoff_delay`
None
Visual inspection of generated files and PR build.
=> NI-DCPower 21.0.0 API parity

.travis.yml
Stop specifying a particular version of the OS to be used in travis-ci. It was previously required because the default version (trusty) didn't include OpenSSL 1.0.2 which was required in Python 3.7+. Currently the default version is xenial and I don't see a reason for pinning to a particular version.
None
travis-ci
=> Do not pin the OS used in travis-ci to a specific version

CHANGELOG.md, docs/nidigital/class.rst, docs/nidigital/enums.rst, docs/nidigital/rep_caps.rst, generated/nidigital/nidigital/enums.py, generated/nidigital/nidigital/session.py, src/nidigital/metadata/attributes.py, src/nidigital/metadata/config.py, src/nidigital/metadata/enums.py, src/nidigital/metadata/functions.py, src/nidigital/system_tests/test_system_nidigital.py
API parity with NI-Digital Pattern Driver 21.0.0.
* Properties added:
* `digital_edge_rio_trigger_edge`
* `digital_edge_rio_trigger_source`
* `exported_rio_event_output_terminal`
* `rio_event_terminal_name`
* `rio_trigger_terminal_name`
* `rio_trigger_type`
* Repeated Capabilities added:
* `rio_events`
* `rio_triggers`
None
- Manual review of API metadata
- Added new system tests for the new rep caps
- Execution of unit and system tests.
=> NI-Digital 21.0 API updates

build/templates/examples.rst.mako, tools/build_release.py
The wording and version used in examples documentation differs based on [master ](https://nimi-python.readthedocs.io/en/master/nidcpower/examples.html) version of the docs vs. [release](https://nimi-python.readthedocs.io/en/1.4.0/nidcpower/examples.html) version of the docs.
There was a bug in code generator that encodes this difference - The version in [VERSION file](https://github.com/ni/nimi-python/blob/master/VERSION) was used in the conditional, but that file is updated later in the build process than when `examples.rst` gets generated. So when the release build step is performed it does not have the correct content …
=> Update release process to use correct version in examples documentation

generated/nidigital/nidigital/unit_tests/test_nidigital.py, generated/nifake/nifake/unit_tests/test_session.py, generated/nimodinst/nimodinst/unit_tests/test_modinst.py, generated/nitclk/nitclk/unit_tests/test_nitclk.py, src/nidigital/unit_tests/test_nidigital.py, src/nifake/unit_tests/test_session.py, src/nimodinst/unit_tests/test_modinst.py, src/nitclk/unit_tests/test_nitclk.py, tox-travis.ini, tox.ini
Latest version of the flake8 plugin `hacking` added a check - `H216: The unittest.mock module should be used rather than the third party mock package unless actually needed.`
When I recreated my tox environment locally, I ran into this violation. The PR replaces third-party mock library with the built-in one.
Note: This is a retry of #1608, which was approved for submission but git rebase on it went south.
N/a
PR pipeline tests
=>  Use unittest.mock instead of third-party mock library

tox-travis.ini, tox.ini
`hacking` pulls in `flake8`. Listing both results in an old version of `hacking` (0.5.4) to be pulled in which is incompatible with the version of `flake8` (4.0.1)
None
PR build
=> Remove a direct dependency on flake8

.github/workflows/github_actions_aws_rhel_python64.yml, .github/workflows/github_actions_aws_windows_python32.yml, .github/workflows/github_actions_aws_windows_python64.yml
Issue: Totally 6 workflows are run instead of 3 when PR is created.  
Root Cause: If you specify multiple activity types, only one of those event activity types needs to occur to trigger your workflow. If multiple triggering event activity types for your workflow occur at the same time, multiple workflow runs will be triggered. Refer this [link](https://docs.github.com/en/enterprise-server@3.3/actions/using-workflows/workflow-syntax-for-github-actions#using-activity-types) for more details
Solution: Changed the types so that multiple types does not trigger at a same time.
Tested for the below use cases.
1. PR is created -> All 3 workflows ran a single instance.
2. PR is updated -> All 3 workflows ran a single instance.
3. PR is reopened -> All 3 workflows ran a single instance.
4. Draft …
=> Fix github workflow issues for AWS

build/templates/tox-system_tests.ini.mako, generated/nidigital/tox-system_tests.ini, generated/nifake/tox-system_tests.ini, generated/nifgen/tox-system_tests.ini, generated/niscope/tox-system_tests.ini, generated/nitclk/tox-system_tests.ini
Fix python binary name used in tox-system_tests.ini, so that system tests can be run on both Windows and Linux platforms via tox.
This will fix the failure we're seeing with the internal pipeline that creates the VMs for running system tests.
N/a
PR build
=> Fix python binary name used in tox-system_tests.ini

CONTRIBUTING.md, build/rules.mak, build/templates/tox-system_tests.ini.mako, generated/nidigital/tox-system_tests.ini, generated/nifake/tox-system_tests.ini, generated/nifgen/tox-system_tests.ini, generated/niscope/tox-system_tests.ini, generated/nitclk/tox-system_tests.ini
Removes python2 compatibility from wheel names as python 2 is no longer supported.
Done via removing `--universal` option when creating the `.whl` files
Also removed the reference to `py2` in the `CONTRIBUTING.md`
Fixes Issue: https://github.com/ni/nimi-python/issues/1641
Built locally and checked that the codegen output wheel file excludes the py2 compatibility tag.
Pull Request takes over and obsoletes Pull Request #1718 by cherry-picking commit from @mmorin-ni fork.
=> Remove --universal wheel option to prevent "py2" compatibility tag

CHANGELOG.md, build/helper/metadata_add_all.py
- Update `_add_python_method_name` to skip the assertion for `method_name_for_documentation` if the `codegen_method` of the function is "no"
- Add unit test for this change
All the build tests (including the updated ones) passed
=> Allow no-codegen method to have method_name_for_doc

generated/nifgen/nifgen/_library.py, generated/nifgen/nifgen/session.py, generated/nifgen/nifgen/unit_tests/_mock_helper.py, src/nifgen/metadata/functions.py
This pull request fixes a documentation issue where some functions in NI-FGEN that returned calibration dates returned `month` instead of `last_cal_datetime`. This has been updated to be consistent with SCOPE and DC-Power. 
Part of fix for issue "The return value of get_date_and_time() related function(s) across drivers should be consistently named"
Confirmed that generated files show `last_cal_datetime` as the return value instead of `month`.
=> Update return type of NI-FGEN datetime-related functions

CHANGELOG.md, docs/nidcpower/class.rst, docs/nidcpower/enums.rst, generated/nidcpower/nidcpower/enums.py, generated/nidcpower/nidcpower/session.py, src/nidcpower/metadata/attributes_addon.py, src/nidcpower/metadata/enums_addon.py, src/nidcpower/system_tests/test_system_nidcpower.py
- Enable simple LCR attributes and associated enums
- Properties added:
- `instrument_mode`
- `lcr_current_amplitude`
- `lcr_frequency`
- `lcr_stimulus_function`
- `lcr_voltage_amplitude`
- Enums added:
- `InstrumentMode`
- `LCRStimulusFunction`
- Update CHANGELOG.md
Locally added system tests passed.
```
test_lcr_attributes[True] PASSED
148 passed, 5 skipped in 16.42s
```
This PR is part of a series of PRs to enable all the new LCR metadata.
=> NI-DCPower: Enable simple LCR metadata

CHANGELOG.md, docs/nidcpower/class.rst, docs/nidcpower/enums.rst, generated/nidcpower/nidcpower/enums.py, generated/nidcpower/nidcpower/session.py, src/nidcpower/metadata/attributes_addon.py, src/nidcpower/metadata/enums_addon.py, src/nidcpower/system_tests/test_system_nidcpower.py
- Enable LCR DC bias related attributes and associated enums
- Add simple system test to set/get the newly added attributes
- Update CHANGELOG.md
The newly added system tests passed.
```
test_lcr_attributes[True] PASSED
148 passed, 5 skipped in 15.17s
```
This PR is part of a series of PRs to enable all the new LCR metadata.
=> NI-DCPower: Enable LCR DC bias metadata

CHANGELOG.md, docs/nidcpower/class.rst, docs/nidcpower/enums.rst, generated/nidcpower/nidcpower/enums.py, generated/nidcpower/nidcpower/session.py, src/nidcpower/metadata/attributes_addon.py, src/nidcpower/metadata/enums_addon.py, src/nidcpower/system_tests/test_system_nidcpower.py
- Enable LCR measurement time and source delay related attributes and associated enums
- Update CHANGELOG.md
Locally added system tests passed.
```
test_lcr_attributes[True] PASSED
148 passed, 5 skipped in 15.23s
```
This PR is part of a series of PRs to enable all the new LCR metadata.
=> NI-DCPower: Enable LCR time and delay metadata

docs/nidcpower/class.rst, generated/nidcpower/nidcpower/session.py, src/nidcpower/metadata/attributes.py, src/nidcpower/metadata/config.py, src/nidcpower/metadata/enums.py, src/nidcpower/metadata/enums_addon.py, src/nidcpower/metadata/functions.py
Metadata 22.0.0d200
- Add documentation for 'aperture time auto mode' attribute and enum
- Remove 'ni_complex_number' custom type (to be replaced with built-in Python `complex` class)
- Remove 'ni_' prefix for 'lcr_load_compensation_spot' and 'lcr_measurement' custom types
- Remove 'IsolationState' enum to be replaced with 'AttributeIsolationState' attribute class
- Remove the codegen_method override for 'IsolationState' enum now that it has been removed
Metadata 22.0.0d216
- Add valid values for "lcr current amplitude" and "lcr voltage amplitude"
- Move some description for "lcr load compensation enabled" to its "note"
- …
=> NI-DCPower: Update metadata to 22.0.0d216

CHANGELOG.md, docs/nidcpower/class.rst, docs/nidcpower/enums.rst, generated/nidcpower/nidcpower/enums.py, generated/nidcpower/nidcpower/session.py, src/nidcpower/metadata/attributes_addon.py, src/nidcpower/metadata/enums_addon.py
- Enable `aperture_time_auto_mode` and `autorange_maximum_delay_after_range_change` attributes
- Enable `aperture_time_auto_mode` enum
- Update CHANGELOG
Tested that the attributes can be retrieved correctly.
```
>>> with nidcpower.Session(resource_name='4137_sim', channels='0', options='Simulate=1, DriverSetup=Model:4137; BoardType:PXIe') as smu:
...     print(smu.aperture_time_auto_mode)
...
ApertureTimeAutoMode.OFF
>>> with nidcpower.Session(resource_name='4162_sim', channels='0', options='Simulate=1, DriverSetup=Model:4162; BoardType:PXIe') as smu:
...     print(smu.autorange_maximum_delay_after_range_change)
...
0:00:00.100000
```
=> NI-DCPower: Enable new non-LCR attributes, enum

build/templates/_mock_helper.py.mako, generated/nifake/nifake/__init__.py, generated/nifake/nifake/_library.py, generated/nifake/nifake/custom_struct_nested_typedef.py, generated/nifake/nifake/custom_struct_typedef.py, generated/nifake/nifake/session.py, generated/nifake/nifake/unit_tests/_mock_helper.py, generated/nifake/nifake/unit_tests/test_session.py, src/nifake/custom_types/custom_struct_nested_typedef.py, src/nifake/custom_types/custom_struct_typedef.py, src/nifake/metadata/attributes.py, src/nifake/metadata/config.py, src/nifake/metadata/enums.py, src/nifake/metadata/functions.py, src/nifake/nifake.mak, src/nifake/unit_tests/test_session.py
- Update NI-FAKE metadata to 22.5.0d9
- New additions:
- `custom_struct_typedef` and `custom_struct_nested_typedef` custom types
- `AltColor` enum
- `FunctionWithRepeatedCapabilityType` and `GetCustomTypeTypedef`
- Create custom type implementation files for the new `custom_struct_typedef` and `custom_struct_nested_typedef` custom types
- Update nifake.mak to copy the custom type implementation files so that the build can succeed
- Create unit test for the new `get_custom_type_typedef()` function that uses the new custom types
- Fix `_mock_helper.py.mako` codegen logic for functions with custom type parameter to use the …
=> NI-FAKE: Update metadata to 22.5.0d9, fix _mock_helper

generated/nifake/nifake/enums.py, generated/nifake/nifake/session.py, src/nifake/metadata/attributes.py, src/nifake/metadata/config.py, src/nifake/metadata/enums.py, src/nifake/metadata/functions.py
- Update NI-FAKE metadata to 22.5.0d21
- Add `EnumWithConverter` enum
- Add `read_write_enum_with_converter` attribute that uses the new enum
Note: This PR is only adding the attribute and enum without the new EnumWithConverter infrastructure, which is implemented in #1738.
Local build succeeded.
=> NI-FAKE: Add enum with converter and related attr

build/templates/session.py/get_channel_names.py.mako, generated/nifake/nifake/_library.py, generated/nifake/nifake/session.py, generated/nifake/nifake/unit_tests/_mock_helper.py, generated/nifake/nifake/unit_tests/test_session.py, src/nifake/metadata/attributes.py, src/nifake/metadata/config.py, src/nifake/metadata/enums.py, src/nifake/metadata/functions.py, src/nifake/unit_tests/test_session.py
- Update NI-FAKE metadata to 22.5.0d24 to include "GetChannelNames" and "PublicGetChannelNames"
- Create "get_channel_names.py.mako" method template to be used by public `get_channel_names()` in Session to call into `_get_channel_names()` in SessionBase
- Create unit test `test_get_channel_names()` for the new method template
* Part of the PRs to fix #1756
Related PR: #1757
The new unit test passed on my local run.
=> NI-FAKE: Create get_channel_names method template

build/templates/_attributes.py.mako, generated/nidcpower/nidcpower/_attributes.py, generated/nidigital/nidigital/_attributes.py, generated/nidmm/nidmm/_attributes.py, generated/nifake/nifake/_attributes.py, generated/nifake/nifake/unit_tests/test_session.py, generated/nifgen/nifgen/_attributes.py, generated/niscope/niscope/_attributes.py, generated/niswitch/niswitch/_attributes.py, generated/nitclk/nitclk/_attributes.py, src/nifake/unit_tests/test_session.py
- This PR addresses the review comment (https://github.com/ni/nimi-python/pull/1763/files/d89afe0da2347857a4516ef89eb881250b5b1061#r907609527)
- Update setter error message for `AttributeEnumWithConverter` to exclude the mention of the internal enum
Local build was successful. The updated tests passed successfully.
=> Update `AttributeEnumWithConverter` error message

build/helper/metadata_add_all.py
This PR is created mainly to address the comment https://github.com/ni/nimi-python/pull/1738#discussion_r905676737
- Update `_add_enum_codegen_method()` to no longer override explicitly specified codegen-method, raise ValueError instead
- Create sub-functions for `_add_enum_codegen_method()`
- `_get_functions_that_use_enums()`
- `_get_attributes_that_use_enums()`
- `_get_least_restrictive_codegen_method()`
- Update their function docstrings accordingly
- Update unit tests in "metadata_add_all.py":
- Add 'EnumWithConverter' to the unit test input
- Create `_setup_inputs_for_enum_codegen_method_tests()` to prepare the input metadata to test the new functions
- Create new unit …
=> Simplify `_add_enum_codegen_method()`

src/nidcpower/system_tests/test_system_nidcpower.py
- Add `test_measure_multiple_channel_ordering()` system test to ensure that the measurements returned by `measure_multiple()` match the order of the channels specified in the channel string
Local run of the new tests was successful.
=> NI-DCPower: Add system test for channel ordering

src/nidcpower/system_tests/test_system_nidcpower.py
Fix `nidcpower` system test - test_create_advanced_sequence_commit_step test, which was failing due to mismatch in expected vs. actual error description, by not comparing the error descriptions.
I removed all the error description checks in the `nidcpower` system tests because error code to description mapping is not done in the nimi-python layer, but in the driver runtime lower down the stack. Asserting on error code is sufficient.
* Fix #1667
PR build
=> Fix failing test - test_create_advanced_sequence_commit_step

generated/nidcpower/nidcpower/lcr_load_compensation_spot.py, generated/nidcpower/nidcpower/lcr_measurement.py, generated/nidcpower/nidcpower/unit_tests/test_nidcpower.py, src/nidcpower/custom_types/lcr_load_compensation_spot.py, src/nidcpower/custom_types/lcr_measurement.py, src/nidcpower/unit_tests/test_nidcpower.py
- Address comments from the previous LCR custom types PR:
- Remove private `_data` member variable in `LCRMeasurement` and store all the previously derived properties as member variables
- Include the previously derived properties in the class docstring
- Include units in the string representation of `LCRMeasurement` and `LCRLoadCompensationSpot`
- Use symbols instead of words to display the units
- Update system tests accordingly
- Update docstring for `reference_value` in `LCRLoadCompensationSpot`
* Fix #1781
* Fix #1782
* Fix #1783
The updated system tests passed.
=> NI-DCPower: Make LCR custom types consistent, add units

CHANGELOG.md, docs/nidcpower/class.rst, generated/nidcpower/nidcpower/_converters.py, generated/nidcpower/nidcpower/enums.py, generated/nidcpower/nidcpower/session.py, src/nidcpower/metadata/attributes_addon.py, src/nidcpower/metadata/enums_addon.py
- Enable `lcr_current_range`, `lcr_dc_bias_current_range`, `lcr_dc_bias_voltage_range` and `lcr_voltage_range` attributes
- Enable `lcr_impedance_auto_range` attribute and its associated enum with converter
- Update CHANGELOG
Local build was successful. Manually tested that the new attributes work as expected.
=> NI-DCPower: Enable LCR range attributes

CHANGELOG.md, docs/nidcpower/examples.rst, src/nidcpower/examples/nidcpower_lcr_source_ac_voltage.py
- Add "nidcpower_lcr_source_ac_voltage.py" example to demonstrate how to perform a simple AC voltage sourcing and take LCR measurements.
- Unit tests added as part of the example file passed.
- Ran the example manually, the output was as follows:
```
> python nidcpower_lcr_source_ac_voltage.py -n 4190 -c NI_STANDARD_1M
Channel             : 4190/0
DC voltage          : 4.34928e-07 V
DC current          : 1.77324e-08 A
Stimulus frequency  : 10,000 Hz
AC voltage          : 0.7+0j V RMS
AC current          : 7.12116e-05+1.68737e-07j A RMS
Impedance           : 9,829.81-23.292j Ω
Impedance magnitude : 9,829.84 Ω
Impedance phase     : -0.135763 °
Admittance          : 0.000101731+2.41053e-07j S
Admittance magnitude: 0.000101731 S
Admittance phase    : 0.135763 °
Series inductance   : …
```
=> NI-DCPower: Add LCR source AC voltage example

src/nidcpower/system_tests/test_system_nidcpower.py
As part of #1788, we need to update driver runtimes on nimibot. But due to a bug in NI-DCPower driver runtime, we need a workaround. See #1798 for details.
None
PR build
=> Workaround for nidcpower self_cal test failure due to driver runtime bug

build/templates/_attributes.py.mako, generated/nidcpower/nidcpower/_attributes.py, generated/nidcpower/nidcpower/session.py, generated/nidigital/nidigital/_attributes.py, generated/nidmm/nidmm/_attributes.py, generated/nifake/nifake/_attributes.py, generated/nifgen/nifgen/_attributes.py, generated/niscope/niscope/_attributes.py, generated/niswitch/niswitch/_attributes.py, generated/nitclk/nitclk/_attributes.py, src/nidcpower/system_tests/test_system_nidcpower.py, src/nidcpower/templates/session.py/fancy_advanced_sequence.py.mako
- Make `AttributeEnumWithConverter` inherits from `object` instead of `AttributeEnum`
- Add `_attribute_id` property to `AttributeEnumWithConverter` to be accessed by `create_advanced_sequence` method in NI-DCPower
- Update `fancy_advanced_sequence.py.mako` method template to consider `AttributeEnumWithConverter` a valid attribute class
- Add `test_create_and_delete_advanced_sequence_attribute_enum_with_converter()` system test to NI-DCPower to ensure that attribute that uses enum with converter can be used in an advanced sequence
The newly added system test passed.
=> Fix AttributeEnumWithConverter to work with AdvSeq

CHANGELOG.md, build/templates/tox-system_tests.ini.mako, generated/nidcpower/tox-system_tests.ini, generated/nidigital/tox-system_tests.ini, generated/nidmm/tox-system_tests.ini, generated/nifake/tox-system_tests.ini, generated/nifgen/tox-system_tests.ini, generated/nimodinst/tox-system_tests.ini, generated/niscope/tox-system_tests.ini, generated/nise/tox-system_tests.ini, generated/niswitch/tox-system_tests.ini, generated/nitclk/tox-system_tests.ini, src/nifgen/examples/nifgen_script.py
* Eliminates our use of numpy and scipy from the NI-FGEN example, and slightly simplifies the waveform creation, to keep the focus on the usage of NI-FGEN.
*  The new waveforms will only be a single cycle. Previous waveforms were an arbitrary 1.x cycles, because the phase ended at 10, which is greater than 2*PI and not even a multiple of 2*PI.
* The Triangle waveform in the example was actually a sawtooth. We will now refer to it as such.
* I could have added an actual triangle wave, but doing so with 0 offset would have been complicated enough that I worried I felt it would distract from the focus on the API usage.  3 or 4 lines, probably, but still the most complicated of the waveforms.
* [Scipy has stopped releasing Windows …
=> Simplify NI-FGEN example and remove its use of numpy and scipy

generated/nidigital/nidigital/session.py, src/nidigital/metadata/functions.py
#1819 mistakenly tweaked our internal exported metadata.
This change regenerates the NI-Digital API using the latest internal metadata export.
The correction made as part of the other PR was well intentioned, but incorrect. An assumption was made that because we don't allow calls to GetChannelName, the documentation should be updated to mention GetChannelNameFromString, instead. This is incorrect.
GetChannelName is what's mentioned in the C Documentation for `GetPinResultsPinInformation` and you do not pass channel indices to `GetChannelNameFromString`. We handle the details of converting indices to channel names as part …
=> Correct manual change to nidigital metadata

src/nifgen/system_tests/test_system_nifgen.py
This change does not need to be customer-facing.
This PR only requires showing that the existing 60 local tests pass. Tests will be enabled over gRPC in a future PR.
This pull request is the first step in making `nifgen`'s system-level tests use the same modification pattern that's been used in other drivers (e.g. NI-DMM, NI-Digital), in order to run tests both locally and over gRPC. This change doesn't enable fgen tests running over gRPC yet, but that step will be covered in a future PR.
* This is the first of (likely 2) PRs needed to fix [internal NI bug AB#2160601](https://ni.visualstudio.com/DevCentral/_workitems/edit/2 …
=> Define SystemTests class in `nifgen` system-level tests

src/nifgen/system_tests/test_system_nifgen.py
This change does not need to be customer-facing.
This change just enables several existing tests.
This is meant to be a cleaner and more up-to-date version of #1838 . That PR has gotten too messy and unmanageable, since it's attempting to handle several upstream code issues that have been detected and either fixed or worked around during the length of time that the PR's been open. Repeated attempts to get it into a clean state have not worked, so I'm hoping that spinning off a new branch can help get the fundamental change submitted more quickly--then we can use other work items to double back and fix individual test …
=> Enable `nifgen` tests for gRPC.

src/nidmm/system_tests/test_system_nidmm.py, src/niswitch/system_tests/test_system_niswitch.py
Just adding tests, not applicable to the change log.
Specifically this verifies one of our acceptance criteria, that locks must be reentrant. Verifying that the user can acquire the lock multiple times and perform an operation, for both native and gRPC code bases, should do the trick.
Add tests that verify the behavior of `lock()`
N/A
Add `test_locks_are_reentrant()` to both DMM and SWITCH tests.
=> Add test that verifies you can perform an operation with multiple locks

src/nidigital/system_tests/test_system_nidigital.py, src/nidmm/system_tests/test_system_nidmm.py, src/nifgen/system_tests/test_system_nifgen.py, src/niswitch/system_tests/test_system_niswitch.py
Adds session_creation_kwargs fixture to all TestLibrary/TestGrpc classes, for consistency and for reduced redundancy.
None
None
=> Add session_creation_kwargs fixture

docs/_static/niscope_usage.inc, generated/niscope/README.rst
We had mentions of Python 2 and Python 3 in the niscope module docs that are no longer relevant. This removes them.
Built the documentation locally and examined the part that was changed. Looked good to me.
=> Remove mentions of Python 2 and 3 from niscope module docs

CHANGELOG.md, generated/nidcpower/nidcpower/lcr_load_compensation_spot.py, generated/nidcpower/nidcpower/unit_tests/test_nidcpower.py, src/nidcpower/custom_types/lcr_load_compensation_spot.py, src/nidcpower/unit_tests/test_nidcpower.py
NI-DCPower: Update LCRLoadCompensationSpot byte packing alignment
- Update the byte packing alignment of `struct_NILCRLoadCompensationSpot` from 4 bytes to 8 bytes for Linux and MacOS
- Update CHANGELOG.md
- Create `test_lcr_load_compensation_spot_byte_packing_alignment()` unit test to test the byte packing alignment of `struct_NILCRLoadCompensationSpot`
Ran the newly created unit test on Windows 10 and Ubuntu 20.04, it passed on both OSes.
=> NI-DCPower: Update LCRLoadCompensationSpot byte packing alignment

.travis.yml
Tox 4.0.0 recently released and broke travis-ci builds, which now fail with
```
Traceback (most recent call last):
File "/home/travis/virtualenv/python3.10.4/bin/tox", line 8, in <module>
sys.exit(run())
File "/home/travis/virtualenv/python3.10.4/lib/python3.10/site-packages/tox/run.py", line 19, in run
result = main(sys.argv[1:] if args is None else args)
File "/home/travis/virtualenv/python3.10.4/lib/python3.10/site-packages/tox/run.py", line 38, in main
state = setup_state(args)
File "/home/travis/virtualenv/python3.10.4/lib/python3.10/site-packages/tox/run.py", line 53, in setup_state
options = get_options(*args)
File …
```
=> Use tox 3 in travis-ci builds

CHANGELOG.md, build/templates/class.rst.mako, build/templates/session.py.mako, docs/nidcpower/class.rst, docs/nidigital/class.rst, docs/nidmm/class.rst, docs/nifgen/class.rst, docs/niscope/class.rst, docs/niswitch/class.rst, generated/nidcpower/nidcpower/session.py, generated/nidigital/nidigital/session.py, generated/nidmm/nidmm/session.py, generated/nifake/nifake/session.py, generated/nifake/nifake/unit_tests/test_session.py, generated/nifgen/nifgen/session.py, generated/niscope/niscope/session.py, generated/niswitch/niswitch/session.py, src/nidcpower/system_tests/test_system_nidcpower.py, src/nidigital/system_tests/test_system_nidigital.py, src/nidmm/system_tests/test_system_nidmm.py, src/nifake/unit_tests/test_session.py, src/nifgen/system_tests/test_system_nifgen.py, src/niscope/system_tests/test_system_niscope.py, src/niswitch/system_tests/test_system_niswitch.py
Renames the optional `_grpc_options` Session parameter to `grpc_options`
None
Unit tests, etc.
=> Remove underscore prefix from grpc_options parameter

README.rst, docs/niswitch/status.inc, generated/niswitch/README.rst, src/niswitch/metadata/config_addon.py
Updated the version of the NI-SWITCH runtime which nimibot runs tests on.
Ran `tox`, which succeeded.
=> Upgrade tested version of NI-SWITCH runtime to `2022 Q4`

docs/conf.py, src/niscope/system_tests/test_system_niscope.py
[numpy 1.24 changed the array fill behavior](https://numpy.org/doc/stable/release/1.24.0-notes.html#array-fill-scalar-may-behave-slightly-different). As a result, the niscope system tests began raising an error:
>       waveform.fill(float('nan'))
>E       ValueError: cannot convert float NaN to integer
This PR changes `test_fetch_into` to no longer use waveform.fill(float('nan')). This was being done to confirm that all values were updated by the driver. Instead, the test will fill with the min supported value for the type and compare initial and final versions of the waveform to confirm that every sample has changed.
Ran …
=> Update niscope system tests to be compatible with numpy 1.24+

CHANGELOG.md, build/templates/_library_interpreter.py/lock.py.mako, build/templates/_library_interpreter.py/unlock.py.mako, docs/conf.py, generated/nidcpower/nidcpower/_library_interpreter.py, generated/nidigital/nidigital/_library_interpreter.py, generated/nidmm/nidmm/_library_interpreter.py, generated/nifake/nifake/_library_interpreter.py, generated/nifgen/nifgen/_library_interpreter.py, generated/niscope/niscope/_library_interpreter.py, generated/niswitch/niswitch/_library_interpreter.py, src/nidcpower/system_tests/test_system_nidcpower.py, src/nidigital/system_tests/test_system_nidigital.py, src/nidmm/system_tests/test_system_nidmm.py, src/nifgen/system_tests/test_system_nifgen.py, src/niscope/system_tests/test_system_niscope.py, src/niswitch/system_tests/test_system_niswitch.py, src/shared/system_test_utilities.py
- Added multi_threading system tests `test_multi_threading_ivi_synchronized_wrapper_releases_lock` that will hang if an unmanaged callerHasLock pointer is passed to _LockSession, _UnlockSession entry points.
- Tried various timeout mechanisms, but could not find a way to test the behavior without a fail hanging the tests
- Added multi_threading system test `test_multi_threading_lock_unlock` to validate locking behavior 
Restores the lock, unlock behavior that was present prior to the 1.4.3 release.
* Fix #1888 
* Wrote the NI-SCOPE multi_threading system test and ran without the fix.
* Test hanged pytest
* Implemented the fix and ran the tests again
* Test passed and did not hang.
* Wrote tests for the other APIs but did not run them locally. They will be run automatically by the PR.
=> Restore previous lock, unlock behavior

src/nidcpower/system_tests/test_system_nidcpower.py
**TL;DR**: This disables a test as a pre-requisite for updating nimibot driver runtimes.
-----------------------
The nidcpower system test `test_lcr_custom_cable_compensation_data` fails with the latest driver runtime as documented in #1908.
@marcoskirch and I discussed this offline and agreed to disable the test for now.
As part of the process for updating driver runtimes, we clone the nimi-python repo and run the system tests with the updated driver runtimes. If this fails, it will prevent us from deploying the driver runtime changes.
Therefore we must disable this test **before** we update our driver runtimes.
None
=> Skip test_lcr_custom_cable_compensation_data

tox-travis.ini, tox.ini
Use "allowlist_externals", instead of "whitelist_externals" in our tox inis.
"whitelist_externals" externals was deprecated in tox 3.18 in favor of "allowlist_externals" which works the exact same way. "whitelist_externals" is no longer supported in tox 4.
Notes:
- It turns out we're actually installing tox 4.4 in our nimibot github-runners.
- If we were doing more than just running our system tests, we would probably be failing without this change.
- travis-ci is still using tox 3.x and can't upgrade to 4.x due to incompatibility with tox-travis. See #1876. However, it's using tox 3.28 which supports allowlist_externals. …
=> Use allowlist_externals, instead of whitelist_externals

build/templates/tox-system_tests.ini.mako, generated/nidcpower/tox-system_tests.ini, generated/nidigital/tox-system_tests.ini, generated/nidmm/tox-system_tests.ini, generated/nifake/tox-system_tests.ini, generated/nifgen/tox-system_tests.ini, generated/nimodinst/tox-system_tests.ini, generated/niscope/tox-system_tests.ini, generated/nise/tox-system_tests.ini, generated/niswitch/tox-system_tests.ini, generated/nitclk/tox-system_tests.ini, src/nidcpower/system_tests/test_system_nidcpower.py, src/nidigital/system_tests/test_system_nidigital.py, src/nidmm/system_tests/test_system_nidmm.py, src/nifgen/system_tests/test_system_nifgen.py, src/niscope/system_tests/test_system_niscope.py, src/niswitch/system_tests/test_system_niswitch.py, src/shared/system_test_utilities.py
The [`test_multi_threading_ivi_synchronized_wrapper_releases_lock` test in niswitch system tests is currently raising `pytest.PytestUnhandledThreadExceptionWarning`](https://github.com/ni/nimi-python/actions/runs/4567686137/jobs/8209768533) in Python 3.8 (earliest version where pytest catches these exceptions) and later due to ` niswitch.errors.DriverError: -1074135023: IVI: Function or method not supported.`. This is caused by the simulated device not supporting abort. The other simulated device typically used in niswitch system tests supports abort but will also raise a DriverError if called immediately after initialization due to no scans being in progress.
This change does 2 …
=> Fix niswitch multithreading test warnings

build/templates/tox-system_tests.ini.mako, generated/nidcpower/tox-system_tests.ini, generated/nidigital/tox-system_tests.ini, generated/nidmm/tox-system_tests.ini, generated/nifake/tox-system_tests.ini, generated/nifgen/tox-system_tests.ini, generated/niscope/tox-system_tests.ini, generated/niswitch/tox-system_tests.ini
[win32 system tests are failing](https://github.com/ni/nimi-python/actions/runs/4661450262/jobs/8250740177?pr=1916) due to the [absence of a win32 Python 3.7 wheel for grpcio 1.53.](https://pypi.org/simple/grpcio/)
>grpcio-1.53.0-cp311-cp311-win32.whl
grpcio-1.53.0-cp311-cp311-win_amd64.whl
grpcio-1.53.0-cp37-cp37m-linux_armv7l.whl
grpcio-1.53.0-cp37-cp37m-macosx_10_10_universal2.whl
grpcio-1.53.0-cp37-cp37m-manylinux_2_17_aarch64.whl
grpcio-1.53.0-cp37-cp37m-manylinux_2_17_i686.manylinux2014_i686.whl
grpcio-1.53.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
grpcio-1.53.0-cp37-cp37m-musllinux_1_1_i686.whl …
=> Exclude gprcio 1.53 from test dependencies to fix win32 system test failures

CHANGELOG.md, docs/nidcpower/class.rst, docs/nidcpower/enums.rst, generated/nidcpower/nidcpower/enums.py, generated/nidcpower/nidcpower/session.py, src/nidcpower/metadata/attributes.py, src/nidcpower/metadata/config.py, src/nidcpower/metadata/enums.py, src/nidcpower/metadata/functions.py
- No new methods added to warrant a new test
- Add entrypoints for NI-DCPower 23.3 driver runtime
None
Just manual analysis
1. At the time of internal metadata updates, a diff of nidcpower.h was analyzed for changes
>Analysis of Diff
>
>Added Attributes (all enabled by this changed)
>* NIDCPOWER_ATTR_LCR_AC_ELECTRICAL_CABLE_LENGTH_DELAY: enabled by this change
>* NIDCPOWER_ATTR_LCR_DC_BIAS_TRANSIENT_RESPONSE
>* NIDCPOWER_ATTR_LCR_AC_DITHER_ENABLED
>* NIDCPOWER_ATTR_LCR_SOURCE_APERTURE_TIME
>
>Added Enums / Enum Values (all enabled by this change)
>* NIDCPOWER_VAL_NI_STANDARD_0_5M (value for NIDCPOWER_ATTR_CABLE_LENGTH)
>* NIDCPOWER_ATTR_LCR_DC_BIAS_TRANSIENT_RESPONSE (enum)
>   * NIDCPOWER_VAL_LCR_DC_BIAS_TRANSIENT_RESPONSE_NORMAL …
=> Implement nidcpower API parity with NI-DCPower 2023 Q2

.github/workflows/github_actions_aws_rhel_python64.yml, .github/workflows/github_actions_aws_windows_python32.yml, .github/workflows/github_actions_aws_windows_python64.yml, .travis.yml, build/templates/tox-system_tests.ini.mako, generated/nidcpower/tox-system_tests.ini, generated/nidigital/tox-system_tests.ini, generated/nidmm/tox-system_tests.ini, generated/nifake/tox-system_tests.ini, generated/nifgen/tox-system_tests.ini, generated/nimodinst/tox-system_tests.ini, generated/niscope/tox-system_tests.ini, generated/nise/tox-system_tests.ini, generated/niswitch/tox-system_tests.ini, generated/nitclk/tox-system_tests.ini
The "codecov" project mysteriously disappeared from PyPI overnight breaking all of our PR checks, because they now fail to install it.
The [repo says the tool was deprecated in Feb 2022 and no longer able to upload coverage.](https://github.com/codecov/codecov-python) It also says it was archived in Jan 2023.
- Based on guidance from the codecov-python repo, [I have updated our PR checks to use the new uploader in travis-ci](https://docs.codecov.com/docs/codecov-uploader).
- For our nimibot runners, I have removed the upload step from tox-system_tests.ini and added a step in our actions ymls [using  the Codecov Actions …
=> Fix PR check failures caused by disappearance of codecov from PyPI

src/niscope/system_tests/test_system_niscope.py
Enable the following tests for TestGrpc:
- `test_get_self_cal_last_date_time`
- `test_get_ext_cal_last_date_time`
- `test_get_self_cal_last_temperature`
- `test_get_ext_cal_last_temperature`
None
Ran the tests on a local machine
=> Enable niscope cal time and temperature tests for TestGrpc

CHANGELOG.md, build/templates/grpc_session_options.py.mako, generated/nidigital/nidigital/grpc_session_options.py
Update `nidigital.GRPC_SERVICE_INTERFACE_NAME` to use the correct gRPC package name (`nidigitalpattern_grpc`, not `nidigital_grpc`).
* Fix #1939 
Inspected codegen.
=> nidigital: Update GRPC_SERVICE_INTERFACE_NAME to use correct gRPC package name

build/templates/setup.py.mako, generated/nidcpower/setup.py, generated/nidigital/setup.py, generated/nidmm/setup.py, generated/nifake/setup.py, generated/nifgen/setup.py, generated/niscope/setup.py, generated/niswitch/setup.py
[win32 system tests are failing again](https://github.com/ni/nimi-python/actions/runs/4769024938/jobs/8478982122?pr=1950) due to the [absence of a win32 Python 3.7 wheel for grpcio 1.54.](https://pypi.org/simple/grpcio/)
The runner lacks the necessary software to build the wheel from scratch and we don't want users to have to deal with building the wheel from scratch for this optional dependency either, particularly because they don't actually need the latest grpcio.
This is a recurrence of the problem fixed by #1917, caused by the very next release of grpcio. We'll just cap the grpcio version for Python 3.7. We don't want …
=> Cap grpcio dependency at <1.53 for Python 3.7

build/helper/documentation_helper.py, build/templates/errors.py.mako, generated/nidcpower/nidcpower/errors.py, generated/nidigital/nidigital/errors.py, generated/nidmm/nidmm/errors.py, generated/nifake/nifake/errors.py, generated/nifake/nifake/unit_tests/test_grpc.py, generated/nifake/nifake/unit_tests/test_library_interpreter.py, generated/nifake/nifake/unit_tests/test_session.py, generated/nifgen/nifgen/errors.py, generated/nimodinst/nimodinst/errors.py, generated/nimodinst/nimodinst/unit_tests/test_modinst.py, generated/niscope/niscope/errors.py, generated/nise/nise/errors.py, generated/niswitch/niswitch/errors.py, generated/nitclk/nitclk/errors.py, generated/nitclk/nitclk/unit_tests/test_nitclk.py, src/nifake/unit_tests/test_grpc.py, src/nifake/unit_tests/test_library_interpreter.py, src/nifake/unit_tests/test_session.py, src/nimodinst/system_tests/test_system_nimodinst.py, src/nimodinst/unit_tests/test_modinst.py, src/nitclk/unit_tests/test_nitclk.py
TL;DR: Fix flake8 PR Check failures by adding a space between `assert` and `(`. Also do some optional cleanup of issues we noticed in asserts.
Due to a bump in the version of flake8 used in our travis-ci runs  (seems to be caused by a version bump of another depedency), we are now using flake8 5.0.4.
Aside: Previously, we used flake8 4.0.1 and there is already a 6.0.0.
Due to the version bump, flake8 now raises the complaint "E275 missing whitespace after keyword" on `assert(`. Apparently `assert` is only a keyword, not a method.
Fixes:
* space between `assert` and `(`
* Remove redundant parentheses in assert statements
* …
=> Clean up assert statements

CHANGELOG.md, docs/niscope/class.rst, generated/niscope/niscope/_grpc_stub_interpreter.py, generated/niscope/niscope/_library.py, generated/niscope/niscope/_library_interpreter.py, generated/niscope/niscope/session.py, generated/niscope/niscope/unit_tests/_mock_helper.py, src/niscope/metadata/functions_addon.py, src/niscope/system_tests/test_system_niscope.py
Add the `get_channel_names` method to the niscope API. Per the decision made in #1386, `get_channel_name` and `get_channel_name_from_string` will not be added. This will be the only entrypoint for translating channel indices to names.
Implementation:
Copied the current metadata from nidigital and tweaked parameter names and some hidden parameter documentation for niscope.
* Fix #1402
* Copied `test_get_channel_names` from nidigital and modified it for niscope. It passes.
=> Add get_channel_names to niscope API

CHANGELOG.md, generated/niscope/niscope/session.py, src/niscope/system_tests/test_system_niscope.py, src/niscope/templates/session.py/fancy_fetch.py.mako, src/niscope/templates/session.py/fancy_fetch_array_measurement.py.mako, src/niscope/templates/session.py/fancy_fetch_measurement_stats.py.mako, src/niscope/templates/session.py/fetch_waveform.py.mako, src/niscope/templates/session.py/fetch_waveform_info_population.py.mako
Based on how nidcpower does things for `fetch_multiple`, `measure_multiple`, etc., expand the _repeated_capability (channels) before trying to do anything with it, other than pass it to a driver function.
The driver knows how to handle unexpanded channel strings (or it will error if it can't), but the simple code in 
`_populate_channel_and_record_info` assumes that all channels in the `channels` iterable are individual channels.
* Fix #1770
* Locally, I used the tests changes to catch the bug, then ran codegen with the changes in this PR (prior to the latest merge) and #1957 to confirm that the issue would be fixed.
* PR Checks
* I played with the tests to make sure there wasn't some other bad data case to worry about for single-instrument sessions. Passing a qualified name to `fetch()` …
=> niscope: expand channels repeated_capability before populating channel and record info in fetched data

.github/workflows/github_actions_aws_rhel_python64.yml, .github/workflows/github_actions_aws_windows_python32.yml, .github/workflows/github_actions_aws_windows_python64.yml
The nimibot GitHub actions workflows are updated to use v3 of the GitHub checkout action. v2 used Node.js 12 and this was causing annotations about it being deprecated to appear in the nimibot run summaries.
[With v3, node16  runtime is used by default](https://github.com/actions/checkout/tree/8e5e7e5ab8b370d6c329ec480221332ada57f0ab#whats-new).
* Fix #1909 
PR Checks.
The annotations are gone. See
* https://github.com/ni/nimi-python/actions/runs/5027414297?pr=1969
* https://github.com/ni/nimi-python/actions/runs/5027414296?pr=1969
* https://github.com/ni/nimi-python/actions/runs/5027414299?pr=1969
Ignore the failing …
=> Use actions/checkout@v3

CHANGELOG.md, generated/niswitch/niswitch/_grpc_stub_interpreter.py, generated/niswitch/niswitch/_library.py, generated/niswitch/niswitch/_library_interpreter.py, generated/niswitch/niswitch/unit_tests/_mock_helper.py, src/niswitch/metadata/attributes.py, src/niswitch/metadata/config.py, src/niswitch/metadata/enums.py, src/niswitch/metadata/functions.py
- ~[] I've added tests applicable for this pull request~
This feature is tested through nifake unit tests.
* niswitch metadata is updated from the latest internal export.
* `set_runtime_environment` call is added to niswitch/_library_interpreter.py
None
None
=> Add set_runtime_environment functionality to niswitch

build/templates/class.rst.mako, build/templates/conf.py.mako, docs/nidcpower/conf.py, docs/nidigital/class.rst, docs/nidigital/conf.py, docs/nidmm/conf.py, docs/nifgen/class.rst, docs/nifgen/conf.py, docs/nimodinst/conf.py, docs/niscope/class.rst, docs/niscope/conf.py, docs/nise/conf.py, docs/niswitch/conf.py, docs/nitclk/conf.py
Links between our new separate Read the Docs projects have not been setup. This change creates them by:
* Adding intersphinx mappings for each of the other projects to every project
* Fixing the way we reference the class nitclk.SessionReference
* This was the only link found in the docs
None
Generated docs locally and was able to click on the link to nitclk.SessionReference from nidigital documentation
=> Add intersphinx mappings

CHANGELOG.md, src/nidcpower/examples/nidcpower_measure_record.py
I've been auditing our NI-DCPower examples for all of our supported ADEs to ensure that they specify Output Function rather than assuming a default value.  The nidcpower_measure_record python example expects the Output Function to be DC Voltage but does not explicitly set it, so I've updated this example to explicitly set the Output Function.
I've run the example manually on several NI-DCPower devices to ensure that it functions as expected.
=> NI-DCPower: Ensure examples specify Output Function when necessary

CHANGELOG.md, build/templates/_library_singleton.py.mako, generated/nidcpower/nidcpower/_library_singleton.py, generated/nidigital/nidigital/_library_singleton.py, generated/nidmm/nidmm/_library_singleton.py, generated/nifake/nifake/_library_singleton.py, generated/nifake/nifake/unit_tests/test_library_singleton.py, generated/nifgen/nifgen/_library_singleton.py, generated/nimodinst/nimodinst/_library_singleton.py, generated/niscope/niscope/_library_singleton.py, generated/nise/nise/_library_singleton.py, generated/niswitch/niswitch/_library_singleton.py, generated/nitclk/nitclk/_library_singleton.py, src/nifake/unit_tests/test_library_singleton.py
The code to load a DLL may change over time, leading to it returning different errors. This led to us returning a poor error when the driver runtime is not installed.
To improve our error behavior, raise a DriverNotInstalledError at the step where we look for the library, if it's not found. This happens before we attempt to load the library and since determining that the library wasn't found doesn't rely on getting a specific error, our behavior will be less likely to change.
Also add a test to cover this behavior.
* Fix #1970
* Added a unit test.
* Ran it without the fix: it failed
* Ran it with the fix: it passed
There's nothing OS-specific about `_get_library_name()`, so it should be okay that the unit tests only run on Linux.
=> Raise error if library not found, before attempting to load it

CHANGELOG.md, build/helper/codegen_helper.py, build/unit_tests/test_codegen_helper.py, generated/nidcpower/nidcpower/_library_interpreter.py, generated/nidigital/nidigital/_library_interpreter.py, generated/nidigital/nidigital/session.py, generated/nidmm/nidmm/_library_interpreter.py, generated/nifake/nifake/_library_interpreter.py, generated/nifake/nifake/unit_tests/test_library_interpreter.py, generated/nifgen/nifgen/_library_interpreter.py, generated/niscope/niscope/_library_interpreter.py, src/nidigital/templates/_library_interpreter.py/fancy_fetch_capture_waveform.py.mako, src/nidigital/templates/session.py/fancy_write_source_waveform_site_unique.py.mako, src/nifake/unit_tests/test_library_interpreter.py
When allocating a buffer, nimi-python APIs create a list of 0s then copy them into an array.array that is being initialized, causing allocation of the array to take much longer than necessary. For large buffers, the extra time spent allocating and copying the list is significant.
This change updates the allocation process to instead create a single element list `[0]` that is copied into the array, then use the `*` operator to extend the array to a specified number of elements.
* Fix #1998
Functional: System and Unit tests
Performance: 
1. Tested allocation time of arrays of various sizes with both methods. When allocation time was not negligible (0 s measured), the new method consistently allocated faster, typically with a …
=> Faster Array Allocation

README.rst, docs/_static/nidmm_usage.inc, generated/nidmm/README.rst
This change fixes the nidmm example shown in nidmm.readthedocs.io, and the NI-DMM and general READMEs. Right now, if you attempt to run this code, you get:
```
AttributeError: 'Session' object has no attribute 'configureMeasurementDigits'
```
(Based upon #2003)
* #1476 
Tested in original PR: #2003
=> Fix nidmm usage example

src/nifgen/system_tests/test_system_nifgen.py
Beginning with NI-FGEN 2023Q3, the error returned in the nifgen system test "test_error_message" has changed, causing the test to fail in our internal test suite. When we update the version of NI-FGEN installed to nimi-bot, the failure will occur in nimi-python PR checks as well.
This updates the test to accept both the new error code and descrption and the old ones.
* Fix #1987
Ran the nifgen system tests with NI-FGEN 2023Q4 (in-dev version).
=> Accept multiple error codes, descriptions in nifgen system test test_error_message

src/nifgen/system_tests/test_system_nifgen.py
Stop using DAQmx-based simulated device in nifgen system tests, now that the internal issues [AB#227842](https://dev.azure.com/ni/DevCentral/_workitems/edit/227842) and [AB#999932](https://dev.azure.com/ni/DevCentral/_workitems/edit/999932) are fixed.
This is a reimplementation of #1598 against master with minor fixes.
* Fix #1375
* Fix #1376
Ran nifgen system tests on a local machine with NI-FGEN 2023Q4 (in-dev version) installed.
Unfortunately, this change only seems to cut test time by a second or two.
PR Checks
=> Use simulated 5433 for all nifgen system tests

.github/workflows/github_actions_aws_rhel_python64.yml, .github/workflows/github_actions_aws_windows_python32.yml, .github/workflows/github_actions_aws_windows_python64.yml
[My fork tried to run the Windows 64-bit Python workflow on its master branch](https://github.com/ni-jfitzger/nimi-python/actions/runs/6290588363) due to 
#2014.
Based on https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-run-job-for-specific-repository
None
None. We'll know if it works when I sync my fork, after the merge.
=> Do not run workflows on forks

src/nidmm/system_tests/test_system_nidmm.py
In a recent version of the NI-DMM, the reported serial of a simulated DMM was intentionally changed. This causes the nidmm system test `test_vi_string_attribute` to fail in our internal test suite and will cause failures in PR Checks when we update the version we test against.
This change updates the test to rely on `instrument_model`, instead of `serial_number`. They are both read-only properties and we do not expect the reported value for `instrument_model` to change in the future.
* Fix #2012
* Ran the nidmm system tests on a local machine with a dev version NI-DMM 2023Q4 installed and confirmed that the test failed.
* Updated the test and ran again, confirming that the test passed.
* PR Checks will confirm that the updated test passes with the driver runtime that we currently test …
=> Use instrument_model property in nidmm system test test_vi_string_attribute

.travis.yml
We're not uploading our niscope unit test coverage when we run travis-ci. This change fixes that.
None
Confirmed that niscopeunittest coverage was uploaded for this PR.
https://app.codecov.io/github/ni/nimi-python/commit/f3a6309343c5b58ce732149b4d8d16d88e90a61b
=> Upload niscope unit test coverage in .travis.yml

build/templates/.readthedocs.yaml.mako, docs/nidcpower/.readthedocs.yaml, docs/nidigital/.readthedocs.yaml, docs/nidmm/.readthedocs.yaml, docs/nifgen/.readthedocs.yaml, docs/nimodinst/.readthedocs.yaml, docs/niscope/.readthedocs.yaml, docs/nise/.readthedocs.yaml, docs/niswitch/.readthedocs.yaml, docs/nitclk/.readthedocs.yaml, docs/requirements.txt
Documentation is failing to build due to the theme not being found. Most likely, Read the Docs changed something so that their theme is no longer installed by default.
This change updates  the .readthedocs.yamls to install the theme.
I don't have time to properly add a requirements file, right now, so this is just a band-aid: a sort-of requirements file to get the dependency installed. We still have an open issue to properly add a requirements file for the sphinx build.
* Fix #2028
None. If the PR checks pass, it should fix the issue.
=> Install read_the_docs theme in .readthedocs.yaml

build/unit_tests/test_metadata_add_all.py, generated/nifake/nifake/unit_tests/test_grpc.py, generated/nifake/nifake/unit_tests/test_session.py, generated/nimodinst/nimodinst/unit_tests/test_modinst.py, src/nifake/unit_tests/test_grpc.py, src/nifake/unit_tests/test_session.py, src/nimodinst/unit_tests/test_modinst.py, src/nitclk/system_tests/test_system_nitclk.py
`build_test` and `flake8` started failing with the latest dependencies.
Example:
```
build/unit_tests/test_metadata_add_all.py:18:12: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
assert type(actual) == type(expected), 'Type mismatch, {0} != {1}'.format(type(actual), type(expected))
^
build/unit_tests/test_metadata_add_all.py:25:12: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
assert type(actual) == type(expected), 'Type mismatch, {0} != {1}'.format(type(actual), type(expected))
```
This change fixes those …
=> Do not compare types

docs/nidcpower/conf.py, docs/nidigital/conf.py, docs/nidmm/conf.py, docs/nifgen/conf.py, docs/nimodinst/conf.py, docs/niscope/conf.py, docs/nise/conf.py, docs/niswitch/conf.py, docs/nitclk/conf.py
The time between when the last PR was posted and when it was merged was so long that the year changed, leading the merged code to not mach `tox -e codegen` and [causing the `travis-ci` build of the commit to fail](https://github.com/ni/nimi-python/runs/20597088068).
None
PR Checks
=> Update copyright date to 2024 so that travis-ci passes

.github/actions/linux/action.yml, .github/actions/windows/action.yml, build/templates/tox-system_tests.ini.mako, generated/nidcpower/tox-system_tests.ini, generated/nidigital/tox-system_tests.ini, generated/nidmm/tox-system_tests.ini, generated/nifake/tox-system_tests.ini, generated/nifgen/tox-system_tests.ini, generated/nimodinst/tox-system_tests.ini, generated/niscope/tox-system_tests.ini, generated/nise/tox-system_tests.ini, generated/niswitch/tox-system_tests.ini, generated/nitclk/tox-system_tests.ini
* Stop creating the unused kibana jsons 
* Assign a different junitxml name to example test results, so they are not overwrriten by system test results
* junitxmls are only used by our internal test suites
* Fix #2041
* Ran the system tests on a local machine for niswitch.
* Confirmed that results were being overwritten
* Confirmed that the changes produce 2 seprate test result files, so nothing is overwritten
=> Do not overwrite example testing results

CHANGELOG.md, docs/nidcpower/class.rst, docs/nidcpower/conf.py, docs/nidcpower/enums.rst, docs/nidigital/conf.py, docs/nidmm/conf.py, docs/nifgen/conf.py, docs/nimodinst/conf.py, docs/niscope/conf.py, docs/nise/conf.py, docs/niswitch/conf.py, docs/nitclk/conf.py, generated/nidcpower/nidcpower/enums.py, generated/nidcpower/nidcpower/session.py, src/nidcpower/metadata/attributes.py, src/nidcpower/metadata/config.py, src/nidcpower/metadata/enums.py, src/nidcpower/metadata/functions.py, src/nidcpower/system_tests/test_system_nidcpower.py
Updates metadata for nidcpower to latest 25.0 export.
Resulting changes:
- Adds `INHIBITED` to enum `OutputStates`
- Changes `OuputStates.VOLTAGE` and `OutputStates.CURRENT` enum value names to `OuputStates.CONSTANT_VOLTAGE` and `OutputStates.CONSTANT_CURRENT` respectively
- Updates documentation for `measure_buffer_size`, `measure_complete_event_delay`, `source_delay`, and `merged_channels` attributes
- Updates copyright year in the `conf.py` files in other modules so that the build passes
- Fix #2067
PR checks
=> Update nidcpower metadata

CHANGELOG.md, build/templates/setup.py.mako, generated/nidcpower/setup.py, generated/nidigital/setup.py, generated/nidmm/setup.py, generated/nifake/setup.py, generated/nifgen/setup.py, generated/nimodinst/setup.py, generated/niscope/setup.py, generated/nise/setup.py, generated/niswitch/setup.py, generated/nitclk/setup.py
Delete deprecated / unsupported imports and distribution options from setup.py. By doing this proactively, we can avoid being broken in the future.
According to GitHub Copilot, `setuptools.command.test` provides a way to setup for and run tests. It would happen in this case when users run `python setup.py test`.
The problems with that are:
1. We don't ship tests with our python packages
1. If someone has cloned the repo, we have guidelines for how to run tests and they don't involve making that call
1. 2 of the distribution options associated with this feature (`tests_require` and `test_suite`) are no longer recognized.
1. setuptools.command.test has been deprecated for years
For these reasons, it makes sense to just remove the …
=> Eliminate use of dead and deprecated imports and options in setup.py

.travis.yml, CHANGELOG.md, build/templates/setup.py.mako, build/templates/tox-system_tests.ini.mako, generated/nidcpower/setup.py, generated/nidcpower/tox-system_tests.ini, generated/nidigital/setup.py, generated/nidigital/tox-system_tests.ini, generated/nidmm/setup.py, generated/nidmm/tox-system_tests.ini, generated/nifake/setup.py, generated/nifake/tox-system_tests.ini, generated/nifgen/setup.py, generated/nifgen/tox-system_tests.ini, generated/nimodinst/setup.py, generated/nimodinst/tox-system_tests.ini, generated/niscope/setup.py, generated/niscope/tox-system_tests.ini, generated/nise/setup.py, generated/nise/tox-system_tests.ini, generated/niswitch/setup.py, generated/niswitch/tox-system_tests.ini, generated/nitclk/setup.py, generated/nitclk/tox-system_tests.ini, tox-travis.ini, tox.ini
* Drop Python 3.8 support, by removing it from our testing and list of officially supported versions.
* (For the first time) enforce our version support policy at installation: disallow installation of APIs on Python versions earlier than 3.9
* As part of this we now need to specify a list of supported Python versions for building wheel_dep in tox-system_tests.ini
None
PR Checks
=> Drop Python 3.8 Support

src/nidcpower/system_tests/grpc_server_config.json, src/nidcpower/system_tests/test_system_nidcpower.py, src/nidigital/system_tests/grpc_server_config.json, src/nidigital/system_tests/test_system_nidigital.py, src/nidmm/system_tests/grpc_server_config.json, src/nidmm/system_tests/test_system_nidmm.py, src/nifgen/system_tests/grpc_server_config.json, src/nifgen/system_tests/test_system_nifgen.py, src/niscope/system_tests/grpc_server_config.json, src/niscope/system_tests/test_system_niscope.py, src/niswitch/system_tests/grpc_server_config.json, src/niswitch/system_tests/test_system_niswitch.py, src/shared/system_test_utilities.py
Several different gRPC device server processes are created when running system tests, but all these different processes default to the same port, 31763. This collision is causing tests to fail to run.
[AB#3048787](https://dev.azure.com/ni/DevCentral/_workitems/edit/3048787)
=> Make each product use their own gRPC Device Server ports in the System Tests

CHANGELOG.md, docs/nidcpower/class.rst, docs/nidcpower/enums.rst, generated/nidcpower/nidcpower/enums.py, generated/nidcpower/nidcpower/session.py, src/nidcpower/metadata/attributes.py, src/nidcpower/metadata/config.py, src/nidcpower/metadata/enums.py, src/nidcpower/metadata/functions.py
- Update the metadata for NI-DCPower to 25.3.0f265
- Update the generated enums.py and session.py files as well as the docs files
- Update CHANGELOG.md to call out the API parity changes
Local run of tox was successful.
Local run of the system tests (`py312-nidcpower-system_tests`) was also successful.
=> NI-DCPower: Add API parity with NI-DCPower 2025 Q2

CHANGELOG.md, docs/nidcpower/examples.rst, src/nidcpower/examples/nidcpower_advanced_sequence.py, src/nidcpower/examples/nidcpower_constant_resistance_and_constant_power.py, src/nidcpower/examples/nidcpower_lcr_source_ac_voltage.py, src/nidcpower/examples/nidcpower_measure_record.py, src/nidcpower/examples/nidcpower_sink_dc_current_into_electronic_load.py, src/nidcpower/examples/nidcpower_source_delay_measure.py
- Add `nidcpower_constant_resistance_and_constant_power.py` and `nidcpower_sink_dc_current_into_electronic_load.py`
- Regenerate `docs/nidcpower/examples.rst`
- Update CHANGELOG.md to call out the new examples
- Update the help string for the `--option-string` parameter to "Option String" based on IVI convention
- Unit tests added as part of the example file passed.
- Both `tox` and `tox -c .\generated\nidcpower\tox-system_tests.ini` succeeded
=> NI-DCPower: Add examples for electronic loads

docs/nirfsg/class.rst, docs/nirfsg/enums.rst, docs/nirfsg/rep_caps.rst, generated/nirfsg/nirfsg/_library.py, generated/nirfsg/nirfsg/_library_interpreter.py, generated/nirfsg/nirfsg/enums.py, generated/nirfsg/nirfsg/session.py, generated/nirfsg/nirfsg/unit_tests/_mock_helper.py, src/nirfsg/metadata/attributes.py, src/nirfsg/metadata/config.py, src/nirfsg/metadata/enums.py, src/nirfsg/metadata/functions.py, src/nirfsg/system_tests/test_system_nirfsg.py
- Enables intflag parameter for self_calibrate_range and adds reset_with_options method
- Overriding doc_tip for stepsToOmit parameter to call out Bitwise input (this should be done in codegen itself in the future)
- Expands shortened terms in enum names to full terms
- Adds lo_channels repeated capability and changed deembedding_port into ports repcap since ports is used by API other then deembedding as well
- Marks relevant attributes with the same
- Makes waveform repcap name plural to align with repcap naming policy
- Fixes few enum values and documentation snippets
- Removes few enums that are not used by any attribute or function
- Ensures all method description start with \n consistently
- Removes p2p related methods, enums, enum values and attributes
- Removes leftover …
=> Adding and removing few methods and few more fixes in RFSG

docs/nirfsg/class.rst, docs/nirfsg/enums.rst, docs/nirfsg/rep_caps.rst, generated/nirfsg/nirfsg/_library.py, generated/nirfsg/nirfsg/_library_interpreter.py, generated/nirfsg/nirfsg/enums.py, generated/nirfsg/nirfsg/session.py, generated/nirfsg/nirfsg/unit_tests/_mock_helper.py, src/nirfsg/metadata/attributes.py, src/nirfsg/metadata/config.py, src/nirfsg/metadata/enums.py, src/nirfsg/metadata/functions.py, src/nirfsg/system_tests/test_system_nirfsg.py, src/nirfsg/templates/session.py/create_deembedding_sparameter_table_array.py.mako, src/nirfsg/templates/session.py/get_deembedding_sparameter.py.mako, src/nirfsg/templates/session.py/write_arb_waveform.py.mako
- Removes export signal method
- Adds configure deembedding table array and get deembedding table methods
- Adds system tests to validate these
- Both involve their own custom expansions
- configure deembedding table array needed a fancy function with custom expansion since we need to ensure valid incoming array and also need to pass number of ports parameter to C
- get deembedding table method needed custom expansion since we use a different method call to get the size to use
- Fixed a shortened enum name
- Renamed few repeated capabilities and added few
- Minor error string fixes 
None
System tests succeed on both simulated and real hardware.
=> Enable deembedding methods and more misc changes

build/helper/helper.py, docs/nirfsg/class.rst, docs/nirfsg/enums.rst, generated/nirfsg/nirfsg/_library.py, generated/nirfsg/nirfsg/_library_interpreter.py, generated/nirfsg/nirfsg/enums.py, generated/nirfsg/nirfsg/session.py, generated/nirfsg/nirfsg/unit_tests/_mock_helper.py, src/nirfsg/metadata/attributes.py, src/nirfsg/metadata/config.py, src/nirfsg/metadata/enums.py, src/nirfsg/metadata/functions.py, src/nirfsg/system_tests/test_system_nirfsg.py, src/nirfsg/templates/session.py/get_deembedding_sparameter.py.mako, src/nirfsg/templates/session.py/write_arb_waveform.py.mako
- Updated the get_development_status codegen helper logic to allow a override of development status via config_addon(this will be used for setting development status for RFSG release, which does not align with existing version based logic)
- Adding rfsg metadata files out of internal codegeneration tool
- Corrected couple of enum names
- Documentation corrections
- functions.py and attributes.py will contain re-arranged entries, but the generated API being unchanged should validate that its just re-arranged
- Few default value fields got removed
- Repcap related fields for functions got added by the codegen tool
- Cleaned up get_deembedding_sparameters method to correctly have only one return value (matches .NET API)
- Needed to add fancy function to get this working correctly
- Corrected …
=> NI-RFSG metadata from codegenerated files with some cleanup and dev status override logic

src/nifgen/system_tests/test_system_nifgen.py
~- [ ]  I've updated [CHANGELOG.md](https://github.com/ni/nimi-python/blob/master/CHANGELOG.md) if applicable.~
The value of `maximum_sequence_length` will be updated in the upcoming NI-FGEN release, hence this PR is to update the NI-FGEN system tests to simply verify that `maximum_sequence_length` >= `minimum_sequence_length` instead of a specific value. This should be sufficient for an API test.
That driver change is causing our internal nimi-python test events to fail, so we need this update to fix those failures.
=> NI-FGEN: Update expected `maximum_sequence_length` in test_query_arb_seq_capabilities
